### ISSUE TITLE
Custom Pygments Lexer?

### ISSUE THREAD

**Issue by a-hurst** [randy3k/radian#100]
Today I went to set up radian on my workstation, only to find that the default colour scheme was different than on my laptop. After ensuring both were running the same versions of iTerm, Python, radian, R, etc. and getting increasingly confused, I narrowed it down to a difference in Pygments versions between the two machines. With Pygments == 2.2.0 on my laptop, radian looks like this:

![Screen Shot 2019-06-17 at 6 32 21 PM](https://user-images.githubusercontent.com/18648066/59641352-3af2ec80-912f-11e9-84e9-1978c26fad0a.png)

With Pygments == 2.4.2 on my workstation, radian now looks like this:

![Screen Shot 2019-06-17 at 6 33 33 PM](https://user-images.githubusercontent.com/18648066/59641378-4c3bf900-912f-11e9-9eaf-218b036c5e9a.png)

Looking at the changelog for Pygments it looks like the R lexer got a rewrite in version 2.3.1, which simplified the code at the expense of diversity of colours (see [here](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/680/slexer-improvements/diff) for the pull request that did it).

I personally much prefer the older style of pygments highlighting, since it's a lot easier to tell functions, types, and numbers all apart at a glance when they're not all approximately the same shade of blue. If you feel the same way, I was wondering whether it might be a good idea to add a custom R lexer to radian that brings back the old colour coding (or something similarly easy to parse visually)?

Thanks in advance, and thanks for creating/maintaining this excellent package!

**Comment by randy3k** [comment]
You could always create a python virtual environment and pin the version of Pygments

**Comment by a-hurst** [comment]
Oh, I've already written a custom lexer that's based on the cleaner code of the new one but retains the colourfulness of the old one. I was just wondering whether you were interested in having a custom lexer for radian that overrides the new pygments default for R and is easier to parse visually, so I could know whether or not to make a pull request.

**Comment by a-hurst** [comment]
Ah no, the idea would be to include a custom R lexer class within radian itself, and then import that in prompt.py instead of the default Pygments SLexer (see my branch here for the implementation, it just involves adding a new file and changing one line in prompt.py: https://github.com/a-hurst/radian/commit/cc903efc811034eec4916e806f509e068099fe3a).

The custom lexer in the fork above is essentially just the current Pygments R lexer, but it brings back the old colour scheme so it's not all blue and white, and adds back differentiation of data type and library()/detach()/etc. calls from normal functions like the earlier version did. Here's what it looks like in action (note: colour highlighting of outputs is due to a different package 'colorout' and not anything I did to the lexer):

![Screen Shot 2019-09-13 at 6 33 48 PM](https://user-images.githubusercontent.com/18648066/64898717-35397400-d656-11e9-87ff-4ef44d762d8a.png)

Let me know what you think!

**Comment by randy3k** [comment]
I like it! I would consider merging it if you make a PR.
