### ISSUE TITLE
Assertion Error For stdout.isatty()

### ISSUE THREAD

**Issue by gfleetwood** [randy3k/radian#103]
Hi,

I'm trying to write a simple GUI wrapper around radian but I triggered an assertion error from `stdout.isatty()` when trying  to open it using python's subprocess. I read that it's related to checking whether sys.stdout is attached to terminal or not, and was curious as to why that assertion exists for radian? 

In case it's relevant, here's the line of code:

`subprocess.Popen(cmd_app, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`

And part of the error.

```
...
...
lineedit/deps/prompt_toolkit/output/vt100.py", line 409, 
in from_pty\n    assert stdout.isatty()\nAssertionError\n'
```

**Comment by randy3k** [comment]
It is for sure an issue of `prompt_toolkit`, a backend used by radian. I believe we need to hack into the `isatty()` function to work around this.

**Comment by gfleetwood** [comment]
Right. Can't believe I missed that. Thanks.

**Comment by randy3k** [comment]
Let's keep it open.
