### ISSUE TITLE
vscode & RStudio

### ISSUE THREAD

**Issue by JohnCoene** [randy3k/radian#104]
I cannot figure out how to use it with vscode and RStudio, the latter seems possible.

**Comment by chrisoswald** [comment]
Under Linux you can install radian with python pip and start it in a terminal window of vscode. There are some R extensions which can help you (sending code to terminal, autocomplete, syntax highlighting ...).
With Rstudio I cannot see a possibility to replace the build in console with radian.

Christian

**Comment by MjolnirT** [comment]
But can it be used as an interpreter in VScode in the windows platform?

**Comment by randy3k** [comment]
radian is cross platform application. It should be working in viscose. Though my experience with vscode is limited.

**Comment by agutieda** [comment]
In case anyone wants to try this in Windows, you can use Radian as your default R terminal in VSCode by adding the following options in your  settings file:
```
"r.rterm.windows": "C:\\Windows\\System32\\cmd.exe",
"r.rterm.option": [ "/k radian"],    
```
This assumes you have installed the vscode-r extension already.

**Comment by randy3k** [comment]
@agutieda i do believe that we could invoke radian directly though

**Comment by ChristopheRoyer21** [comment]
Radian used to work with VS Code normally with:

`
"r.rterm.windows": "C:\\Windows\\Anaconda3\\radian.exe",
`
Since a week or two however, it stopped working this way. I'm trying any other way and can't find anything that works now. Even this doesn't work unfortunately.

> In case anyone wants to try this in Windows, you can use Radian as your default R terminal in VSCode by adding the following options in your settings file:
> 
> ```
> "r.rterm.windows": "C:\\Windows\\System32\\cmd.exe",
> "r.rterm.option": [ "/k radian"],    
> ```
> 
> This assumes you have installed the vscode-r extension already.

**Comment by randy3k** [comment]
@ChristopheRoyer21 could you be more specific? what error did you see?

**Comment by ChristopheRoyer21** [comment]
![image](https://user-images.githubusercontent.com/34045208/79643313-663fd100-8170-11ea-8943-7c8f03863372.png)

It only seems it cannot find my R path even though I know it is duely set. Sorry for the long wait, I didn't have a lot of time lately

**Comment by ChristopheRoyer21** [comment]
![image](https://user-images.githubusercontent.com/34045208/79643424-e23a1900-8170-11ea-8ba6-00e1d7a96f58.png)

It seems it simply doesn't find my path to R even though I know it's duely set. 
I usually use git bash as my terminal so it tried something similar:

```
"r.rterm.windows: "C:\\Program Files\\Git\\git-bash.exe",
"r.rterm.option": [ "/k radian"],
``` 
However, it simply opens an external terminal then closing git with this error message VS Code:
```
The terminal process terminated with exit code: 3221225477
```

**Comment by randy3k** [comment]
This is not a correct way to invoke bash shell on windows. 
```
"r.rterm.windows: "C:\\Program Files\\Git\\git-bash.exe",
"r.rterm.option": [ "/k radian"]
```

Use this instead,
```
"r.rterm.windows": "C:\\Windows\\Anaconda3\\radian.exe"
```

When happen if you run `radian --version` in the integrated terminal?

**Comment by ChristopheRoyer21** [comment]
As I said in my first message in the issue, I used to have the exact settings you just showed. However, it is not working anymore. I just tried to adapt the suggestion given to use it through cmd.exe. 
I have radian version 0.4.8, with r version 3.6.3







Sent from my Bell Samsung device over Canada's largest network.







-------- Original message --------

**Comment by randy3k** [comment]
As the error suggests, the path to R cannot be determined. You need to expose it via the PATH variable.

**Comment by ChristopheRoyer21** [comment]
Of course, but as I said, I know the R path is duely set in my environment variable. It works everywherr else than vscode. Even in an external terminal, r and radian both work normally. 







Sent from my Bell Samsung device over Canada's largest network.







-------- Original message --------

**Comment by randy3k** [comment]
Normally `radian` would try to guess the PATH to R via windows registry. Perhaps something is wrong in your registry.

**Comment by randy3k** [comment]
Wait, my last assertion may be incorrect if you say radian could find R in an external terminal. I don't have any idea then.

**Comment by ChristopheRoyer21** [comment]
Actually, I know my terminal cannot find correctly my R PATH in my environment variables. I fixed the problem by adding: 
'''
export PATH=$PATH'\...PATH TO R BIN... \
'''
In other word, I add it automatically every time I open the terminal. That might a reason why VS Code cannot find it and open radian. Is there a way to do something similar on VS Code? 







Sent from my Bell Samsung device over Canada's largest network.







-------- Original message --------

**Comment by randy3k** [comment]
Check this: https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by ChristopheRoyer21** [comment]
As I said twice earlier, I know that the R PATH is duely set in my environment variables. ​However, I don't know why, but it seems to not recognized it. It works for every other paths I entered there. 



De : Randy Lai <notifications@github.com>
Envoyé : 18 avril 2020 17:38
À : randy3k/radian
Cc : Christophe Royer; Mention
Objet : Re: [randy3k/radian] vscode & RStudio (#104)
 

[Externe UL*]


Check this: 
https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.


*ATTENTION : L’émetteur de ce courriel est externe à l’Université Laval.

Évitez de cliquer sur un hyperlien, d’ouvrir une pièce jointe ou de transmettre des informations si vous ne connaissez pas l’expéditeur du courriel. En cas de doute, contactez l’équipe de soutien informatique de votre unité ou hameconnage@ulaval.ca.
