### ISSUE TITLE
radian windows shared libraries

### ISSUE THREAD

**Issue by chrisoswald** [randy3k/radian#105]
I have problems to get radian running on windows. I get always the errror 

> RuntimeError: Cannot locate R share library.

and I have looked for it but I cannot found these shared libraries. How can I get them under Windows?

Thanks
Christian

**Comment by randy3k** [comment]
You could put the path to R binary in the PATH environmental variable.

**Comment by chrisoswald** [comment]
That was  done on my machine:

`... C:\Program Files\R\R-3.5.2\bin\x64 ... ;C:\Program Files\R\R-3.5.2; ...`

but it changes nothing. 

`pip install -U radian`

runs without errors but execute `radian` after it  brings

`Traceback (most recent call last):
  File "C:\Users\Christian Oswald\AppData\Local\Programs\Python\Python36-32\Scripts\radian-script.py", line 11, in <module>
    load_entry_point('radian==0.4.0', 'console_scripts', 'radian')()
  File "c:\users\christian oswald\appdata\local\programs\python\python36-32\lib\site-packages\radian\__init__.py", line 75, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "c:\users\christian oswald\appdata\local\programs\python\python36-32\lib\site-packages\radian\radianapp.py", line 82, in run
    rchitect.init(args=args)
  File "c:\users\christian oswald\appdata\local\programs\python\python36-32\lib\site-packages\rchitect\setup.py", line 25, in init
    if not lib._libR_load(libRpath(rhome).encode("utf-8")):
  File "c:\users\christian oswald\appdata\local\programs\python\python36-32\lib\site-packages\rchitect\utils.py", line 51, in libRpath
    raise RuntimeError("Cannot locate R share library.")
RuntimeError: Cannot locate R share library.`

Any other idea?
Thanks

**Comment by randy3k** [comment]
Maybe trying to reinstall R? It usually would correct the registry entries which give clues to radian.

**Comment by chrisoswald** [comment]
Useless, I have tried everything. Complete reinstall of R, older version ... Reinstall python ... Everytime cannot locate R share library.

**Comment by randy3k** [comment]
Does the file `C:\Program Files\R\R-3.5.2\bin\x64\R.dll` exist (assuming you have installed R 3.5.2)?

**Comment by chrisoswald** [comment]
Yes, it exists in all R Installation. (I have installed R-3.5.2, R-3.6.0, R-3.6.1)

**Comment by randy3k** [comment]
What does `radian —version` day?

**Comment by chrisoswald** [comment]
I have tried installing another python on windows but I get the same result.

`radian version: 0.4.0
r executable: C:\Program Files\R\R-3.6.0\bin\x64\bin\R
r version: 1000.0.0
python executable: c:\miniconda\python.exe
python version: 3.7.3`

Thanks, Christian

**Comment by randy3k** [comment]
It seems that there is an issue of R, radian failed to determine the version of R in your computer.

**Comment by chrisoswald** [comment]
I have reinstalled R again, all is running good - but no radian ...

**Comment by randy3k** [comment]
how about `C:\Program Files\R\R-3.6.0\bin\x64\bin\R --version`?

**Comment by chrisoswald** [comment]
(base) C:\Program Files\R\R-3.6.1\bin>R --version
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by randy3k** [comment]
It looks correct.
Btw, `radian --version` was showing your R is 3.6.0?

**Comment by chrisoswald** [comment]
Thats right, radian --version get also the wrong path. I have changed R_HOME and now it shows
`radian version: 0.4.0
r executable: C:\Program Files\R\R-3.6.1\bin\x64\bin\R
r version: 1000.0.0
python executable: c:\miniconda\python.exe
python version: 3.7.3`

But `radian` gets
`(base) C:\Users\Christian Oswald>radian
Traceback (most recent call last):
  File "c:\miniconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda\Scripts\radian.exe\__main__.py", line 9, in <module>
  File "c:\miniconda\lib\site-packages\radian\__init__.py", line 75, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "c:\miniconda\lib\site-packages\radian\radianapp.py", line 82, in run
    rchitect.init(args=args)
  File "c:\miniconda\lib\site-packages\rchitect\setup.py", line 25, in init
    if not lib._libR_load(libRpath(rhome).encode("utf-8")):
  File "c:\miniconda\lib\site-packages\rchitect\utils.py", line 51, in libRpath
    raise RuntimeError("Cannot locate R share library.")
RuntimeError: Cannot locate R share library.`


>

**Comment by randy3k** [comment]
radian is able to locate the binary but not to determine the version and R share library. I hate to repeat myself, but 

1. does `C:\Program Files\R\R-3.6.1\bin\x64\bin\R` exist?
2. how about running `C:\Program Files\R\R-3.6.1\bin\x64\bin\R --version`
3. how about `C:\Program Files\R\R-3.6.1\bin\x64\bin\R.dll`? exist?

If they exist, I cannot see why it doesn't work.

**Comment by chrisoswald** [comment]
all three points are o.k. 
R_HOME is correct,
R is running without problems

A nice problem ...

But nevertheless thanks for your help.
Christian

**Comment by diandian11** [comment]
do you have methord to address this issuse ?
![image](https://user-images.githubusercontent.com/31070013/71556866-999f0880-2a78-11ea-9067-e8994d39a4c6.png)

**Comment by renkun-ken** [comment]
@randy3k, from @diandian11's attached image, `python36-32` means python3.6 32-bit, but R-3.5.1 lies in `C:\Program Files` which is for 64-bit programs. Is it possible that a 32-bit python could load 64-bit shared library?

**Comment by randy3k** [comment]
@renkun-ken you have nailed the cause of the issue. Users are expected to have a 32bit R installed in the case of 32bit python. I think I should provide better error message in this case.

**Comment by randy3k** [comment]
It seems that @chrisoswald had the same issue.

**Comment by XuRuihan** [comment]
Did you try opening cmd with **admin user**? I ran into the same problem with general user, but it works with admin.

**Comment by pinusm** [comment]
I'm also facing the "Cannot locate R share library" issue. 

However, on my machine, the R path is:
C:\Program Files\R\R-3.6.3\bin\x64\R
not:
C:\Program Files\R\R-3.6.3\bin\x64\bin\R

nevertheless, `radian --version` gives me:
```
radian version: 0.4.9
r executable: C:\Program Files\R\R-3.6.3\bin\x64\bin\R
r version: 1000.0.0
python executable: C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\python.exe
python version: 3.8.2
```

For completeness, here's `C:\Program Files\R\R-3.6.3\bin\x64\R --version`:
```
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

I'll try installing x64 python and report, but I think there's another issue in my case (perhaps completely unrelated)

**Comment by randy3k** [comment]
Try upgrading radian to the most recent version? It should be more robust in detecting R.

**Comment by randy3k** [comment]
By the way, `C:\Program Files\R\R-3.6.3\bin\x64` is a wrong value for R_HOME, you might need to fix it.

**Comment by pinusm** [comment]
Thanks for looking into this!

I've update radian to 0.5.3, and also set R_HOME manually with `set R_HOME=C:\Program Files\R\R-3.6.3\`.
Now `radian --version` gives me:
```
radian version: 0.5.3
r executable: C:\Program Files\R\R-3.6.3\bin\R
r version: 3.6.3
python executable: c:\users\myusername\appdata\local\programs\python\python38\python.exe
python version: 3.8.2
```
which is better - It detected my R version correctly!

However, running `radian` gives me another error:
```
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38\Scripts\radian-script.py", line 11, in <module>
    load_entry_point('radian==0.5.3', 'console_scripts', 'radian')()
  File "c:\users\myusername\appdata\local\programs\python\python38\lib\site-packages\radian\__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "c:\users\myusername\appdata\local\programs\python\python38\lib\site-packages\radian\radianapp.py", line 89, in run
    rchitect.init(args=args)
  File "c:\users\myusername\appdata\local\programs\python\python38\lib\site-packages\rchitect\setup.py", line 42, in init
    raise Exception(load_r_symbol_error())
Exception: Cannot load symbol GA_peekevent: The specified procedure could not be found.
```

**Comment by randy3k** [comment]
Hi pinusum, could you open python and run the following? Just want to know if it works

```py
import rchitect
from ctypes import WinDLL
rchitect.utils.ensure_path()
p = rchitect.utils.libRgapath(rchitect.utils.Rhome())
lib = CDLL(p)
lib.GA_peekevent()
```

**Comment by pinusm** [comment]
Sure!
This runs fine (no output):
```python
import rchitect
from ctypes import CDLL
rchitect.utils.ensure_path()
```

but then `p = rchitect.utils.libRgapath(rchitect.utils.Rhome())` gives:
```
>>> p = rchitect.utils.libRgapath(rchitect.utils.Rhome())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38\lib\site-packages\rchitect\utils.py", line 91, in libRgapath
    raise RuntimeError("Cannot locate R share library.")
RuntimeError: Cannot locate R share library.
```

**Comment by randy3k** [comment]
What is your `p`?

My `p` is `'C:\\Program Files\\R\\R-3.6.3\\bin\\x64\\Rgraphapp.dll'`

Could you peek where `Rgraphapp.dll` is in your system?

**Comment by pinusm** [comment]
```
>>> p
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'p' is not defined
```

I've got one Rgraphapp.dll in `C:\Program Files\R\R-3.6.3\bin\x64`, and
another in `C:\Program Files\R\R-3.6.3\bin\i386`.
(and also, but probably not related, under `C:\Program
Files\JASP\R\bin\x64\Rgraphapp.dll` and `C:\Program Files\jamovi
1.2.16.0\Frameworks\R\bin\x64\Rgraphapp.dll`. Both JASP and jamovi use
their own version of R, so that's probably the reason for these extra dlls)

**Comment by randy3k** [comment]
Sorry, I meant `rchitect.utils.Rhome()`.

```
In [2]: rchitect.utils.Rhome()
Out[2]: 'C:\\Program Files\\R\\R-3.6.3\\'
```

**Comment by pinusm** [comment]
```
>>> rchitect.utils.Rhome()
'C:\\Program Files\\R\\R-3.6.3\\bin\\x64'
```

**Comment by randy3k** [comment]
Again, for the same reason, your `R_HOME` was not set correctly. Could you fix it and rerun

```
import rchitect
from ctypes import CDLL
rchitect.utils.ensure_path()
p = rchitect.utils.libRgapath(rchitect.utils.Rhome())
lib = CDLL(p)
lib.GA_peekevent()
```

**Comment by randy3k** [comment]
Or just hotfix it for now
```py
import rchitect
from ctypes import CDLL
rchitect.utils.ensure_path()
p = rchitect.utils.libRgapath('C:\\Program Files\\R\\R-3.6.3\\')
lib = CDLL(p)
lib.GA_peekevent()
```

**Comment by pinusm** [comment]
so here's another go..

```
C:\Users\myusername>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rchitect
>>> from ctypes import CDLL
>>> rchitect.utils.ensure_path('C:\\Program Files\\R\\R-3.6.3\\')
>>> p = rchitect.utils.libRgapath('C:\\Program Files\\R\\R-3.6.3\\')
>>> lib = CDLL(p)
>>> lib.GA_peekevent()
0
```
That's the expected result.

I've set R_HOME before with `set R_HOME`, but I guess that isn't persistent. I've now changed it from the dialog menu to be `C:\Program Files\R\R-3.6.3\`.

then:
```
>>> import rchitect
>>> from ctypes import CDLL
>>> rhome = rchitect.utils.Rhome()
>>> rchitect.utils.ensure_path(rhome)
>>> p = rchitect.utils.libRgapath(rhome)
>>> lib = CDLL(p)
>>> lib.GA_peekevent()
0
```
That's also the expected result.

However, just quitting the python console and running `radian` still doesn't work..
![2020-04-23 10_21_53-Window](https://user-images.githubusercontent.com/10765331/80070942-7e3a9a80-854c-11ea-83ae-e6b0cf2af300.png)

so next I've verified again my R_HOME value, and it seems OK.
```
C:\Users\myusername>echo %R_HOME%
C:\Program Files\R\R-3.6.3\
```

**Comment by randy3k** [comment]
Thanks, I know what's wrong but I don't know why it's wrong. What Windows OS do you have?

**Comment by pinusm** [comment]
Windows 10 Build 18363

**Comment by randy3k** [comment]
Oh, I could reproduce it with python 3.8. But it works with python 3.7 previously.

**Comment by pinusm** [comment]
I replaced 3.8 with 3.7 and it works!
Let me know if you'd like me to try anything else...
Thanks for your help with this!

**Comment by randy3k** [comment]
Thank you for bringing it up, I guess I will need to pry into python 3.8 tomorrow to see what's wrong there. Have to sleep now.

**Comment by randy3k** [comment]
Oh, I found the culprit https://github.com/randy3k/rchitect/commit/227bec42e5606d4dd06fe670c6b6ef24006bb09b

I guess python 3.8 may be a bit less error tolerant :) Will release a fix tomorrow.

**Comment by ramosgislaine** [comment]
Guys, I also can't install radian and it seems that I'm getting a duplicated bin/ folder in my path:

```
(base) C:\Users\700105212>radian --version
radian version: 0.5.12
r executable: C:\Users\700105212\Programas\R-4.1.1\bin\bin\R
r version: 1000.0.0
python executable: c:\users\700105212\programas\anaconda\python.exe
python version: 3.8.8

(base) C:\Users\700105212>echo %R_HOME%
C:\Users\700105212\Programas\R-4.1.1\bin
```
but I've checked every variable and it's alright. Any ideias?
