### ISSUE TITLE
Colorize condition messages output to stderr

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#109]
In RStudio, the condition signals (`message`, `warning`, and `stop`) to `stderr` are colorized so that it is easy to distinguish exceptional messages from `stdout`. I'm wondering if it is possible for `radian` to also colorize `stderr` output to serve the same purpose?

RStudio console:
![image](https://user-images.githubusercontent.com/4662568/64753559-3e431c00-d556-11e9-96d5-83cc6883c48b.png)

radian:
![image](https://user-images.githubusercontent.com/4662568/64753581-4e5afb80-d556-11e9-9541-fa813d5e9bcf.png)

**Comment by randy3k** [comment]
It is totally possible and it makes sense.

**Comment by randy3k** [comment]
<img width="386" alt="Screen Shot 2019-09-11 at 9 57 47 PM" src="https://user-images.githubusercontent.com/1690993/64755204-35633380-d4df-11e9-8732-f3460ee5877e.png">
c2dfad6 closes it.

**Comment by renkun-ken** [comment]
I installed the latest dev with `pip install --user git+https://github.com/randy3k/radian` but it does not work yet. Am I missing something?

**Comment by randy3k** [comment]
It's working on my macOS (though the code is not working on windows, I'll push a fix soon).

I don't get what you meant. The settings is `radian.stderr_format` and the default color is red.

**Comment by randy3k** [comment]
It should now also work in Windows.

**Comment by renkun-ken** [comment]
I'm using Ubuntu 19.04 and I uninstalled radian and reinstalled radian but it does not seem to work for me.

I also clone the repo and `pip install --user .`, the same.

**Comment by renkun-ken** [comment]
Sorry for the confusion, I mean the `stderr_format` in `README.md`.

**Comment by randy3k** [comment]
That was a typo in README...thank you for catching it. 
It also doesn't work on my Ubuntu VM. Let me work on it.
