### ISSUE TITLE
radian.auto_indentation add too much indentation to code sent from vscode

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#111]
I'm using latest radian, vscode, and vscode-R.
I enabled `r.bracketedPaste` for vscode-R as suggested at https://github.com/randy3k/radian/issues/99.

However, if I enable `radian.auto_indentation`, the identation of the code sent to vscode is messed up like the following (see https://github.com/Ikuyadeu/vscode-R/issues/117):

![image](https://user-images.githubusercontent.com/4662568/64832300-f7aff900-d60b-11e9-86c1-cd4f5935b4c9.png)

If I turn off `radian.auto_indentation`, the code sent to radian looks normal.

**Comment by nlneas1** [comment]
It may be [important to know](https://github.com/Ikuyadeu/vscode-R/issues/117#issuecomment-531076921) what OS you are using

**Comment by renkun-ken** [comment]
I notice that I didn't use `r.runSelectionInActiveTerm` action but vscode built-in send-code action. I bind `Cmd+Enter` to `r.runSelectionInActiveTerm` and the bracketed paste works.

**Comment by randy3k** [comment]
Err....I know nothing about VCcode. But it’s good that you have figured it out and future readers would know how to fix it.
