### ISSUE TITLE
Ctrl+C does not interrupt function call

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#115]
In R terminal, Ctrl+C is effective to stop the currently running execution. However, pressing Ctrl+C does not seem to work in radian:

One is a simple `Sys.sleep()` call.

```r
Sys.sleep(10)
```

The other is long-running execution loop:

```r
sum <- 0L
for (i in 1:1000000000) sum <- sum + 1L
```

Both can be immediately interrupted by user in R terminal.

It seems that radian does not send user interruption signals to R.

**Comment by randy3k** [comment]
It's working on my macOS, both iTerm and Sublime Terminus.
What OS and program are you using?

**Comment by renkun-ken** [comment]
Surprisingly, the only case it does not work is where I press Ctrl+C in radian in tmux on remote server in vscode terminal. And I exit tmux session and restart a new one and the problem is gone.

**Comment by Whale-fall** [comment]
The same case，can not interrupt in vscode terminal.

**Comment by EvoLandEco** [comment]
I tried twice, the first time Ctrl + C worked, but the second time not, it seems that Ctrl + C is not always working

**Comment by randy3k** [comment]
Note that Ctrl + C only sends a signal to R and asks it to interrupt. The outs come will ultimately depend on what loop R is running. The signal will be ignored when R is executing a heavy C/C++ code unless the C code checks the signal regularly.

**Comment by EvoLandEco** [comment]
> Note that Ctrl + C only sends a signal to R and asks it to interrupt. The outs come will ultimately depend on what loop R is running. The signal will be ignored when R is executing a heavy C/C++ code unless the C code checks the signal regularly.

Thanks for the reply, but in this case do we have other way to interrupt radian? Is Ctrl + C equal to the interrupt R function that R studio offers?

**Comment by randy3k** [comment]
You could either wait until the c code completes or kill the whole program. This is the same mechanism in RStudio.
