### ISSUE TITLE
radian reads .Rprofile twice

### ISSUE THREAD

**Issue by olesendan** [randy3k/radian#122]
Hi.
When I starts radian, it seems to start R twice.
I can see in the console that radian prints my .First() from my .Rprofile twice, as if radian opens, closes and opens R again.

Does other experience this behaviour?
My setup is
arch linux, 
R 3.6.1
and and fresh radian install

Greetings from Denmark
Dan Olesen

**Comment by randy3k** [comment]
I suspect that your `.First` function was executed when we are determining some system information before stating the R session. Could you try the following?
```
R --slave -e "cat(paste(R.home('doc'), R.home('include'), R.home('share'), sep=':'))"
```

**Comment by randy3k** [comment]
In general, you might need to check if the current session in interactive.

```
.First <- function() {
	if (interactive()) {
		# do things
	}
}	
```

**Comment by olesendan** [comment]
Hi Randy.

I tried your suggestion, and it printed the output from the function. Is this expected?

I will try to put the if statement in my function.

**Comment by randy3k** [comment]
You should avoid printing anything from `.First` in an non-interactive R process. My recommendation is to check `interactive()`. It will also prevent you from any future issues.

**Comment by olesendan** [comment]
Hi Randy.

Thank you, for your suggestion. It works as expected.

**Comment by gwd666** [comment]
This started happening again in `radian 0.6.7`? I guess it's the .First function calling ... but it has an `if(interactive())` in place, and even when I remove the `.First` func it still occurs - so not sure what has changed.  When I remove the `.Rprofile` completely `radian` complains that there is no `.Rprofile` file available in `R_USER` directory. If I put an empty one there it will start up twice again. I noticed some `Locale` changes happening in the background that may be responsible for the startup firing twice -> dunno.
