### ISSUE TITLE
Different values for `LD_LIBRARY_PATH` in R vs. Radian?

### ISSUE THREAD

**Issue by khughitt** [randy3k/radian#125]
After a recent system update, rJava started raising the usual complaints. A call to `sudo R CMD javareconf` fixes the issue for the base R console, but not so far radian. After updating Radian, to be safe, I launched equivalent R/radian consoles from an identical environment.

(As aside, the first different I noticed was that radian was using different versions of BLAS/LAPACK. This turned out to be due to radian being installed in a conda environment that included those libraries -- deactivating the environment and reinstalling radian fixed this issue... It might be worth mentioning in the install docs.)

`.libPaths()` is the same, however, I checked the environmental variables defined in each and found that `LD_LIBRARY_PATH` differs between radian / R console, which is almost certainly the culprit:

```r
> r[r$r_console != r$radian, ]
# A tibble: 9 x 3
  name                  r_console                                        radian          
  <chr>                 <Dlist>                                          <chr>           
1 NA                    NA                                               NA              
2 NA                    NA                                               NA              
3 CONDA_PROMPT_MODIFIER (base)                                           (base)          
4 LD_LIBRARY_PATH       /usr/lib64/R/lib:/usr/lib/jvm/default/lib/server /usr/lib64/R/lib
5 NA                    NA                                               NA              
6 NA                    NA                                               NA              
7 NA                    NA                                               NA              
8 R_SESSION_TMPDIR      /tmp/RtmpiNyeZY                                  /tmp/RtmpMRiWzL 
9 WINDOWID              67108867                                         65011715        

```

Is there any possibility this behavior could be normalized between R/radian to avoid unexpected behavior like this?

**Radian version:**

```
radian version: 0.4.2
r executable: /usr/lib64/R/bin/R
r version: 3.6.1
python executable: /usr/bin/python
python version: 3.8.0
```

**Comment by randy3k** [comment]
R uses the `$R_HOME/etc/ldpaths` file to modify the variable `LD_LIBRARY_PATH`. radian doesn't read that file, however, it respects the environmental variable `R_LD_LIBRARY_PATH`.

The workaround, for now, is to utilize the `R_LD_LIBRARY_PATH` variable.
```
export R_LD_LIBRARY_PATH=/usr/lib/jvm/default/lib/server
# then run either R or radian
```

A possible solution is to run something like `R --slave -e "cat(Sys.getenv('LD_LIBRARY_PATH'))"` and append it to `LD_LIBRARY_PATH`, but I am not sure having this additional overhead...

**Comment by randy3k** [comment]
I found a faster solution which just involves the `ldpaths` file.
```
bash -c '. $(R RHOME)/etc/ldpaths; echo $LD_LIBRARY_PATH'
```
Perhaps I could also force radian to read that file too.

**Comment by khughitt** [comment]
Hey @randy3k - thanks for the quick reply and work-around!

That looks quite fast! Was speed the main motivation for not using `$RHOME/etc/ldpaths` previously?

It seems to me, the more you can make radian *just work* as a drop-in R console replacement, the better the user experience will be.

If you ever need help testing in Linux (Arch), just let me know!

**Comment by randy3k** [comment]
Speed was the major but not the only factor. The other factor was that these behaviours are not actually documented by R developers. Though they are unlikely to change in the foreseeable future, I simply didn't want to take the risk of breaking things.

**Comment by randy3k** [comment]
Hope #126 will resolve the issue.

```
pip3 install -U git+https://github.com/randy3k/radian@ldpaths 
```
