### ISSUE TITLE
How to use radian in a vim buffer?

### ISSUE THREAD

**Issue by fountainer** [randy3k/radian#127]
I can use `radian` in an external terminal for the `Nvim-R` plugin when I set the following `let R_in_buffer = 0` and `let R_app = "radian"`. I want to run R in vim built-in terminal. However, this will open the traditional R console. How can I open the `radian` console in the vim build-in terminal when I start R with `<LocalLeader>\rf`?

**Comment by randy3k** [comment]
https://github.com/randy3k/radian/blob/master/README.md#nvim-r-support

**Comment by fountainer** [comment]
I forgot to delete the line `let R_in_buffer = 0`. Now I can use `radian` in a vim buffer.
