### ISSUE TITLE
edit files in new window

### ISSUE THREAD

**Issue by olesendan** [randy3k/radian#129]
Hi.

I'm trying to figure out, if I can setup radian to open files in a new window.

I'm on archlinux
i3wm
bash
Urxvt
R 3.6.xx
radian
neovim 8.x

My workflow
cd path/to/project/root
start radian
type usethis::edit_file("some_file.Rmd")

I would like radian to open this file in a new termial with neovim. Now it starts vim in the same terminal

When reading the docs, I can not find a setting for this behaviour

Greetings from Denmark
Dan Olesen

**Comment by randy3k** [comment]
This is unfortunately out of scope of radian, even out of the scope of R. To do so, it’s highly dependent on your setup, I couldn’t offer much help without any details.

**Comment by olesendan** [comment]
Hi Randy.

Thank you, for your reply. Then I will not explore this any further.

/Dan
