### ISSUE TITLE
Is there a way for radian to inherit the colour scheme of my terminal?

### ISSUE THREAD

**Issue by HarrisonWilde** [randy3k/radian#130]
Trying to figure this out, is the only way for me to somehow define a custom pygments theme?

**Comment by randy3k** [comment]
You may be able to do it by changing the color depth. However the setting is not exposed and you’ll need to edit the source code.

**Comment by HarrisonWilde** [comment]
Any pointers for where I can go about changing the colour depth? Will try to write a little utility to give users an option once I figure it out.

**Comment by randy3k** [comment]
https://github.com/randy3k/radian/blob/master/radian/session.py#L126

You will need to read the docs of prompt_toolkit for the options.

**Comment by HarrisonWilde** [comment]
After doing some reading it seems far easier to just create a custom `pygments` style so will close this for now
