### ISSUE TITLE
radian in N-vimr with vim bindings

### ISSUE THREAD

**Issue by olesendan** [randy3k/radian#131]
Hi.
I'm trying to use radian in my n-vimr setup.

It seems to my, that if I have "vi" bindings set in radian, the first couple of letters gets cut of, when I send code from nvim to radian.

init.vim
let R_app = 'radian'
let R_cmd = 'R'

radian_profile
options(radian.editing_mode = "vi")

If I comment out the vi binding in radian it works as expected.

Am I doing something wrong?

Greetings from Denmark
Dan Olesen

**Comment by randy3k** [comment]
Try turning on the bracketed paste mode. Check the FAQ.

**Comment by olesendan** [comment]
Hi Randy.
Thank you. The bracketed paste mode did it.

/Dan
