### ISSUE TITLE
CTRL-LEFT / RIGHT does not skip words

### ISSUE THREAD

**Issue by Peder2911** [randy3k/radian#132]
Hey!

Really impressed with this, it's a lot of fun to use, and super useful.
I would like to "move around" the prompt in the same way that i do with the regular R prompt, though. When holding CTRL and pressing left / right, the "regular" cursor skips words, while in radian, it doesn't do anything. This also applies to CTRL-A moving the cursor to the beginning of the line.

**Comment by randy3k** [comment]
I am surprised that `ctrl+a` does not send the cursor to the beginning of the line. In order to move between words, it depends on the terminal emulator that you are using. For example, most terminals support `alt+left/right`.

**Comment by Peder2911** [comment]
Hey Randy! Thank you for your prompt reply.
I am using bash. Also, i have alt+left/right bound to something else (using i3 wm), so i can't really confirm if that works.

Also surprised. Especially weird that the only c-* that works is deleting the last word with c-w.

I also tried with xterm, same issue. Could it be i3?

**Comment by randy3k** [comment]
That I cannot be sure. `radian` uses `prompt-toolkit` under the hood and it looks like it has already handled the keys [well](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/bd5c368e106d8e3d15244206a92959acb2f70592/prompt_toolkit/key_binding/bindings/emacs.py#L63-L64).

**Comment by Peder2911** [comment]
Ah, interesting. I was trying to pile through `prompt_toolkit`s code yesterday to figure out if it was handled by the framework, or if it was something that had to be implemented by you.

I should find something else made with ptk to figure out if that's the issue. Any tips?
P

**Comment by randy3k** [comment]
By the way, prompt-toolkit recognize [these](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/bd5c368e106d8e3d15244206a92959acb2f70592/prompt_toolkit/input/ansi_escape_sequences.py#L120-L121) sequences as `ctrl+left/right`. Would you confirm if your terminal emits the same sequences? (Press `ctrl+v, ctrl+left` to display the sequence.)

**Comment by Peder2911** [comment]
It emits:
`c-left` = `^[[1;5D`
`c-right` = `^[[1;5C`

**Comment by randy3k** [comment]
So they are correct..

**Comment by Peder2911** [comment]
[ptpython](https://github.com/prompt-toolkit/ptpython/) responds correctly to `c-left` / `c-right` / `c-a` / `c-e`, so i don't think the issue is with my emulator or prompt-toolkit.

**Comment by randy3k** [comment]
What version of `ptpython` do you have?

**Comment by Peder2911** [comment]
2.0.6

**Comment by randy3k** [comment]
I just tried iTerm on macOS and `ctrl+left/right` are working correctly. But it requires to turn off the system keybindings of Mission Control.

<img width="630" alt="Screen Shot 2019-12-11 at 1 15 22 AM" src="https://user-images.githubusercontent.com/1690993/70607664-b94abb80-1bb3-11ea-9fe0-a6e7b1f2adaf.png">

**Comment by randy3k** [comment]
Did you somehow turn on the 'vi' mode of radian?

**Comment by Peder2911** [comment]
Oh lord, that's it! So sorry about wasting your time on this. :smile: 
Thank you for excellent help.
P
