### ISSUE TITLE
How to change the r executable?

### ISSUE THREAD

**Issue by EularTang** [randy3k/radian#133]
Hi,

I recieved the Traceback as following when I run 'radian':
```
Traceback (most recent call last):
  File "/usr/software/anaconda3/bin/radian", line 10, in <module>
    sys.exit(main())
  File "/usr/software/anaconda3/lib/python3.6/site-packages/radian/__init__.py", line 76, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/usr/software/anaconda3/lib/python3.6/site-packages/radian/radianapp.py", line 83, in run
    rchitect.init(args=args)
  File "/usr/software/anaconda3/lib/python3.6/site-packages/rchitect/setup.py", line 27, in init
    if not lib._libR_load(libRpath(rhome).encode("utf-8")):
  File "/usr/software/anaconda3/lib/python3.6/site-packages/rchitect/utils.py", line 51, in libRpath
    raise RuntimeError("Cannot locate R share library.")
RuntimeError: Cannot locate R share library.
```
So, I countinued to input 「radian --version」,the result showed:  
`r executable: /usr/local/bin/R/bin/R`
But my R is in '/usr/local/bin/R'.How can I  change the r executable?
Thanks for your attention！

Tang

**Comment by randy3k** [comment]
Did you somehow define `R_HOME`? What is the result of `which R`?

**Comment by EularTang** [comment]
I runned the 'export R_HOME=/usr/local/bin/R' in the shell and put the code following in the .bashrc, but it didn't work.
```
export R_HOME=/usr/local/bin/R
alias r="radian"
```

**Comment by randy3k** [comment]
`R_HOME` is **not** the path to R. Run `R RHOME` to find it.

**Comment by randy3k** [comment]
By the way, `radian` actually was able to find the R binary, it just failed to locate the R shared library `libR.so`. I suspect that the R in your system was not compiled with the flag `--enable-R-shlib`. Try install a version of R with the shared library.

**Comment by EularTang** [comment]
> By the way, `radian` actually was able to find the R binary, it just failed to locate the R shared library `libR.so`. I suspect that the R in your system was not compiled with the flag `--enable-R-shlib`. Try install a version of R with the shared library.

Is **reinstalling** the R the only way to make it compiled with the flag `--enable-R-shlib`?

**Comment by randy3k** [comment]
You don't have to remove the existing R, you only have to install a version that has the shared library. It could be done in multiple ways,

1. compile it from source with the flag --enable-R-shlib
1. assume that you are using ubuntu, from apt-get
1. or from linuxbrew https://docs.brew.sh/Homebrew-on-Linux

How did you install your current R?

**Comment by EularTang** [comment]
> You don't have to remove the existing R, you only have to install a version that has the shared library. It could be done in multiple ways,
> 
> 1. compile it from source with the flag --enable-R-shlib
> 2. assume that you are using ubuntu, from apt-get
> 3. or from linuxbrew https://docs.brew.sh/Homebrew-on-Linux
> 
> How did you install your current R?
> 
> Update: I saw that it is `anaconda3`.

Hi,

I installed R in Way 1.
Your judgment is accurate and I have solved the problems by ` ./configure --enable-R-shlib`.
Thank you very much!

Tang
