### ISSUE TITLE
Empty rows below the command line

### ISSUE THREAD

**Issue by intiben** [randy3k/radian#135]
First of all thanks for developping radian I just started using it and it's promising. However coming from Rstudio I noticed that there is constantly at least 7 empty rows below the command entry line:
<img width="653" alt="Screen Shot 2020-01-15 at 15 45 26" src="https://user-images.githubusercontent.com/56064362/72443393-78dfee00-37ae-11ea-9c9c-f52db0567131.png">

In my opinion this make is impractical to use radian for consoles that are only a few rows high (e.g. script on top and console at the bottom), for example in the example above I would have liked to see 7 more rows of `mtcars` rather than having the padding at the bottom.

This may be related to #17 where it was stated that the empty space is for auto completion? In this case wouldn't it be possible to remove the empty rows but to have the autocompletion above the command line when there is no room below as in Rstudio?
![Screen Shot 2020-01-15 at 15 51 26](https://user-images.githubusercontent.com/56064362/72443657-ed1a9180-37ae-11ea-8264-147a12d34916.png)

**Comment by randy3k** [comment]
We are using prompt-toolkit to display the prompt. Unfortunately there is no immediate option to display the menu above the cursor. One possibility is to write an full screen app out of it, but it will be like a complete rewrite of radian. If you really want to get rid if the extra spaces, you could turn off `radian.complete_while_typing`

**Comment by intiben** [comment]
@randy3k prefect this does the trick for me 😄, thanks a lot for your help.

**Comment by krlmlr** [comment]
Is there an upstream issue for displaying the menu above the cursor? Should we file one?

Setting the `radian.complete_while_typing` option to `FALSE` helps turn off scrolling/padding, but the scrolling after tab completion is still a minor annoyance.

**Comment by randy3k** [comment]
I am sure that I have seen threads upstream related to this matter. Though I can't recall any specific threads now.
