### ISSUE TITLE
[FR] specify r.exe path

### ISSUE THREAD

**Issue by StevenLi-DS** [randy3k/radian#136]
After installing radian, everything runs fine but it seems like radian uses the R.exe installed by code at my path  `C:/Users/liqia/Anaconda3/lib/R/bin/x64/R`, but I'd like to use another exe in `C:\Program Files\R\R-3.6.1\bin\R.exe`. 

Please considering add a toggle to let user choose exe.

https://github.com/Ikuyadeu/vscode-R/issues/190#issuecomment-574992531

**Comment by randy3k** [comment]
You just need to add the path to your favourite R.exe to the beginning of the PATH variable.

**Comment by StevenLi-DS** [comment]
@randy3k I just tried to do that, but when I do `R.home("bin")` and it still gives me `"C:/Users/liqia/Anaconda3/lib/R/bin/x64"`.  Do you have a more detailed instruction. Maybe I'm missing something.
