### ISSUE TITLE
clang7 breaks radian?

### ISSUE THREAD

**Issue by intheravine** [randy3k/radian#137]
I've been using radian for many months but today installed clang7 and radian is no longer happy:

> ~% radian
> Traceback (most recent call last):
>   File "/usr/local/bin/radian", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/radian/__init__.py", line 88, in main
>     RadianApplication(r_home, ver=__version__).run(options)
>   File "/usr/local/lib/python3.7/site-packages/radian/radianapp.py", line 83, in run
>     rchitect.init(args=args)
>   File "/usr/local/lib/python3.7/site-packages/rchitect/setup.py", line 29, in init
>     system2utf8(ffi.string(lib._libR_dl_error_message()))))
> Exception: Cannot load R shared library. dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 10): Symbol not found: ___addtf3
>   Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libquadmath.0.dylib
>   Expected in: /usr/local/lib/libgcc_s.1.dylib
>  in /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libquadmath.0.dylib

> ~% radian --version
> radian version: 0.4.4
> r executable: /Library/Frameworks/R.framework/Resources/bin/R
> r version: 3.6.2
> python executable: /usr/local/opt/python/bin/python3.7
> python version: 3.7.6

I'm wondering if I must remove clang to use radian or if there's a work around.

**Comment by randy3k** [comment]
How did you install clang7 and what is the result of the following?
```bash
otool -L /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libquadmath.0.dylib
```
Normally, R should detect it's own libgcc `libgcc_s.1.dylib`.

```bash
(randyimac)-~$ otool -L /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libquadmath.0.dylib
/Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libquadmath.0.dylib:
	/Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by intheravine** [comment]
User error - I mistakenly installed an out-of-date gfortran version. I uninstalled and installed gfortran 6.1 - radian is happy again! Sorry for the bother.
