### ISSUE TITLE
vignette() not working

### ISSUE THREAD

**Issue by StevenLi-DS** [randy3k/radian#139]
radian-0.4.4

It seems like `vignette()` is not working, which will open a html if I use R with Jupyter Lab.
If I use it in radian, I got 
```
starting httpd help server ... done
```
but nothing show up

http://r-pkgs.had.co.nz/vignettes.html

**Comment by randy3k** [comment]
But it works in regular R?

**Comment by StevenLi-DS** [comment]
yes, a html will open after I run it.

**Comment by randy3k** [comment]
I again cannot reproduce the issue with radian 0.4.4 in Windows.

**Comment by StevenLi-DS** [comment]
Could you give me some code so that we can try at my end.

**Comment by randy3k** [comment]
I just tried `vignette("parallel")`

**Comment by StevenLi-DS** [comment]
@randy3k that works, but it open an pdf. Could you try `vignette("dplyr")`, which should open an html

**Comment by randy3k** [comment]
That also works for me.
<img width="731" alt="Screen Shot 2020-01-20 at 2 40 34 PM" src="https://user-images.githubusercontent.com/1690993/72762003-d8654180-3b92-11ea-8d0e-9c9d1cfd74c9.png">

**Comment by StevenLi-DS** [comment]
interesting...I got nothing but
![image](https://user-images.githubusercontent.com/33796896/72762079-4e29d700-3bac-11ea-9932-2a73f6c507ea.png)

**Comment by StevenLi-DS** [comment]
https://github.com/Ikuyadeu/vscode-R/issues/190#issuecomment-576460851
