### ISSUE TITLE
Add option for case insensitive search

### ISSUE THREAD

**Issue by strboul** [randy3k/radian#146]
I don't know whether it's currently possible to do case insensitve history search with <kbd>CTRL</kbd>+<kbd>r</kbd>. It'll be nice to add a new option to the radian settings such as `radian.case_insensitive_history_search`.

I'd be happy to help implementing this feature as well.

Thanks for the radian, it is awesome!

**Comment by randy3k** [comment]
It is an easy take. 
Install the dev version and have fun.

closed by e6bd2f8
