### ISSUE TITLE
radian throws error in VSCode: MacOS cannot get radian to run: "The terminal process terminated with exit code: 2"

### ISSUE THREAD

**Issue by atanasj** [randy3k/radian#149]
See [here](https://github.com/Ikuyadeu/vscode-R/issues/235)

In order for `radian` to work as expected, all `Rterm options` had to be removed form the `VSCode-R` extension (`--no-restore`, `--no-save`, `--no-site-file`).

See suggestion [here](https://github.com/Ikuyadeu/vscode-R/issues/235#issuecomment-588030150).

Is this fixable on the `radian` side?

**Comment by randy3k** [comment]
Yes, you are right that radian and R take different arguments. Maybe it’s a good idea to support the most of the common flags.

**Comment by randy3k** [comment]
close by 6cdd020

**Comment by atanasj** [comment]
This doesn't seem to have fixed the issue as I'm getting the same behaviour.... Anything else I need to do?

**Comment by randy3k** [comment]
Did you install the master branch?

**Comment by atanasj** [comment]
Right you are, sorry. Thanks for that.
