### ISSUE TITLE
Non-breaking spaces cause radian to break

### ISSUE THREAD

**Issue by intiben** [randy3k/radian#150]
For some unknown reasons, I had a non-breaking space (option + space on macOS) instead of a regular white space for the code indentation in my code, and that caused radian to return the following error:

```
From cffi callback <function cb_write_console_capturable at 0x7f05c8c90500>:
Traceback (most recent call last):
  File "/home/ben/.local/lib/python2.7/site-packages/rchitect/callbacks.py", line 182, in cb_write_console_capturable
    text = rconsole2str(ffi.string(buf))
  File "/home/ben/.local/lib/python2.7/site-packages/rchitect/utils.py", line 111, in rconsole2str
    ret += system2utf8(buf)
  File "/home/ben/.local/lib/python2.7/site-packages/rchitect/utils.py", line 163, in system2utf8
    return buf.decode("utf-8", "backslashreplace")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: don't know how to handle UnicodeDecodeError in error callback
```

While I agree that non-breaking spaces have nothing to do in R code, would it be possible to have a least a more informative error message from radian?

**Comment by randy3k** [comment]
I cannot reproduce it. How did you run the command?

**Comment by ghost** [comment]
I investigated this further and found that it was caused by an outdated version of python (2.7.12)

**Comment by randy3k** [comment]
I also cannot reproduce it with 2.7.13.

**Comment by ghost** [comment]
Here are the details of the install that does not work:
```
radian --version
radian version: 0.4.6
r executable: /opt/R/3.5.3/lib/R/bin/R
r version: 3.5.3
python executable: /usr/bin/python
python version: 2.7.12
```

As for the steps to reproduce the error:
1) Start radian from a terminal 
2) On macOS I type option + space (to add a non breaking space) followed by any R command e.g. `print("Hello")`

**Comment by randy3k** [comment]
I still cannot reproduce it...
macOS Catalina, R 3.6.3, python 2.7.13

```
r$>  print("hello")                                                             
[1] "hello"
```

**Comment by randy3k** [comment]
Ok, I found a way to reproduce it in python 2.7

```
cat("\xa0")
```

but
```
cat("\xc2\xa0")
```
works fine.

**Comment by ghost** [comment]
Yes works for me as well, `cat("\xa0")` crashes in my old setup but works in the new one and `cat("\xc2\xa0")` works in both cases.
