### ISSUE TITLE
Keybind to exit vim mode and prompt indication format

### ISSUE THREAD

**Issue by petobens** [randy3k/radian#153]
I would like to map `jj` to exit insert mode (i.e switch to navigation mode). Is this possible?

Also can we format the text that indicates the current vi mode? Currently in the config I have:
```R
options(radian.vi_mode_prompt = "\033[0;35m({})\033[0m")
```
and `insert` mode is shown as `(ins)`. I would like to replace it by `(I)`. 
Thanks in advance

**Comment by randy3k** [comment]
Unfortunately, both of these are not not officially supported.

**Comment by petobens** [comment]
Thanks for the quick reply. Any plans to add them? Also it would be really nice to be able to change the cursor shape conditional on the vim mode.

**Comment by petobens** [comment]
Also in general I'm not sure about the scope/extent of the key binding mechanism... For instance I realized that I would like to map `C-p` to go up in history (i.e as up arrow key) but this doesn't seem possible yet right?

**Comment by randy3k** [comment]
You are right. Custom key bindings are not possible.

All these bindings are actually from the python package promot-toolkit. It is not sure how we should expose these settings to R users.

**Comment by petobens** [comment]
Mmm for what it's worth and AFAICT ipython also uses prompt toolkit behind the scenes and it allows us to map keys like this: https://github.com/petobens/dotfiles/blob/e3515c53039686ca51de6c5ab10adcfb4a8a78c5/python/ipython_startup.py#L25-L39

**Comment by randy3k** [comment]
Exactly, we want to expose these interface to R users and it is not realistic to ask R users to write python code...

**Comment by petobens** [comment]
Ok. I thinks it's better to at least have this in python rather than not having this at all but I undestand your concern. Thanks

**Comment by randy3k** [comment]
I have just pushed `d3bd041` which allows user hook. 

Given that you have some experience of working with `prompt-toolkit`, try the following hook function.

```
options(radian.on_load_hooks = list(function() {
    getOption("rchitect.py_tools")$attach()

    radian <- import("radian")
    prompt_toolkit <- import("prompt_toolkit")

    KeyPress <- prompt_toolkit$key_binding$key_processor$KeyPress
    Keys <- prompt_toolkit$keys$Keys

    insert_mode <- radian$key_bindings$insert_mode
    app <- radian$get_app()
    kb <- app$session$modes$r$prompt_key_bindings

    kb$add("j", "j", filter = insert_mode)(function(event) {
        event$app$key_processor$feed(KeyPress(Keys$Escape))
    })
}))

```

**Comment by petobens** [comment]
Brilliant. Thanks. Can I call a prompt toolkit function directly? I want to replicate this binding:
```python
from prompt_toolkit.key_binding.bindings.named_commands import forward_word
r.add_binding(Keys.Escape, 'f', filter=insert_mode)(lambda ev: forward_word(ev))
```
i.e call `forward_word`

**Comment by randy3k** [comment]
It should work

**Comment by randy3k** [comment]
But keep in mind that all these are subjected to change (though unlikely).

**Comment by petobens** [comment]
It does work.. sorry about that. Thank you!

**Comment by petobens** [comment]
Just for completeness sake: any chance of adding formatting to the prompt vi mode indication? Otherwise we can close this issue

**Comment by petobens** [comment]
Also could you add `normal_mode = ~insert_mode` to `radian/key_bindings.py` file so as to define normal/navigation mode mappings? Thanks

**Comment by randy3k** [comment]
You could use the following to get normal mode.

```
operator <- import("operator")
normal_mode <- operator$inv(radian$key_bindings$insert_mode)
```

**Comment by petobens** [comment]
Is there a way to have the bindings defined above to work within a `browser` (debugging) prompt? Radian seems to autocomplete just fine within such prompt but my custom mapping don't work.

**Comment by randy3k** [comment]
`app$session$modes$r$prompt_key_bindings` will only apply the keybindings to the regular R mode. Use `app$session$modes$r$key_bindings` if you want all the keys to be enabled in all modes.

**Comment by randy3k** [comment]
By the way, if you want debug mode only keybindings, use `app$session$modes$browse$prompt_key_bindings`.

**Comment by petobens** [comment]
Nice! Didn't know about this. Thanks for the quick reply.

Is there a way to change the vi mode prompt indication format? Otherwise we can close this one.

**Comment by randy3k** [comment]
Done 41feb90, with options

```
options(
    radian.vi_mode_prompt = list(
        "vi-insert" = "(I) ",
        "vi-insert-multiple" = "(M) ",
        "vi-navigation" = "(N) ",
        "vi-replace" = "(V) "
    )
)
```

**Comment by petobens** [comment]
Awesome! Thanks
