### ISSUE TITLE
radian and R package crayon

### ISSUE THREAD

**Issue by chisqr** [randy3k/radian#159]
The following code prints the output in white instead of blue on Windows, is there some way to fix it? Thanks.

`library(crayon)`
`cat(blue("Hello", "world!\n"))`

**Comment by randy3k** [comment]
What happen if you run `Sys.getenv("ANSICON")` in radian?

**Comment by chisqr** [comment]
This is what I get:

```
r$> Sys.getenv("ANSICON")
[1] "1"
```

**Comment by randy3k** [comment]
It should be enabled from judging https://github.com/r-lib/crayon/blob/master/R/has_color.r#L70

**Comment by chisqr** [comment]
Thank you for the tip. Adding the following lines made it work:

```
options(crayon.enabled = TRUE)
options(crayon.colors = 256)
```

**Comment by randy3k** [comment]
It should be enabled by default. What re the values of `Sys.getenv("NO_COLOR")` and `isatty(stdout())`?

**Comment by randy3k** [comment]
I see what's happening. The latest release of crayon was in 2017...and that release doesn't check `ANSICON` as all.

**Comment by randy3k** [comment]
Please note that setting `options(crayon.enabled = TRUE)` will affect `knitr`: https://github.com/randy3k/radian/issues/144

**Comment by randy3k** [comment]
c2dbb6e will introduce unwanted side effects. We may need another workaround.

**Comment by chisqr** [comment]
I am using the following to get colors in the console, independent of crayon:

```
cat('\033[0;32m hello world  \033[0m')
```

**Comment by randy3k** [comment]
The ansi sequence should always work

**Comment by randy3k** [comment]
v0.4.7 should close it.
