### ISSUE TITLE
partial matching in .packages call

### ISSUE THREAD

**Issue by tjtnew** [randy3k/radian#161]
In 489e817 you added a call to `.packages` that used partial matching for the `all.available` argument (e.g. used `all` instead of `all.available`).  Is it possible to use the full argument instead (I have partial arguments flagged in my .Rprofile which keeps highlighting this)?  I'd have made a PR but I'm not familiar enough with python to check the change.

**Comment by randy3k** [comment]
No problem. Check the current master.
