### ISSUE TITLE
radian crashing in VS code

### ISSUE THREAD

**Issue by chisqr** [randy3k/radian#162]
I am using the VS code R extension [by Yuki Ueda] and when I do Ctrl + Enter to submit a line of code from the editor, the terminal process terminates with exit code 2. The 'always use active terminal' setting is unchecked in the extension. The extension is working properly with vanilla R.exe. Here are my settings:

R - 3.6.2
languageserver - 0.3.4
R VS code dextension - 1.2.6

**Comment by randy3k** [comment]
I am really not sure what's causing it. Perhaps check with vscode-R?

**Comment by randy3k** [comment]
Maybe related to this: https://github.com/randy3k/radian/issues/149

**Comment by chisqr** [comment]
Indeed it was. Upgrading to the most recent version [v0.4.7] did the trick. Thanks!
