### ISSUE TITLE
Nvim-R send startup args to radian

### ISSUE THREAD

**Issue by olesendan** [randy3k/radian#165]
Hi Randy.

I'm using radin with nvim-r and as a stand alone.

As standalone I like to have vim bindings, but not in nvim-r. Therefore I have tried the following setup, but can not get it to work. Do you have any input?

I'm trying to load a profile ajusted to to how I would like radian to behave in nvim-r.

my settings
let R_app = 'radian --profile="/home/dano/.config/nvim/radian_profile"'
let R_cmd = 'R'
let R_args = []
let R_bracketed_paste = 1

Greetings from denmark
Dan Olesen

**Comment by randy3k** [comment]
If you use radian as a standalone program, none of the settings would be applied. How are you going to launch radian within nvim/vim?

**Comment by olesendan** [comment]
Hi Randy.

Sorry, I'm not being clear. What I mean to say, is that I have the following two usercases.

1. radian launched from the commandline with "radian". In this case, i'm launching radian with it's default radian_profile. Here I like to have vim bindings.
2. with nvim and nvim-r. radian is opened in nvim buffer. I this scenario I would like to have emacs bindings. Therefore I thougth to use a costumized radian_profile. I am trying to load the profile with the command: let R_app = 'radian --profile="/path/to/costumized/radian_profile"'. With this in init.vim I'm getting the following message: R executable not round: 'radian --profile="/path/to/costumized/radian_profile"'. It works without the "--profi......" but offcouse now with the default radian_profile.

Greetings from denmark
Dan

I'm prob

**Comment by randy3k** [comment]
1. There is an option to turn on vi keybinding. Consider the following in `.radian_profile`

```
options(radian.editing_mode = "vi")
```

2. You should keep `R_app` as `radian`, but passing the arguments via `R_args `

**Comment by olesendan** [comment]
Hi Randy.

Thank you, for your suggestion.

I have the "vi" option in my default radian_profile. Thats the reason i'm asking. Is it possible to disable this option, when I'm calling radian from nvim-r?

I will try to pass the --profile=/path/to/customized/radian_profile to R_args.

Greetings from denmark
Dan Olesen

**Comment by olesendan** [comment]
I can confirm that passing a path to a costum radian_profile in nvim vill load it.

so I'm closing this issue

greetings from denmark
