### ISSUE TITLE
Error when sending code with line breaks

### ISSUE THREAD

**Issue by stegmueller** [randy3k/radian#167]
Using VScode, sending REPL code that involves line breaks no longer works.

Example code:
<img width="362" alt="code" src="https://user-images.githubusercontent.com/9674007/76684189-24a38f80-65e0-11ea-8241-86418e7f61ac.png">

Output (running radian 0.4.7 in VScode terminal):
<img width="539" alt="radian_broken" src="https://user-images.githubusercontent.com/9674007/76684192-2bca9d80-65e0-11ea-804a-7ced3992f961.png">

Expected output (using plain R in VScode terminal)
<img width="363" alt="R_ok" src="https://user-images.githubusercontent.com/9674007/76684202-36853280-65e0-11ea-96d4-144f870e7f02.png">

If I revert to radian version 0.4.4:
<img width="332" alt="radian_ok" src="https://user-images.githubusercontent.com/9674007/76684214-443ab800-65e0-11ea-9796-23073e53dd8e.png">

**Comment by randy3k** [comment]
radian has changed the default behaviour for auto matching parentheses. That why you see the additional closing parenthesis. By the way, you could turn on bracketed paste mode when using radian.

**Comment by randy3k** [comment]
Check https://github.com/Ikuyadeu/vscode-R/blob/master/README.md#extension-settings

**Comment by stegmueller** [comment]
Thanks Randy!

For posterity: setting `options(radian.auto_match = TRUE)` does it.

Changing  r.bracketedPaste is fine when sending code using vscode-R but it will not work when sending code from VScode (using "run selection in terminal" command).

**Comment by randy3k** [comment]
You need the bracketed paste mode sequences for that, I believe the default vscode command won’t added those sequences.

**Comment by randy3k** [comment]
There could be other potential issues if you don’t use bracketed paste mode.
