### ISSUE TITLE
How to change the R executable ?

### ISSUE THREAD

**Issue by sxyzy1016** [randy3k/radian#168]
I have 3 R installed: R Server (3.5.2), R Open (3.5.3) and R from cran (3.6.3). I want to use the 3.5.3 in `radian`, so I put it in `PATH`, but `radian` always uses the 3.5.2.
```
(base) C:\ProgramData\Miniconda3>R --version
R version 3.5.3 (2019-03-11) -- "Great Truth"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.


(base) C:\ProgramData\Miniconda3>radian --version
radian version: 0.4.7
r executable: C:\Program Files\Microsoft\ML Server\R_SERVER\bin\R
r version: 3.5.2
python executable: c:\programdata\miniconda3\python.exe
python version: 3.7.6

(base) C:\ProgramData\Miniconda3>where R.exe
C:\Program Files\Microsoft\R Open\R-3.5.3\bin\x64\R.exe

(base) C:\ProgramData\Miniconda3>dir "C:\Program Files\Microsoft\R Open\R-3.5.3\bin\x64"
2020/02/27  12:13    <DIR>          .
2020/02/27  12:13    <DIR>          ..
2019/04/09  21:09         1,726,616 libiomp5md.dll
2019/05/07  19:00            28,648 open.exe
2019/05/07  19:00        31,003,824 R.dll
2019/05/07  19:00            51,680 R.exe
2019/04/09  21:10        22,128,016 Rblas.dll
2019/05/07  19:00            50,144 Rcmd.exe
2019/05/07  19:00            34,272 Rfe.exe
2019/05/07  19:00           220,640 Rgraphapp.dll
2019/05/07  19:00            34,488 Rgui.exe
2019/05/07  19:00            45,032 Riconv.dll
2019/04/09  21:10        28,856,720 Rlapack.dll
2019/05/07  19:00            39,912 Rscript.exe
2019/05/07  19:00            35,304 RSetReg.exe
2019/05/07  19:00            35,304 Rterm.exe
```
And my `PATH` is:
<pre>
(base) C:\ProgramData\Miniconda3>echo %PATH%
C:\ProgramData\Miniconda3;
C:\ProgramData\Miniconda3\Library\mingw-w64\bin;
C:\ProgramData\Miniconda3\Library\usr\bin;
C:\ProgramData\Miniconda3\Library\bin;
C:\ProgramData\Miniconda3\Scripts;
C:\ProgramData\Miniconda3\bin;
C:\ProgramData\Miniconda3\condabin;
<b>C:\Program Files\Microsoft\R Open\R-3.5.3\bin\x64;</b>
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.0.166\windows\mpi\intel64\bin;
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt;
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;
C:\Program Files\Microsoft MPI\Bin;
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;
C:\Windows\system32;C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0;
C:\Windows\System32\OpenSSH;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn;
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;
C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0;
C:\Program Files\Java\jdk1.8.0_231\bin;
C:\Program Files\Java\jdk1.8.0_231\jre\bin;
C:\Program Files\Microsoft VS Code\bin;
C:\Program Files\Polyspace\R2019b\runtime\win64;
C:\Program Files\Polyspace\R2019b\bin;
C:\Program Files\Polyspace\R2019b\polyspace\bin;
C:\ProgramData\gmt6\bin;
C:\Program Files\Polyspace\R2018a\runtime\win64;
C:\Program Files\Polyspace\R2018a\bin;
C:\Program Files\dotnet;
C:\Program Files\Calibre2;
C:\Program Files\Git\cmd;
C:\Program Files\PowerShell\7;
C:\Users\SXY\AppData\Local\Microsoft\WindowsApps;
C:\Program Files\Bandizip;
C:\Program Files\JetBrains\CLion 2019.3.1\bin;
C:\Program Files\JetBrains\PyCharm 2019.3\bin
</pre>

How to make `radian` use the 3.5.3?

**Comment by randy3k** [comment]
What is the result of `R RHOME`? radian detects R binary in the following order in Windows.

1. check the environment variable `R_HOME`
1. check the result `R RHOME`
2. check registry `HKEY_LOCAL_MACHINE\Software\R-Core\R`

**Comment by sxyzy1016** [comment]
I didn't realize `R_HOME` works for Windows too.
```
(base) C:\ProgramData\Miniconda3>R RHOME
C:\PROGRA~1\MICROS~4\ROPEN~1\R-35~1.3

(base) C:\ProgramData\Miniconda3>set R_HOME=C:\Program Files\Microsoft\R Open\R-3.5.3

(base) C:\ProgramData\Miniconda3>radian --version
radian version: 0.4.7
r executable: C:\Program Files\Microsoft\R Open\R-3.5.3\bin\R
r version: 3.5.3
python executable: c:\programdata\miniconda3\python.exe
python version: 3.7.6
```
Set `R_HOME` and it works fine. Thanks. :)

**Comment by randy3k** [comment]
That's strange. `R RHOME` and the binary that radian picked are different.

**Comment by ajmoralesa** [comment]
Is there another way around to change the R executable? 

My PATH is: 

```
PS C:\Users\user1> $env:path
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\MATLAB\R2020b\runtime\win64;C:\Program Files\MATLAB\R2020b\bin;C:\Program Files\PuTTY\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\Library\bin;C:\Users\user1\AppData\Local\Microsoft\WindowsApps;C:\Users\user1\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\user1\AppData\Local\Programs\Git\cmd
```

`radian --version` gives:

```
radian version: 0.5.11
r executable: C:\Program Files\R\R-3.5.2\bin\R
r version: 3.5.2
python executable: C:\ProgramData\Anaconda3\python.exe
python version: 3.8.5
```

And the R version I'm targeting is at the User level. Here's the output of `R.home` and `version` in the RStudio console:

```
R.home()
"C:/Users/user1/DOCUME~1/R/R-40~1.4"

version

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.4                         
year           2021                        
month          02                          
day            15                          
svn rev        80002                       
language       R                           
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book 
```

How can I make `radian` use my R version 4.0.4 (2021-02-15)?

**Comment by jweickm** [comment]
I am trying to achieve the same thing. Did you ever find a solution, @ajmoralesa?
