### ISSUE TITLE
A colorscheme that works on both light and dark backgrounds?

### ISSUE THREAD

**Issue by pat-s** [randy3k/radian#172]
Related to https://github.com/randy3k/radian/issues/45

I switch between a light and dark terminal theme and haven't been able to find a radian colorscheme that works nicely with both.

One part of the radian colorscheme is either black or white, making it almost impossible to see what is being typed.

For example using "native" scheme and a white terminal background, the letters that are being typed are not visible.

I would even prefer no colorscheme at all and just following the respective terminal colorschemes font color. Is there a way to turn off the radian coloring?

**Comment by randy3k** [comment]
`radian` uses `prompt_toolkit` to highlight syntax. See
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/b1c212cf961541870d84248f0402bf60deb5ee5c/docs/pages/advanced_topics/styling.rst#color-depths

```
PROMPT_TOOLKIT_COLOR_DEPTH=DEPTH_4_BIT radian
```

Note that `ipython` also uses `prompt_toolkit` so it would also changes the color of ipython.

**Comment by pat-s** [comment]
Thanks. 4bit does not help, I've set it to 1bit now which essentially disables all coloring.

**Comment by randy3k** [comment]
4bit color uses your terminal ansi colors, so it is more your terminal color scheme issue.

**Comment by pat-s** [comment]
I see. The ANSI colors are set to the default dark theme I use and persist when I switch to the light theme which I load from a keybinding.

Essentially I would also need to switch to the ANSI colors of the light theme when changing themes on the fly.

Thanks for the heads up!

**Comment by pat-s** [comment]
Follow up: Most light color schemes have their ANSI "white" set to a very light white tone.

Setting this value to a darker tone (both for the "normal" and "bright" setting) makes radian usable with env var `PROMPT_TOOLKIT_COLOR_DEPTH=DEPTH_4_BIT` set.
This applies to strings and normal text, which otherwise appear in the same color as the background.

I've tried lots of common light color schemes and almost all of them had a ANSI white set to a very light white tone. This does not make sense to me if the background of these themes also use a white tone?

It feels wrong that I need to do this manual adjustment for commonly used light color schemes. If anyone has an idea what I might by missing here, help is appreciated!
