### ISSUE TITLE
Problem executing code blocks with '[['

### ISSUE THREAD

**Issue by rknx** [randy3k/radian#184]
Here's my code:
```
f <- function() {
    lapply(list, '[[', 1)
}
```
If I put the cursor right after `}` and run the code (Ctrl + Enter), I get this error:
```
Error: unexpected '}' in "}"
```
I'm guessing that it is because the console expects closing brackets for `[[`.

- rstudio runs the code without any error.
- if I select entire function and run, it doesn't produce error
- if I put cursor in second line, it executes second line (doesn't understand I'm defining a function)
- if I put cursor in first line, it asks me to enter function code in the console.
- `` `[[` `` (backticks) also produces same error

radian version 0.5.4
OS: Linux (Ubuntu 20.04 in WSL2)
IDE: Visual Studio Code 1.44.2
r version: 3.6.3
python version: 3.8.2

**Comment by randy3k** [comment]
You should switch on the bracketed paste mode in vscode.

**Comment by rknx** [comment]
It is already on.

`"r.bracketedPaste": true`

**Comment by randy3k** [comment]
Then please open an issue in vscode-R. It is not an issue of radian.

**Comment by rknx** [comment]
Thanks, I'm about to do that.

**Comment by renkun-ken** [comment]
See https://github.com/Ikuyadeu/vscode-R/issues/173.

**Comment by rknx** [comment]
Workaround:
I replaced `'[['` with `'\u005B\u005B'`, and now it works as expected.
This works in rstudio as well.

**Comment by rknx** [comment]
Better workaround:

Define new **single line** function. The single line part is important.
```
list_extract <- function(var, ind) var[[ind]]
```
Use the new function instead of `[[`
```
f <- function(list) {
    lapply(list, list_extract, 1)
}
```
