### ISSUE TITLE
Radian appears to fail to display cyrillic characters in UTF-8

### ISSUE THREAD

**Issue by D3SL** [randy3k/radian#186]
I compared identical CSV and XLS files in rstudio and vscode running Radian. The data is successfully imported but displayed in the console as character codes such as ```<U+041E>``` and simply invisible when opened with ```View()```.  Under rstudio some functions such as ```read_csv()``` may show character codes in their initial console output but when viewed directly the dataframe is still properly rendered in cyrillic.

Interestingly if I directly assign a cyrillic string to an object it will render correctly in the console when the assignment line prints but not when I call the object. EG ```cyrillictest<-"Тверская обл"``` will show up in Radian's console when run, but when I call ```cyrillictest``` I get this for output:

```
r$> cyrillictest
[1] "<U+0422><U+0432><U+0435><U+0440><U+0441><U+043A><U+0430><U+044F> <U+043E><U+0431><U+043B>"
````

**Comment by randy3k** [comment]
It is a known issue. You will need to upgrade to R4.0 to fix it.

**Comment by D3SL** [comment]
Updating R seems to give a partial fix. ```cyrillictest<-"Тверская обл"``` now renders properly when ```cyrillictest``` is called, but reading in an actual CSV with cyrillic characters results in ```Ð—Ðž \"ÐšÐžÐ¡\"``` in place of ```ЗАО \"АКОС\``` when attempting to use ```head()``` or similar. When calling a single column via ```[[``` or ```$``` it renders correctly. In every case RStudio always renders correctly.

I also ran into something interesting with another language. With cyrillic it doesn't matter what I use to read it into VSCode, it only renders properly if I call one column at a time. With Czech however ```readr::read_delim()``` behaves like cyrillic does, while ```base::read.delim()``` accepts ```fileEncoding="UTF-8-BOM``` and renders properly even when I use ```head()``` or ```[```.

```
base::read_delim()
"14 â€“ SluÅ¾by pro zdravotnÄ› postiÅ¾enÃ©,

readr::read_delim()
14 – Služby pro zdravotne postižené,
```

Even more interesting, that en dash (```– ```) apparently doesn't exist to VSCode/Radian. When I try to use ```tidyr::separate``` for that character it doesn't work. If I paste in ```–``` I get an error about empty search strings, and if I paste in the misrendered â€“ the command will run but not split the column correctly. While in RStudio it works just fine.

I'm wondering if part of this is that RStudio is doing something nonstandard and that's why it works while VSCode/Radian doesn't.

**Comment by randy3k** [comment]
I am guessing some of them are to R’s bugs. On windows, radian and RStudio runs in different modes. RStudio and the official R GUI run in GUI mode, there are specific code to handle non ascii characters. However, radian, like RTerm, runs in non GUI mode. It doesn’t handle non ascii chars very well. In fact, you will have even worse experience with RTerm. 

Would you share a sample file to me to reproduce the issues? I want to see if there are workarounds in these cases or If I would figure out where the bugs are and inform upstream.

**Comment by randy3k** [comment]
> Updating R seems to give a partial fix. `cyrillictest<-"Тверская обл"` now renders properly when `cyrillictest` is called, but reading in an actual CSV with cyrillic characters results in `Ð—Ðž \"ÐšÐžÐ¡\"` in place of `ЗАО \"АКОС\` when attempting to use `head()` or similar. When calling a single column via `[[` or `$` it renders correctly. In every case RStudio always renders correctly.

```
title, title2
Тверская обл, postižené

```

and this is my result
```
r$> a = read.csv("utf.csv", encoding = "UTF-8")

r$> a
                                                                                      title     title2
1 <U+0422><U+0432><U+0435><U+0440><U+0441><U+043A><U+0430><U+044F> <U+043E><U+0431><U+043B>  postižené

r$> a$title
[1] "Тверская обл"


r$> a$title2
[1] " postižené"

r$> readLines("utf.csv", encoding = "UTF-8")
[1] "title, title2"           "Тверская обл, postižené"
```

I believe it is due to a bug in R which doesn't respect `EmitEmbeddedUTF8` in `head`, see for example https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17677

And you are seeing a different output, maybe because your system default language is Cyrillic!? But why Czech works? I gauss the `head` function is doing something for the European accented letters.


> I also ran into something interesting with another language. With cyrillic it doesn't matter what I use to read it into VSCode, it only renders properly if I call one column at a time. With Czech however `readr::read_delim()` behaves like cyrillic does, while `base::read.delim()` accepts `fileEncoding="UTF-8-BOM` and renders properly even when I use `head()` or `[`.
> 
> ```
> base::read_delim()
> "14 â€“ SluÅ¾by pro zdravotnÄ› postiÅ¾enÃ©,
> 
> readr::read_delim()
> 14 – Služby pro zdravotne postižené,
> ```
> 

I will need to take a closer look at it.


> Even more interesting, that en dash (`– `) apparently doesn't exist to VSCode/Radian. When I try to use `tidyr::separate` for that character it doesn't work. If I paste in `–` I get an error about empty search strings, and if I paste in the misrendered â€“ the command will run but not split the column correctly. I had to use the java character code to get it to work in VSCode/Radian, while in RStudio I could just paste in an en dash.


This seems to be a bug in upstream [prompt_toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit). `ipython` uses the same library and it suffers from the same problem.

**Comment by D3SL** [comment]
Try the files from [here (russian)](https://rossvyaz.ru/deyatelnost/resurs-numeracii/vypiska-iz-reestra-sistemy-i-plana-numeracii) and [here (czech)](https://www.ctu.cz/vyhledavaci-databaze/pridelena-cisla-a-kody?form_build_id=form-i82Vg8MxkvVzvIW1cawcpmHPaxfqwSkLz5m_BnBb5Uk&form_id=pridelena_cisla_a_kody_page_search_form&signpost_number=1&find_number=0&bussinessman_find=0&textfield_input=&format_number=0&bussinessman=0&pick_date_type=0&date%5Bdate%5D=18.09.2017&summary_number_submit=Search). I don't think it's just a matter of character type, I think it's also something to do with byte order marks because I did need to specifically use ```UTF-8-BOM``` to get the czech file read properly.

And my system language is most assuredly set at US english, but I can verify these same effects are all replicated on a computer set to English International.

**Comment by randy3k** [comment]
> Try the files from here (russian) and here (czech). I don't think it's just a matter of character type, I think it's also something to do with byte order marks because I did need to specifically use UTF-8-BOM to get the czech file read properly.

You meant the base R function `read.csv`? You always need to specify the default encoding in `read.csv` otherwise it will treat it as Windows native locale.

<img width="860" alt="Screen Shot 2020-05-14 at 5 42 49 PM" src="https://user-images.githubusercontent.com/1690993/81999575-5948bd00-960a-11ea-974e-bad8b9596be3.png">

**Comment by randy3k** [comment]
After some initial investigation,

1. the `print.table` function is bugged for certain unicodes. Vectors are fine. Both in GUI and non-GUI mode.

2. in GUI mode, the `print.tibble` function has some trick to to make sure the display is correct. But the trick doesn't work in non-GUI mode.

**Comment by randy3k** [comment]
I think I understand what `print.tbl` has done to make the rendering correct. `radian` assumes that the unicode escape sequences are not buffered, but it seems that it is not the case in `print.tbl`. So we are not able to render the output of `print.tbl` correctly.

**Comment by randy3k** [comment]
I was wrong, it is because `radian` didn't search the unicode escape sequences correctly. A fix is on the way.

**Comment by randy3k** [comment]
Please upgrade rchitect to 0.3.26. It should fix the `readr::read_csv` issue.

```
pip install -U rchitect
```
