### ISSUE TITLE
Exception: Cannot load shared library: The specified module could not be found.

### ISSUE THREAD

**Issue by jbishop-intven** [randy3k/radian#192]
I used to have radian working in a conda environment but I'm struggling to get it to work again in a new install. I am working in Powershell in a Conda environment (`C:\Conda\envs\r36') on a Windows 10 machine.

The result of running `radian` is: 
>Traceback (most recent call last):
>  File "c:\conda\envs\r36\lib\runpy.py", line 193, in _run_module_as_main return _run_code(code, main_globals, None,
>  File "c:\conda\envs\r36\lib\runpy.py", line 86, in _run_code exec(code, run_globals)
>  File "C:\Conda\envs\r36\Scripts\radian.exe\__main__.py", line 7, in <module>
>  File "c:\conda\envs\r36\lib\site-packages\radian\__init__.py", line 101, in main RadianApplication(r_home, ver=__version__).run(options)
>  File "c:\conda\envs\r36\lib\site-packages\radian\radianapp.py", line 89, in run rchitect.init(args=args, register_signal_handlers=True)
>  File "c:\conda\envs\r36\lib\site-packages\rchitect\setup.py", line 42, in init raise Exception(load_lib_error())
> Exception: Cannot load shared library: The specified module could not be found.

And the result of running `radian --version` is:
>radian version: 0.5.4
>r executable: C:\Conda\envs\r36\Lib\R\bin\R
>r version: 3.6.3
>python executable: c:\conda\envs\r36\python.exe
>python version: 3.8.1

The `R.dll` library file is in `C:\Conda\envs\r36\Lib\R\bin\x64` and the result of `$env:R_HOME` is:
>C:\Conda\envs\r36\Lib\R

I tried to dig into the rchitect source code within `C:\Conda\envs\r36\Lib\site-packages\rchitect` to see what the problem might be, but I got lost at the call to `lib._libR_load(rhome.encode("utf-8"))` in `setup.py`. I looked at issue #105 for more troubleshooting help but I can't run `p = rchitect.utils.libRgapath(rhome)` at the prompt because it seems that the method is not in `rchitect` version 0.5.4? The methods that are in my version of `rchitect.utils` do seem to find the correct `R.dll`...

Thanks for any help!

**Comment by randy3k** [comment]
What channel in conda do you use to install R?

**Comment by jbishop-intven** [comment]
conda-forge

**Comment by randy3k** [comment]
It seems a fix in supporting Microsoft store python breaks condo python.

**Comment by randy3k** [comment]
A fix is on the way, will be fixed by the next version of rchitect.

**Comment by randy3k** [comment]
see if rchitect 0.3.27 fixes it.

```
pip install -U rchitect
```

**Comment by jbishop-intven** [comment]
It absolutely does. Thanks!
