### ISSUE TITLE
Use radian in Windows vscode

### ISSUE THREAD

**Issue by kdzhang** [randy3k/radian#204]
Hi, I have problems in using radian as the default R console in vscode Windows. My current workflow is to set below in vscode settings:

```json
"r.bracketedPaste": true,
"r.alwaysUseActiveTerminal": true
```

Then manually start a `radian` console by typing `radian` in the terminal. Then vscode will send all my code to the radian console without any problem. This works but it's a bit annoying because I have to manually start the console.

My question is, is it possible that I can configure vscode to make it automatically use `radian` console so that I don't have to manually start it from terminal every time? If I simply set `"r.alwaysUseActiveTerminal": false`, vscode will just start a regular R console.

Thanks!

**Comment by randy3k** [comment]
I am sorry that I don't much experience with vscode to help you.

You may want to open an issue in https://github.com/Ikuyadeu/vscode-R instead.
