### ISSUE TITLE
[NEED HELP] RuntimeError: Cannot determine R Home. in Vscode

### ISSUE THREAD

**Issue by Direct-A** [randy3k/radian#211]
When I use `Run Source` I get a error in terminal windows

![2020-08-01_20-05](https://user-images.githubusercontent.com/46991254/89114000-6d35e980-d4aa-11ea-81d8-b8f55e5fd133.png)

```python
Traceback (most recent call last):
  File "home/xxx/miniconda3/bin/radian", line 8, in <module>
    sys. exit(main())
  File "home/xxx/miniconda3/lib/python.7/site-packages/radian/init.py", line 44, in main
    r_home = Rhome()
  FIle "home/xxx/miniconda3/lib/python.7/site-packages/rchitect/utils.py", line 84, in Rhome
    raise RuntimeError ("Cannot determine R HOME.")
RuntimeError: Cannot determine R HOME.
```

and a notify

![2020-08-02_09-44](https://user-images.githubusercontent.com/46991254/89114008-88085e00-d4aa-11ea-8b34-61efd81ae1f6.png)

But, in system terminal I can use radiant and find R HOME.
How to solve it? Thanks.

In my enviroment value I only have `RSTUDIO_WHICH_R=/home/xxx/miniconda3/bin/R`.
I install R by `conda insatall`, is that the problem?

 - Vscode version is `1.47.1`   
 - vscode extention `ikuyadeu.r` version is `1.4.3`   
 - vscode extention `reditorsupport.r-lsp` version is `0.1.6`   
 - zsh version is `5.8 (x86_64-pc-linux-gnu)`   
 - R version is `4.0.2 (2020-06-22)` install by `conda install -c conda-forge r-base=4.0`   
 - radian version is `0.5.8`   
 - python version is `3.7.7`

**Comment by randy3k** [comment]
Check this section: https://github.com/randy3k/radian#how-to-switch-to-a-different-r-or-specify-the-version-of-r

**Comment by Direct-A** [comment]
> Check this section: [randy3k/radian#how-to-switch-to-a-different-r-or-specify-the-version-of-r](https://github.com/randy3k/radian#how-to-switch-to-a-different-r-or-specify-the-version-of-r)

Thanks! It works!

I solve by add options in my vscode settings
```json
  "r.rterm.option": ["--r-binary=/home/xxx/miniconda3/bin/R"],
````
