### ISSUE TITLE
bottom of console

### ISSUE THREAD

**Issue by tlhenvironment** [randy3k/radian#212]
In the normal console it is handy that radian leaves a few blank lines before the bottom of the screen. When used as a console in vs code, I would the prompt to be fixed at the lowest position though.
Is there an option for that? I couldn't find one.

**Comment by randy3k** [comment]
The spaces are left for the completion menu, you will need to disable autocompletion while typing if you want the prompt to be positioned at the bottom.

**Comment by tlhenvironment** [comment]
Ah, haven't thought of that!
Worked well with
options(radian.complete_while_typing = FALSE)
Thanks!
