### ISSUE TITLE
C stack size too small

### ISSUE THREAD

**Issue by assignUser** [randy3k/radian#214]
Hey,

first off thanks for radian, it looks nice and mostly works great!

I have some code with recursion and nested functions which I can't run in radian:
```r
Error: C stack usage  1915264 is too close to the limit
```
but can run without issue in `R.exe` (64bit).
Radians C stack seems to be much smaller than the normal R terminal's.
radian.exe:
```r 
size    current  direction eval_depth
   1914470      16008          1          2
```
vs. R.exe
```r
 size    current  direction eval_depth 
  63737856      11288          1          2 
```
As far as I could find out this is a compiler setting that needs to be adjusted? 
Or is there a way to change this via cli flag or something?

**Comment by randy3k** [comment]
It might be a Windows specific issue, I don't experience the reduction of stack size on macOS. May be related to how python restricts the stack size on Windows? Though I am not sure.

**Comment by assignUser** [comment]
You should be able to pass the [stack_size/stack parameter](https://stackoverrun.com/de/q/471770) to gcc via conda? I have absolutly no idea how the whole conda build process works though...

**Comment by assignUser** [comment]
So it seems that the only way to change the stack size of python programs on windows (which seems to be ~2mb by default) is to use [threading.stack_size()](https://stackoverflow.com/questions/2917210/what-is-the-hard-recursion-limit-for-linux-mac-and-windows) because [resource](https://docs.python.org/3/library/resource.html) is not available on windows.

I used this [workaround](https://bugs.python.org/issue31113#msg299876) to increase the default stack size. I would still suggest to maybe look into a way to use therading to fix this on windows machines as I ran into this problem using not only my own code but also packages from cran.

**Comment by randy3k** [comment]
Thanks for looking into it. I will need to look into it more closely.

**Comment by assignUser** [comment]
> It might be a Windows specific issue, I don't experience the reduction of stack size on macOS. May be related to how python restricts the stack size on Windows? Though I am not sure.

I have recently switched to Linux and can confirm that this is not a windows only issue. But I can also report on solutions to this issue for use within editors and cli (e.g. gha):

* In a normal terminal we can use `ulimit -s` to get and set the stack size limit of the current termina, this will be inherited by any R process spawned in this session, can also be used within github actions, see below.
* The [{unix}](https://cran.r-project.org/web/packages/unix/) package allows us to set the different limis, including the stack limit from within R: `unix::rlimit_stack()`

As this is not directly related to radian I will close this issue.

```yaml
 name: Check Linux
        if: runner.os == 'Linux'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: |
          ulimit -s 10000000
          Rscript -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")'
```

**Comment by randy3k** [comment]
That's not just an radian issue though.

**Comment by assignUser** [comment]
@randy3k Yeah I did not put that quite right. I initially thought it was a radian issue as on Windows this only happens with radian and not with the default R.exe/Rterm.exe. 

Now I know better and so I closed the issue :) and thank you again for radian!

**Comment by randy3k** [comment]
Well, on Windows, there is still a issue of reducing the stack size from 63737856 to 1914470.

**Comment by colinpmillar** [comment]
Was there any solution or workaround that a basic radian user could perform to get round this? Or do I need to search on python forums?  THanks for any help (windows radian user on MS code)

**Comment by assignUser** [comment]
> I used this [workaround](https://bugs.python.org/issue31113#msg299876) to increase the default stack size. 

@colinpmillar

**Comment by assignUser** [comment]
Hm I have run much more complicated shiny apps through radian without an issue, can you post your session info?

**Comment by colinpmillar** [comment]
yeah me too, so I was surprised..  I run radian from a miniconda installation, i updated to the most recent version of miniconda for info.
```r
r$> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)  
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C
[5] LC_TIME=English_United Kingdom.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] shiny_1.7.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3     crayon_1.5.1     digest_0.6.29    later_1.3.0      mime_0.12
 [6] R6_2.5.1         jsonlite_1.8.0   lifecycle_1.0.1  xtable_1.8-4     magrittr_2.0.3  
[11] cachem_1.0.6     rlang_1.0.2      cli_3.3.0        promises_1.2.0.1 jquerylib_0.1.4    
[16] bslib_0.3.1      ellipsis_0.3.2   tools_4.2.0      httpuv_1.6.5     fastmap_1.1.0   
[21] compiler_4.2.0   htmltools_0.5.2  sass_0.4.1
```

**Comment by tarensanders** [comment]
Just want to note I'm having the same issue. Trying to run even a simple shiny app in radian fails with the C stack usage error from OP (on Windows), but the same code runs fine in R.exe, Rstudio, or deployed to a tiny server.

> I used this [workaround](https://bugs.python.org/issue31113#msg299876) to increase the default stack size.

This works, but is pretty hacky. You need to install Visual studio, download the right buildtools, and then find where it's installed editbin. And, it's very easy to ruin your Python install (recommend making a backup).

**Comment by assignUser** [comment]
I can confirm that this only happens with R 4.2 but not with R 4.1.3 with the same unchanged radian version (0.6.0).

As the stack usage can be alleviated by changing the python executable it seems to be some interplay between python and R 4.2? Maybe the issue is with rchitect? @randy3k
