### ISSUE TITLE
vscode doesnt run R code in radian when i hit control enter

### ISSUE THREAD

**Issue by bdeshon** [randy3k/radian#215]
Hello, I just set up radian to run R code.  I thought i did everything correctly but I guess might have goofed somewhere. :) 

I pip installed radian and it works when I run 'radian' from the windows cmd (I am running windows 10).  When I go into vscode and hit control enter it does not execute radian.  At first I get an error that says 'There are no open terminals'.  When I open a new terminal and repeat control enter, it runs the code in the command prompt but does not open radian first.  I wasn't sure if it is possible to have radian launch when the line is executed (similar to how python works with vscode).

Below is the settings in vscode:
`"r.rterm.windows": "C:\\Users\\XXXX\\AppData\\Local\\Continuum\\miniconda3\\Scripts\\radian.exe",`
    `"r.rterm.option": [
        "--no-save",
        "--no-restore",
        "radian" ]`
`"r.terminalPath": "D:\\R-4.0.2\\bin\\x64\\r.exe"`
`"r.alwaysUseActiveTerminal": true,`
`"r.editor.bracesOnNewLine": true,`
`"r.bracketedPaste": true,`
`"r.lsp.path": "D:\\R-4.0.1\\bin\\x64",`

The vscode extensions I have installed are:
-R
-R Extension Pack
-R LSP Client
-R Tools
-r-vscode-tools

I appreciate any help you all could provide.

**Comment by randy3k** [comment]
It is more a vscode R extension issue. Please move it to the relevant repo.

**Comment by bdeshon** [comment]
OK thank you.  I figured i would start here first. :)
