### ISSUE TITLE
Locate prompt at bottom of window

### ISSUE THREAD

**Issue by andycraig** [randy3k/radian#231]
radian seems to keep about 7 lines of space below the prompt:

![image](https://user-images.githubusercontent.com/23294156/98429153-61307800-20e8-11eb-86bf-d6f047829b51.png)

If I make it about one line smaller, I get the message 'Window too small...':

![image](https://user-images.githubusercontent.com/23294156/98429181-7d341980-20e8-11eb-8798-819cd86990e9.png)

It's like this for me on both Linux and Windows. The screenshots are from radian version 0.5.9.

It would be nice if the prompt sat at the bottom of the window. Also, it would be nice if the 'Window too small...' alert didn't happen at all.

I searched for 'window too small' in this repo and couldn't find it. I did the same search in https://github.com/prompt-toolkit/python-prompt-toolkit and it produced results. So I wonder if the prompt location and the 'Window too small...' message are coming from prompt_toolkit rather than radian. If so, please feel free to close this issue and I'll create one over at prompt_toolkit instead.

Thank you very much for making radian, I really like using it!

**Comment by renkun-ken** [comment]
Disabling auto completion via `options(radian.complete_while_typing = FALSE)` will remove the blank but it would be definitely nice if the completion buffer could be managed in a more flexible way.

**Comment by randy3k** [comment]
Unfortunately, the spacing is handled by prompt toolkit so it's better to leave it alone.

**Comment by andycraig** [comment]
Thanks both! Good to know that space is there for a reason. I'll set the option suggested by @renkun-ken for now, and might follow up at prompt_toolkit to see if more flexibility can be added.
