### ISSUE TITLE
Cannot load R packages

### ISSUE THREAD

**Issue by JunjieLeiCoe** [randy3k/radian#235]
Hi, 

Thanks for Radian. 
I trailed with radian recently (switching from Rstudio to VSCode)

I found that after I pip installed Radian, it does not recognize my local R packages installed. 
For example, I have ggplot2 installed, but radian kept telling me that 

> Error in library(ggplot2) : there is no package called 'ggplot2'

I was wondering if I need to modify the `Rprofile.site` file or? 

I am using a windows 10 machine, and the R version is 

> R version 4.0.2 (2020-06-22) -- "Taking Off Again"
> Platform: x86_64-w64-mingw32 (64-bit)

**Comment by randy3k** [comment]
It's likely that the library path is not set correctly. See https://stat.ethz.ch/R-manual/R-devel/library/base/html/libPaths.html

**Comment by JunjieLeiCoe** [comment]
Got it!  Thanks a lot. 
It seems that in windows, the libraries are installed in the win document folder instead of under the R folder. 
After I modify with the .libPath() command, it works.

thanks!
