### ISSUE TITLE
Autocompletion stops working

### ISSUE THREAD

**Issue by awellis** [randy3k/radian#240]
I'm using radian 0.5.9 on MacOS Catalina with miniconda, installed from source using ` python setup.py install`

After the first command, the prompt changes to `>`, and the autocompletion dropdown stops working.

```
❯ radian --version                                                                                                  14:06:17
radian version: 0.5.9
r executable: /Library/Frameworks/R.framework/Resources/bin/R
r version: 4.0.3
python executable: /Users/andrew/miniconda/bin/python
python version: 3.7.4
```
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/94028/102084281-3b983c00-3e15-11eb-9e65-f97f1db5b1b3.png">
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/94028/102084325-4b178500-3e15-11eb-9855-e088e0577fd0.png">
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/94028/102084374-59fe3780-3e15-11eb-85ee-745c4083e763.png">

**Comment by randy3k** [comment]
It seems that you got the vanilla prompt after the first line. No idea how it could happen though.

**Comment by awellis** [comment]
exactly. No idea either.

**Comment by awellis** [comment]
Anyone have any idea why this might be happening? I still get the same behaviour on MacOS Big Sur, after a fresh install of Miniconda, and then 

```
conda install pip
pip install -U git+https://github.com/randy3k/radian
```

**Comment by awellis** [comment]
This may have been related to some obscure setting in my `.Rprofile`, so I'm closing this.
