### ISSUE TITLE
automatically add ) in the end of line when ctrl+enter

### ISSUE THREAD

**Issue by microsat2018** [randy3k/radian#242]
I tried to send line command to console by 'ctrl+enter'. But it seems the radian automatically added ')' at the end of the command. My command is correct absolutely and doesn't need any extra ) at the end.

Please help me cope with this. My OS is windows. R client is Visual Studio Code (latest version). radian is also the latest version.

**Comment by randy3k** [comment]
You may want to disable the auto match feature. The root of the issue is that VSCode in Windows doesn't support bracketed paste mode. You could search "bracketed paste mode" at the issues of VSCode-R to gain some insights.

**Comment by microsat2018** [comment]
Hi Randy,

Thank you. May I ask how to disable the auto match feature in radian
for windows 10?

Thank you again.
Best regards,

Mike

You may want to disable the auto match feature. The root of the issue is that VSCode in Windows doesn't support bracketed paste mode. You could search "bracketed paste mode" at the issues of VSCode-R to gain some insights.

**Comment by randy3k** [comment]
Put 
```
options(radian.auto_match = FALSE)
```
in radian profile.
