### ISSUE TITLE
Add option to install radian from conda-forge

### ISSUE THREAD

**Issue by gvelasq** [randy3k/radian#244]
Thank you for this great R console. Would you consider adding radian as a recipe to conda-forge?

**Comment by randy3k** [comment]
I am not familiar with the procedure. I am happy if someone could initiate this.

**Comment by jdblischak** [comment]
I can work on this. In addition to radian, we'll also need to add [rchitect](https://github.com/randy3k/rchitect).

**Comment by jdblischak** [comment]
@gvelasq Thanks for getting the discussion started and providing a central location to track progress. Please give it a try:

```
conda install -c conda-forge radian
```

@randy3k Thanks for all your help getting your packages on conda-forge (and of course for creating and maintaining this awesome R console).

**Comment by gvelasq** [comment]
@jdblischak and @randy3k, thank you very much for setting this up. I can confirm that installing `radian` works perfectly when installing from `conda-forge`. I also used `conda-forge` to install `jedi` after installing `radian` and it was very convenient that the correct correct version of `jedi` was installed automatically.

On our end, @ivelasq and I will edit our recent [blog post](https://ivelasq.rbind.io/blog/vscode-live-share/) to show the simplified installation instructions from `conda-forge` and we'll thank you for your efforts there.

**Comment by jdblischak** [comment]
> On our end, @ivelasq and I will edit our recent blog post to show the simplified installation instructions from conda-forge and we'll thank you for your efforts there.

Great blog post. I really enjoyed it, and I hope to try out live sharing in the future. And since you're clearly fans of conda-forge, I have to point out that you can also install R and R packages from conda-forge. Then both your Python and R setup can be isolated per environment/project.

**Comment by gvelasq** [comment]
Closed in 8448e0375df5cb422e4af4db518c135db06b6c94. Many thanks!

**Comment by randy3k** [comment]
@jdblischak 
just want to let you know that the next version of radian 0.5.11 will support jedi 0.18.

**Comment by jdblischak** [comment]
> just want to let you know that the next version of radian 0.5.11 will support jedi 0.18.

Great! How do you want to proceed with updating the conda recipe? I see multiple options:

1. Update `run_constrains` to `jedi <= 0.18`. I think this is the most conservative approach. It'll allow radian to be used with jedi 0.18 or earlier, but make no guarantees about future versions of jedi (and actively prevent this situation).
2. Move jedi to a strict dependency. This is the most aggressive option. But if most users will want the features that jedi provides, it would make sense.
3. Remove jedi from the recipe all together. This would allow it to be handled similarly to R. Users are free to install it however they like.

**Comment by randy3k** [comment]
I guess we could remove the requirement as a whole. I don't expect the code to break any time soon.
