### ISSUE TITLE
Install from pip succeeds, but cannot start (MemoryError)

### ISSUE THREAD

**Issue by pdiegmann** [randy3k/radian#249]
Hi all,

just installed radian (via pip and also tried pip+git). However, I can't use it due to the following error:

> Traceback (most recent call last):
>   File "/Users/x/miniforge3/bin/radian", line 8, in <module>
>     sys.exit(main())
>   File "/Users/x/miniforge3/lib/python3.9/site-packages/radian/__init__.py", line 11, in main
>     from rchitect.utils import Rhome, rversion
>   File "/Users/x/miniforge3/lib/python3.9/site-packages/rchitect/__init__.py", line 3, in <module>
>     from .interface import rparse, reval, rprint, rlang, rcall, rcopy, robject
>   File "/Users/x/miniforge3/lib/python3.9/site-packages/rchitect/interface.py", line 8, in <module>
>     from .xptr import new_xptr, new_xptr_p, from_xptr
>   File "/Users/x/miniforge3/lib/python3.9/site-packages/rchitect/xptr.py", line 11, in <module>
>     def finalizer(s):
> MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks

I'm on macOS 11.1, M1/arm64 with pip 20.3.3 on Python 3.9.
Any help greatly appreciated!

**Comment by storopoli** [comment]
Same here. Also on macOS 11.1/arm64 with pip 21.0 on Python 3.9.1. (installed with radian with pip)

**Comment by storopoli** [comment]
Solved for me. See if this works for you @pdiegmann. Use native python (that is v.3.9.1) from brew (arm):

```
❯ type -a pip3
pip3 is /Users/storopoli/miniforge3/bin/pip3
pip3 is /opt/homebrew/bin/pip3
pip3 is /usr/local/bin/pip3
pip3 is /usr/bin/pip3
```

```
❯ /opt/homebrew/bin/pip3 install -U radian
```

```
❯ radian
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Platform: arm-apple-darwin20.2.0 (64-bit)

r$>   
```

**Comment by pdiegmann** [comment]
Thanks for the suggestion, but sadly did not change anything for me.
I made sure to uninstall radian before reinstalling. Also using `/opt/homebrew/bin/radian` directly does not change the result :(

**Comment by randy3k** [comment]
Is it an issue of M1? Unfortunately I don't own the latest MacBook to test it.

**Comment by randy3k** [comment]
It seems that the old style callback has some issues on new macbooks: https://cffi.readthedocs.io/en/latest/using.html#callbacks

**Comment by randy3k** [comment]
@pdiegmann could you try upgrading to the dev version of [rchitect](https://github.com/randy3k/rchitect)

```
pip install -U git+https://github.com/randy3k/rchitect
```

**Comment by pdiegmann** [comment]
Thank you for the input, @randy3k! Yes, it's a M1 mac mini.
Gave it a shot:

> (base) x@mac-mini ~ % /opt/homebrew/bin/pip3 install -U git+https://github.com/randy3k/rchitect
> Collecting git+https://github.com/randy3k/rchitect
>   Cloning https://github.com/randy3k/rchitect to /private/var/folders/d5/pvn0gcwj3hsc6lz_qjk1j8vh0000gn/T/pip-req-build-w1j53w9_
>   Running command git clone -q https://github.com/randy3k/rchitect /private/var/folders/d5/pvn0gcwj3hsc6lz_qjk1j8vh0000gn/T/pip-req-build-w1j53w9_
>     ERROR: Command errored out with exit status 1:
>      command: /opt/homebrew/opt/python@3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d5/pvn0gcwj3hsc6lz_qjk1j8vh0000gn/T/pip-req-build-w1j53w9_/setup.py'"'"'; __file__='"'"'/private/var/folders/d5/pvn0gcwj3hsc6lz_qjk1j8vh0000gn/T/pip-req-build-w1j53w9_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/d5/pvn0gcwj3hsc6lz_qjk1j8vh0000gn/T/pip-pip-egg-info-71ahdszi
>          cwd: /private/var/folders/d5/pvn0gcwj3hsc6lz_qjk1j8vh0000gn/T/pip-req-build-w1j53w9_/
>     Complete output (30 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/d5/pvn0gcwj3hsc6lz_qjk1j8vh0000gn/T/pip-req-build-w1j53w9_/setup.py", line 32, in <module>
>         setup(
>       File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
>         return distutils.core.setup(**attrs)
>       File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 423, in __init__
>         _Distribution.__init__(self, {
>       File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
>         self.finalize_options()
>       File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 695, in finalize_options
>         ep(self)
>       File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
>         ep.load()(self, ep.name, value)
>       File "/opt/homebrew/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
>         add_cffi_module(dist, cffi_module)
>       File "/opt/homebrew/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
>         execfile(build_file_name, mod_vars)
>       File "/opt/homebrew/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
>         exec(code, glob, glob)
>       File "rchitect/src/build.py", line 5, in <module>
>         ffibuilder = FFI()
>       File "/opt/homebrew/lib/python3.9/site-packages/cffi/api.py", line 48, in __init__
>         import _cffi_backend as backend
>     ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
>       Referenced from: /opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
>       Expected in: flat namespace
>      in /opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
>     ----------------------------------------
> WARNING: Discarding git+https://github.com/randy3k/rchitect. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by randy3k** [comment]
it seems to be an issue of the homebrew python. Could you try different distributions of python?

**Comment by pdiegmann** [comment]
Alright, using the python 3.9.1 from miniforge worked. However, I need to install a parallel version of python running under Rosetta 2 as x86_64, as R is not available as arm64 and it therefore is incompatible with radian installed as arm64/running on Python as arm64.
Thank you for your help!

**Comment by randy3k** [comment]
Ya, you are right. We will need to [wait for R 4.1](https://mac.r-project.org/).

**Comment by storopoli** [comment]
Hey, R is available for arm, I'm using it. `brew install r` (arm64 brew)

**Comment by pdiegmann** [comment]
Worked like a charm! Thank you, @storopoli!
