### ISSUE TITLE
R share library does not exist

### ISSUE THREAD

**Issue by pfren1998** [randy3k/radian#250]
Hi!
I set the R_BINARY in ~/.bashrc using the command below
```sh
export R_BINARY="/mnt/Storage/home/renpengfei/miniconda3/envs/tools/bin/R"
```
when I start radian, I encountered an error which says
`RuntimeError: R share library (WARNING: ignoring environment value of R_HOME
/mnt/Storage/home/renpengfei/miniconda3/envs/tools/lib/R/lib/libR.so) does not exist`

However, I find the libR.so does exist under /mnt/Storage/home/renpengfei/miniconda3/envs/tools/lib/R/lib. It is really strange. Could you please help me with this issue? Thanks!

**Comment by randy3k** [comment]
What is the result of `/mnt/Storage/home/renpengfei/miniconda3/envs/tools/bin/R RHOME`?

**Comment by pfren1998** [comment]
Hi, it is `/mnt/Storage/home/renpengfei/miniconda3/envs/tools/lib/R`

**Comment by pfren1998** [comment]
Hi, it works after I restarted the shell. Thanks for your reply!
