### ISSUE TITLE
vim editing mode stopped working

### ISSUE THREAD

**Issue by klmr** [randy3k/radian#252]
All of the sudden recently the vim editing mode stopped working. It just always uses the Emacs mode. `getOption('radian.editing_mode')` returns `"vim"`.

I’m on macOS 10.14.6, `radian --version` is

```
radian version: 0.5.9
r executable: /Library/Frameworks/R.framework/Resources/bin/R
r version: 4.0.3
python executable: /usr/local/opt/python@3.9/bin/python3.9
python version: 3.9.1
```

I haven’t recently updated radian; however, I did update Homebrew and that led to a whole chain of other upgrades, including apparently an automatic reinstall of Python 3.9. My installed readline version is 8.1, and vim mode in other readline-enabled applications continues to work. My readline config also contains the following:

```
set keymap vi
set editing-mode vi
"\e": vi-movement-mode
```

I realise this is incredibly vague. I’m happy to collect diagnostics or do some debugging if that’s helpful, but I’d need directions where to look.

**Comment by randy3k** [comment]
radian does not use readline but prompt-toolkit. Let me check if there is any issue with python 3.9 with prompt-toolkit 2.x. For python 2 compatibility, we didn’t upgrade prompt-toolkit to the latest version. Maybe it is causing some issues.

**Comment by klmr** [comment]
Oh that’s weird:

```bash
pip3 show prompt_toolkit
WARNING: Package(s) not found: prompt_toolkit
```

However, manually installing it unfortunately doesn’t fix the issue.

**Comment by randy3k** [comment]
Oddly, it is working for me.
```
(randyimac)-~$ /usr/local/bin/radian --version
radian version: 0.5.9
r executable: /Library/Frameworks/R.framework/Resources/bin/R
r version: 4.0.3
python executable: /usr/local/opt/python@3.9/bin/python3.9
python version: 3.9.1
```

I have macOS 11.1, though I don't think that it is the cause.

**Comment by randy3k** [comment]
`prompt_toolkit` is packaged manually in https://github.com/randy3k/lineedit

**Comment by klmr** [comment]
The plot thickens: vim mode apparently *still works*, but now requires hitting <kbd>Esc</kbd> *twice*. I’ve no idea what might be causing this.

**Comment by randy3k** [comment]
Oops, I see what is going on. There is a new setting `radian.emacs_bindings_in_vi_insert_mode` which has a default value of `True`. And unfortunately, turning it on will add a small timeout after `escape` is pressed because the setting added some keybindings of the from `escape + x`. Without the little timeout, those keybindings won't be possible.

**Comment by randy3k** [comment]
A workaround for you is to set `options(radian.emacs_bindings_in_vi_insert_mode = FALSE)`.

**Comment by klmr** [comment]
Thanks, that fixed it.
