### ISSUE TITLE
No graphing output with radian in VSCode while running in Remote-WSL

### ISSUE THREAD

**Issue by skazazes** [randy3k/radian#254]
I was wondering if anyone has run into issues with displaying plots and graphs when using radian within VSCode in conjuncture with Remote-WSL. Everything seems to work well as far as I can tell except for calls that invoke visualizations. When the same code is ran via radian and VSCode outside of Remote-WSL, a windows opens seamlessly displaying visualizations.

**Comment by randy3k** [comment]
I am not sure if it's vscode issue or radian issue.

**Comment by skazazes** [comment]
Understood, if there is any additional information I can provide to help find a solution please let me know, otherwise we can close the issue

**Comment by randy3k** [comment]
By the way, did you enable the live session feature in VSCode-R?

**Comment by skazazes** [comment]
I have moved off WSL for work in R and as such am closing the issue
