### ISSUE TITLE
radian should work with renv

### ISSUE THREAD

**Issue by mikekaminsky** [randy3k/radian#255]
It seems like this is a known issue as it's mentioned in the readme, but I couldn't find an issue related to using renv with radian so I figured I'd start one.

I have gotten into the habit of always using `renv` when I'm working on an R project (the same way I always use a `virtualenv` when working in python). It'd be great to be able to use radian with renv. 

If it's already possible, I'd love to know how! And if it's not, I'm curious as to why / what it would take to make them compatible.

**Comment by randy3k** [comment]
yes, radian does work with renv. What was mentioned in the README is that options related to radian should go to `.radian_profile` rather than the regular `.Rprofile`.

**Comment by mikekaminsky** [comment]
Hmm. Okay. Well in that case I may have a bug to report! I’m going to close this and will post an issue with more details if I figure out what the issue is.
