### ISSUE TITLE
Strange error when using rstan with radian

### ISSUE THREAD

**Issue by mikekaminsky** [randy3k/radian#256]
I'm getting a strange error when trying to run my tests via `radian`. These tests run fine when using the normal command-line `r`. 

Unfortunately, I'm not sure how to parse these errors -- something appears to be going wrong when compiling the Stan C++ code as called by [`rstan`](https://mc-stan.org/users/interfaces/rstan).

```
Error in compileCode(f, code, language = language, verbose = verbose) :
  Compilation ERROR, function(s)/method(s) not created! In file included from <built-in>:1:
In file included from /Users/michael/Library/Application Support/renv/cache/v5/R-3.6/x86_64-apple-darwin15.6.0/StanHeaders/2.19.2/41726c001c1cee4ce5869f648c64f013/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4:
In file included from /Users/michael/workspace/recast/recast/renv/library/R-3.6/x86_64-apple-darwin15.6.0/RcppEigen/include/Eigen/Dense:1:
In file included from /Users/michael/workspace/recast/recast/renv/library/R-3.6/x86_64-apple-darwin15.6.0/RcppEigen/include/Eigen/Core:535:
/Users/michael/workspace/recast/recast/renv/library/R-3.6/x86_64-apple-darwin15.6.0/RcppEigen/include/Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop
                             ^
In file included from <built-in>:1:
In file included from /Users/michael/Library/Application Support/
In addition: Warning messages:
1: An installation already exists at /Users/michael/.cmdstanr/cmdstan-2.24.1. Please remove or rename the installation folder or set overwrite=TRUE.
7: In system(cmd, intern = !verbose) :
  running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file24ab49bde9fe.cpp 2> file24ab49bde9fe.cpp.err.txt' had status 1 and error message 'Interrupted system call'
Error in sink(type = "output") : invalid connection
```

I'm unfortunately not sure where to start debugging this. If anyone has ideas for things to try / check, I'd be happy to give it a whirl. 

If this is low-priority, it's fine to just close this and ignore this issue, but I figured I'd file it in case there's something easily fixable here. 

Radian seems super cool, would love to be able to use it!

**Comment by randy3k** [comment]
I am not a rstan user, is the line
```
An installation already exists at /Users/michael/.cmdstanr/cmdstan-2.24.1. Please remove or rename the installation folder or set overwrite=TRUE.
```
related?

Perhaps trying a fresh installation of rstan?

**Comment by mikekaminsky** [comment]
I don’t believe that’s related as we get that warning when using normal r
(we call the install-Stan function at the beginning of every run so that it
installs if it’s not present, and it generates this warning).

I’ll try a fresh install just to check, though.

**Comment by randy3k** [comment]
I have just tested some [sample code](https://discourse.mc-stan.org/t/stan-compiling-error/6486) for rstan and it seems to be working flawlessly on my macOS.

It may have something to do with the `Makevars` file as mentioned in the thread?

**Comment by mikekaminsky** [comment]
Okay -- I am able to get this working on my other laptop, so am closing this for now. Will open up an issue with more details if I can track down what's causing that issue -- I suspect a fresh install will solve it.

Apologies for the noise! Looking forward to using Radian :)
