### ISSUE TITLE
table function problem

### ISSUE THREAD

**Issue by childrentime** [randy3k/radian#264]
The table function is used in radian If there is a Chinese in the data frame, the result will be garbled
`r$> tax.tab<-readr::read_csv("taxsamp.csv",locale=locale(encoding="Gb18030"))`
-- Column specification --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------cols(
 公司编号 = col_double(),
 日期 = col_character(),
 征收方式 = col_character(),
 申报渠道 = col_character(),
 营业额 = col_double()
)
`r$> print(head(tax.tab))`
\# A tibble: 6 x 5
 公司编号 日期      征收方式   申报渠道 营业额
   <dbl> <chr>      <chr>    <chr>   <dbl>
1   9913 2014/1/13 12:52 查帐征收   网上申报 36820 
2   9913 2014/1/14 15:49 查帐征收   网上申报 36820 
3   9913 2014/1/14 15:49 定期定率征收 网上申报 786902.
4   9913 2014/1/14 15:49 查帐征收   网上申报  105.
5   9913 2014/1/14 15:49 查帐征收   网上申报  105.
6   9913 2014/1/14 15:49 查帐征收   网上申报  105.
`r$> table(tax.tab[["征收方式"]])`
      \u67e5\u5e10\u5f81\u6536 \u5b9a\u671f\u5b9a\u989d\u5f81\u6536 \u5b9a\u671f\u5b9a\u7387\u5f81\u6536 
                 31                  16                  2
![image](https://user-images.githubusercontent.com/58261676/109772475-fe379380-7c38-11eb-8a62-7ad64e05ce0a.png)

**Comment by randy3k** [comment]
Did you figure it out?

**Comment by childrentime** [comment]
I think it's because  terminal  can't convert unicode characters to Chinese.
