### ISSUE TITLE
Add support for Windows UTF-8 version of R

### ISSUE THREAD

**Issue by SpecterShell** [randy3k/radian#269]
An experimental build of R using UTF-8 as native encoding on Windows has been released recently, and here is the instruction: [https://svn.r-project.org/R-dev-web/trunk/WindowsBuilds/winutf8/ucrt3/howto.html]()

I'm on Windows 10 20H2 and has set `$LANG` to `zh_CN.UTF-8`. After setting the codepage to 65001(UTF-8), the encoding in Rterm successfully switches to UTF-8, but the encoding in radian remains unchanged.

![image](https://user-images.githubusercontent.com/56779163/113680632-a7b7ec00-96f3-11eb-867e-857cf982b518.png)

In most of the time the terminal and the graph can still handle CJK characters properly. But sometimes some messy codes show, like the red text in the screenshot.

I thought this issue came from Python itself, so I set `$PYTHONUTF8` to `1` to force Python to use UTF-8, and ran `python -m radian` instead of `radian`. However it doesn't work for radian. I also tried to directly change the encoding in radian, and then it crashed.

**Comment by randy3k** [comment]
These are the relevant lines for decoding and encoding: https://github.com/randy3k/rchitect/blob/cb6e77c860ef180bd7f47416c94185fb9db04370/rchitect/utils.py#L142

Is there any prebuilt binary? The steps seem a bit involved.

**Comment by SpecterShell** [comment]
[https://www.r-project.org/nosvn/winutf8/ucrt3/](https://www.r-project.org/nosvn/winutf8/ucrt3/)
And `R-devel-win-80146-4517-4499.exe`(or newer) is the installer of the prebuilt binary.

I just found that running `demo(recursion)` can also reproduce the issue while R is waiting for user's response. So there is no need to prepare building environment. Just install and test.

**Comment by randy3k** [comment]
Does something like `Sys.setlocale(locale = "English_United States.utf8")` fix it?

**Comment by randy3k** [comment]
I have to set this
<img width="460" alt="Screen Shot 2021-04-06 at 2 51 47 PM" src="https://user-images.githubusercontent.com/1690993/113784024-84883f00-96e9-11eb-93b8-b31e52d7abcb.png">
to change the default locale of python applications.

But then, things are still not working well in `radian`:
```
r$> x = "床前明月光"

r$> print(x)
[1] "åºåææå"

r$> Sys.getlocale()
[1] "LC_COLLATE=English_United States.utf8;LC_CTYPE=English_United States.utf8;LC_MONETARY=English_United States.utf8;LC_NUMERIC=C;LC_TIME=English_United States.utf8"

r$> l10n_info()
$MBCS
[1] TRUE

$`UTF-8`
[1] TRUE

$`Latin-1`
[1] FALSE

$codepage
[1] 65001

$system.codepage
[1] 65001
```

**Comment by randy3k** [comment]
https://github.com/randy3k/rchitect/commit/7c0d72aa3fbb5c7dc42ff3ae43c2346bd0ce5a39 should fix the garbled text issue. However, it requires checking the beta UTF-8 setting in Region settings.

**Comment by randy3k** [comment]
There is some [discussion](https://discuss.python.org/t/pep-597-enable-utf-8-mode-by-default-on-windows/3122/20) on enabling UTF-8 codepage on Windows, but it won't happen soon. So for now,  the unicode setting in regional settings is the only way to enable UTF-8 on radian.

**Comment by SpecterShell** [comment]
In my opinion this issue occurs when radian calls R, system tends to use system-wide encoding settings instead of one set in the console, making R think that the current codepage is not UTF-8.
Setting the unicode setting may fix this problem by making all the applications use Unicode, but will make non-Unicode applications and even [system](https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8) corrupted.
Therefore, before there is a better way to solve this, I would use English as default in radian or rollback R to stable version.

**Comment by SpecterShell** [comment]
UTF-8 has become the default encoding now. 🤔
https://cran.r-project.org/bin/windows/base/NEWS.R-4.2.0.html

**Comment by SpecterShell** [comment]
The bare R term uses English by default utill the `LANG` is set. However, radian (or rchitect) always use system locale, resulting in garbled text.
A temporary workaround is to set `LANG` to `en_US.UTF-8` at startup.
![image](https://user-images.githubusercontent.com/56779163/165017103-a5053f40-8637-40e5-8683-4b4681789b27.png)

**Comment by randy3k** [comment]
I guess we'd need to force utf8 encoding for newer version of R.

**Comment by SpecterShell** [comment]
Works
![image](https://user-images.githubusercontent.com/56779163/166616749-bdfbf387-2ebe-4ac1-8681-48f448075a2b.png)

**Comment by randy3k** [comment]
Then the solution for us is simpler, we could just set it if it is unset.

**Comment by randy3k** [comment]
@SpecterShell 
Could you test if f016d462c3d99be0765507a8a9e71b4cd47a5d10 fixes it.

**Comment by SpecterShell** [comment]
Fixed now. Thank you for the fix!
![image](https://user-images.githubusercontent.com/56779163/166856796-ae772d67-cab3-4726-8f36-226d6fbb2429.png)

**Comment by randy3k** [comment]
Great, radian 0.6.2 is on the way.

**Comment by Yunuuuu** [comment]
Only set `LANG` environment is not sufficient to make this work well, I must set locale manually by adding following code in my   `.Rprofile`.
```
            # Set locale to utf8
            is_uft8_support <- grepl(
                "UTF-8|utf8", Sys.getenv("LANG"),
                ignore.case = TRUE, perl = TRUE
            ) &&
                R.version$major >= 4L &&
                R.version$minor >= 2.0
            if (is_uft8_support) {
                suppressWarnings(Sys.setlocale("LC_ALL", Sys.getenv("LANG")))
            }
```
This is my `radian` version:
![image](https://user-images.githubusercontent.com/19575010/176383691-fd4ff410-614f-4830-8358-f57d22ff73f3.png)

when use raw radian without setting above code in my `.Rprofile`, the R sessionInfo and l10n_info indicate `UTF-8` encoding isn't work. When we read file with special character using `data.table::fread`, some characters won't be parsed correctly 
![image](https://user-images.githubusercontent.com/19575010/176383903-65e98c03-3c65-4075-a257-eef16cc6ea61.png)
After setting `locale`, this works fine, and when we read file with special character using `data.table::fread`, special characters can be parsed successfully.
![image](https://user-images.githubusercontent.com/19575010/176384301-f1c9da51-bcd9-4119-8c14-d7fb02339dbc.png)

**Comment by Yunuuuu** [comment]
RStudio has setted appropriate `UTF-8` locale for R 4.2
![image](https://user-images.githubusercontent.com/19575010/176385240-c2c1408f-5367-493e-b25b-767d7a05b314.png)

**Comment by Kristie-Hu** [comment]
Where is the `.Rprofile` in vscode? I am new to R, and have little idea as to where to configure it... Thanks in advance!

**Comment by SpecterShell** [comment]
> Where is the `.Rprofile` in vscode? I am new to R, and have little idea as to where to configure it... Thanks in advance!

%USERPROFILE%\Documents\.Rprofile

**Comment by Kristie-Hu** [comment]
Hi @SpecterShell, the  `.Rprofile` didn't exist under my document folder although I have already made the hidden files visible.
However, I have found something quite smiliar to `.Rprofile`:

1. `Rprofile` under dir `R\R-4.2.1\library\base\R` 
2. `Rprofile.site` under dir `R\R-4.2.1\etc`

Is it possible to configure any of these to configure the UTF-8 as the global setting? Thanks!

**Comment by SpecterShell** [comment]
You can create one if it doesn't exist.

**Comment by Kristie-Hu** [comment]
> You can create one if it doesn't exist.

OK, thanks!

**Comment by Kristie-Hu** [comment]
I think perhaps the best solution for this is adding `Sys.setenv(LANG = "en_US.UTF-8")` directly to `.Rprofile`, and the garbled text will never appear again. Now everything just works fine in English. The Chinese translation is actually a bit misleading...

**Comment by kongdd** [comment]
After set the local by `Sys.setlocale("LC_ALL", "Chinese (Simplified)_China.utf8")`, get the following warnings when using `devtools::load_all()`
```R
There were 15 warnings (use warnings() to see them)

r$> warnings()
Warning messages:
1: In Sys.setlocale("LC_CTYPE", ctype) :
  using locale code page other than 936 may cause problems
```

**Comment by beansrowning** [comment]
Not sure if I'm in the right place here, but R.4.2 + radian seems to be entirely non-functional in my case. No changing of env vars seems to change that.

Radian fails on start:

System setup

```
radian --version
```
```
radian version: 0.6.4
r executable: C:\Users\<>\AppData\Local\Programs\R\R-4.2.1\bin\R
r version: 4.2.1
python executable: C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\python.exe
python version: 3.10.8
```

Stack trace
```
radian
```

```
Traceback (most recent call last):
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\Scripts\radian-script.py", line 33, in <module>
    sys.exit(load_entry_point('radian==0.6.4', 'console_scripts', 'radian')())
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\app.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\app.py", line 217, in run
    self.session = create_radian_prompt_session(options, settings)
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\prompt_session.py", line 153, in create_radian_prompt_session
    session = RadianPromptSession(
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\lineedit\prompt.py", line 72, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 473, in __init__
    self.default_buffer = self._create_default_buffer()
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\lineedit\prompt.py", line 163, in _create_default_buffer
    return ModalBuffer(
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\lineedit\buffer.py", line 185, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\lineedit\buffer.py", line 22, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\prompt_toolkit\buffer.py", line 313, in __init__
    self.reset(document=document)
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\lineedit\buffer.py", line 264, in reset
    self._reset_history()
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\lineedit\buffer.py", line 257, in _reset_history
    for m, item in self.history.load():
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\lineedit\history.py", line 9, in load
    self._loaded_strings = list(self.load_history_strings())
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\radian\lineedit\history.py", line 68, in load_history_strings
    backup = f.readlines()
  File "C:\Users\<>\.pyenv\pyenv-win\versions\3.10.8\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2546: character maps to <undefined>
```

**Comment by randy3k** [comment]
Good catch, we should make sure that the history file is in utf-8.

**Comment by psychelzh** [comment]
Any clue on why the first character of the package {targets} output is not as expect?

![image](https://user-images.githubusercontent.com/13306020/219030126-8a30c8f0-7bd4-4054-8571-686f4bb2509d.png)

Should be this instead:

![image](https://user-images.githubusercontent.com/13306020/219030279-b433f6c1-1a95-46a9-a4f1-1fc4e3a73a6a.png)

**Comment by kebuAAA** [comment]
where is the history file? I meet the same `UnicodeDecodeError` while this happens in the `radian/rutils.py`file
