### ISSUE TITLE
Does not start on M1 Macbook

### ISSUE THREAD

**Issue by nicebread** [randy3k/radian#271]
I installed successfully via
` pip3 install -U radian`

Starting from the console throws this error:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/radian/__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/opt/homebrew/lib/python3.9/site-packages/radian/radianapp.py", line 94, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/opt/homebrew/lib/python3.9/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 10): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Resources/lib/libR.dylib: mach-o, but wrong architecture
	/Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib: mach-o, but wrong architecture
```

Same with development version.

**Comment by randy3k** [comment]
You need to make sure that both python and R are in the same architecture.

**Comment by randy3k** [comment]
Let me elaborate. Most likely that the python from homebrew is naive (arm based), so you will need to install the arm based version of R: https://mac.r-project.org/

**Comment by nicebread** [comment]
Thanks, works now!

I had to (a) install the current dev version of arm R ("big-sur"; https://mac.r-project.org), and (b) install and enable the current python (e.g., https://opensource.com/article/19/5/python-3-default-mac).

**Comment by nicebread** [comment]
Add on: I realized that the arm version of R is not production-ready yet; the alternative is to install python and radian as intel-version (not the arm version).

**Comment by YiquanGu** [comment]
Hi I think have encountered a similar problem:

`  File "/opt/homebrew/anaconda3/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/radian/__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/radian/radianapp.py", line 94, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/opt/homebrew/Cellar/r/4.0.5/lib/R/lib/libR.dylib, 10): no suitable image found.  Did find:
        /opt/homebrew/Cellar/r/4.0.5/lib/R/lib/libR.dylib: mach-o, but wrong architecture
        /opt/homebrew/Cellar/r/4.0.5/lib/R/lib/libR.dylib: mach-o, but wrong architecture`

radian --version gives:
`radian version: 0.5.10
r executable: /opt/homebrew/Cellar/r/4.0.5/lib/R/bin/R
r version: 4.0.5
python executable: /opt/homebrew/anaconda3/bin/python
python version: 3.8.5`

Any suggestions of how to deal with problem of wrong architecture? At the moment both anaconda/python and R work just fine in their respective workflow. However,  I do wish to setup R (rmarkdown) in VS  code if possible.  Thanks.

**Comment by psobolewskiPhD** [comment]
R installed via homebrew should be arm native, unless you're not running native homebrew or running homebrew in a non-native shell/terminal.
If you just run R from the terminal, what does it report for Platform?

I think your issue may be with anaconda. Looks like the homebrew install is a cask (so from upstream) and I don't think anaconda supports arm (yet). I believe miniforge should work native:
https://github.com/conda-forge/miniforge

If you want to stick with your anaconda, then probably you need x86 R install, such as the default CRAN binary.

**Comment by YiquanGu** [comment]
@psobolewskiPhD thanks a lot for the comments! This all makes sense!

While running R in the terminal shows it's ARM64, within R studio which runs on intel architecture R.home() returns : "/Library/Frameworks/R.framework/Resources". 

I subsequently uninstalled r via homebrew but R studio still works and the installation with "/Library/Frameworks/R.framework/Resources" should be intact. 

Would `set R_HOME=/Library/Frameworks/R.framework/Resources` solve the problem? Don't wish to mess up the system if this only complicates things.  

Thanks.

**Comment by YiquanGu** [comment]
Hi all, the following step solved the issue:
Adding `export R_HOME=/Library/Frameworks/R.framework/Resources` to `.zshrc` which allows radian to find the version of R that is used by Rstudio. Hope this helps others who may have a similar problem. 
Thanks.

**Comment by psobolewskiPhD** [comment]
Great that you solved it. 
That path is for the standard CRAN R, used by RStudio. Both are x86 atm, so now R matches your anaconda environment architecture-wise.
You should be able to use pandoc, etc. all fine too as long as it's x86 (no arm version yet, as I mentioned above).
Basically, if everything is Rosetta emulated everything works. If everything is arm, it also works.
(e.g. in my case: native VSCode, native R, native radian).
Mixing though typically doesn't work.
