### ISSUE TITLE
Set shell executable

### ISSUE THREAD

**Issue by stefanocoretta** [randy3k/radian#274]
Hi! `radian` is really awesome, thanks for developing it!

Is there a way to set a different executable for the shell (the default is `sh` but I'd like to use `zsh` instead).

**Comment by randy3k** [comment]
It uses the environmental variable `SHELL` to determine which shell to use. Could you verify the variable is set correctly?

**Comment by stefanocoretta** [comment]
I tried this (perhaps I am doing it wrong) but still `sh`:

```bash
export SHELL="/usr/local/bin/zsh"
echo $SHELL
> /usr/local/bin/zsh
radian
```

**Comment by randy3k** [comment]
How do you check if it is zsh or sh?
