### ISSUE TITLE
Automatically save workspace

### ISSUE THREAD

**Issue by matrix-ranger** [randy3k/radian#275]
Hi, I enjoyed this tool a lot. But one problem here: You need to manually save a work space image every time before quitting especially when you are working with a large dataset and don't want to rerun all the commands, which I often forget. Is there an option to automatically save it like `--save` for `Rscript`?

**Comment by matrix-ranger** [comment]
I find `--restore-data` for my use but there is no `--save`, only `--ask-save` which is still a little annoying since I want to save every time.

**Comment by randy3k** [comment]
Done. Check out the master branch if you want to test it out.
