### ISSUE TITLE
Load full `reticulate` package when using `~` to enter python terminal

### ISSUE THREAD

**Issue by matrix-ranger** [randy3k/radian#276]
If you don't do that, you have no access to python variables from R after exiting the python terminal. However, if you load `library(reticulate)` and then `repl_python()`, you can use commands like `py$x` to get the variables created in the python terminal which is an important feature.

**Comment by randy3k** [comment]
IINM, I think you could still do `library(reticulate)` after exiting the python prompt.

**Comment by matrix-ranger** [comment]
Yes. Indeed! Thanks a lot.

**Comment by randy3k** [comment]
I am unsure about automatically running `library(reticulate)` when a user triggers `~`. I think it is better to keep it as is.
