### ISSUE TITLE
Unable to load shared object with latest R 4.1

### ISSUE THREAD

**Issue by mik3y64** [randy3k/radian#278]
Hello, I just fresh installed R 4.1 and spent 5 hours debugging this error but I have no clue at all. Please help. Thank you.

When loading packages such as Rcpp or devtools, I have no issue loading them and calling comamnds in raw `R` console but `radian` does not work. The shared object `.so` files are available as shown below. I have also tried reinstalliwng `miniconda` and `radian` and `R 4.1` from scratch and unfortunately same things happen again and again.

`R --version` gives
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"

`R`
`library(Rcpp)`
`Rcpp::evalCpp("100")`
[1] 100

`radian --version`
radian version: 0.5.7
r executable: /usr/lib64/R/bin/R
r version: 4.1.0
python executable: /opt/miniconda3/bin/python
python version: 3.8.5

`radian`
`library(Rcpp)`
Error: package or namespace load failed for ‘Rcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/mikey/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/libs/Rcpp.so':
  /opt/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/mikey/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/libs/Rcpp.so)
  

`ldd /home/mikey/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/libs/Rcpp.so | grep libstdc`
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fee25c1c000)

Same things happen for `devtools` and other packages

`R`
`library(devtools)`
Loading required package: usethis

`radian`
`library(devtools)`
Loading required package: usethis
Error: package or namespace load failed for ‘devtools’:
 .onLoad failed in loadNamespace() for 'pkgload', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/mikey/R/x86_64-pc-linux-gnu-library/4.1/testthat/libs/testthat.so':
  /opt/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/mikey/R/x86_64-pc-linux-gnu-library/4.1/testthat/libs/testthat.so)

`ldd /home/mikey/R/x86_64-pc-linux-gnu-library/4.1/testthat/libs/testthat.so | grep libstdc`
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fee25c1c000)

**Comment by mik3y64** [comment]
I use packages from `R 4.0` then it works

`rm -rf ~/R/x86_64-pc-linux-gnu-library/4.1`
`cp -r ~/R/x86_64-pc-linux-gnu-library/4.0 ~/R/x86_64-pc-linux-gnu-library/4.1`

`radian`
`library(Rcpp)`
Working

**Comment by randy3k** [comment]
Did you upgrade your gcc recently? It seems to me that the c runtime used by R 4.1 and minconda's python are different in your system. While R 4.1 uses glibc version 3.4.29, the version that miniconda provides is different.

Therefore a potential fix is upgrading the c runtime of miniconda or downgrading the c runtime of your system.

**Comment by randy3k** [comment]
Another solution is to install R via miniconda, it will make sure that R and radian uses the same c runtime.

**Comment by mik3y64** [comment]
Wow thank you for the swift response. I have no idea radian and R use different gcc. My OS knowledge is very bad. So thanks again for your help.

Yes yesterday I upgraded R4.1 and gcc together to avoid breaking things. But I 

Related `pacman.log`
upgraded r (4.0.5-4 -> 4.1.0-1)
upgraded gcc-libs (10.2.0-6 -> 11.1.0-1)
upgraded gcc (10.2.0-6 -> 11.1.0-1)
upgraded gcc-fortran (10.2.0-6 -> 11.1.0-1)

`pacman -Q | grep gcc`
gcc 11.1.0-1
gcc-fortran 11.1.0-1
gcc-libs 11.1.0-1

`conda list | grep gcc`
_libgcc_mutex             0.1                        main
libgcc-ng                 9.1.0                hdf63c60_0

Is `libgcc` used by conda the same thing as `gcc` used by R? here `libgcc-ng` has version `9.1.0` which is the latest available versions? What should I do now?


`conda search gcc`
Loading channels: done
No match found for: gcc. Search: *gcc*
```
# Name                       Version           Build  Channel
_libgcc_mutex                    0.1            main  pkgs/main
gcc-dbg_linux-64               7.2.0              19  pkgs/main
gcc-dbg_linux-64               7.2.0              24  pkgs/main
gcc-dbg_linux-64               7.2.0              25  pkgs/main
gcc-dbg_linux-64               7.3.0      h553295d_1  pkgs/main
gcc-dbg_linux-64               7.3.0      h553295d_2  pkgs/main
gcc-dbg_linux-64               7.3.0     h553295d_26  pkgs/main
gcc-dbg_linux-64               8.2.0      h218040c_1  pkgs/main
gcc-dbg_linux-64               8.2.0     h218040c_26  pkgs/main
gcc_bootstrap_linux-64           7.3.0     h64e4fec_15  pkgs/main
gcc_bootstrap_linux-64           7.3.0      h64e4fec_9  pkgs/main
gcc_impl_linux-64              5.4.0      habb00fd_3  pkgs/main
gcc_impl_linux-64              7.2.0      habb00fd_3  pkgs/main
gcc_impl_linux-64              7.2.0      hc5ce805_2  pkgs/main
gcc_impl_linux-64              7.3.0      habb00fd_0  pkgs/main
gcc_impl_linux-64              7.3.0      habb00fd_1  pkgs/main
gcc_linux-64                   5.4.0     h98af8de_24  pkgs/main
gcc_linux-64                   7.2.0              19  pkgs/main
gcc_linux-64                   7.2.0              24  pkgs/main
gcc_linux-64                   7.2.0              25  pkgs/main
gcc_linux-64                   7.2.0              26  pkgs/main
gcc_linux-64                   7.2.0     h196ecd4_10  pkgs/main
gcc_linux-64                   7.2.0     h217957b_13  pkgs/main
gcc_linux-64                   7.2.0      h22f992b_7  pkgs/main
gcc_linux-64                   7.2.0      h29fd5c9_3  pkgs/main
gcc_linux-64                   7.2.0     h4118e58_11  pkgs/main
gcc_linux-64                   7.2.0     h550dcbe_27  pkgs/main
gcc_linux-64                   7.2.0      h60973fd_9  pkgs/main
gcc_linux-64                   7.2.0      h6f34251_8  pkgs/main
gcc_linux-64                   7.2.0     haf1f6fa_15  pkgs/main
gcc_linux-64                   7.2.0      hc7b1ceb_1  pkgs/main
gcc_linux-64                   7.2.0     hd763dfe_12  pkgs/main
gcc_linux-64                   7.2.0      hecb3f9c_2  pkgs/main
gcc_linux-64                   7.2.0     hf1c97a4_14  pkgs/main
gcc_linux-64                   7.3.0      h553295d_1  pkgs/main
gcc_linux-64                   7.3.0     h553295d_15  pkgs/main
gcc_linux-64                   7.3.0      h553295d_2  pkgs/main
gcc_linux-64                   7.3.0      h553295d_3  pkgs/main
gcc_linux-64                   7.3.0      h553295d_6  pkgs/main
gcc_linux-64                   7.3.0      h553295d_7  pkgs/main
gcc_linux-64                   7.3.0      h553295d_8  pkgs/main
gcc_linux-64                   7.3.0      h553295d_9  pkgs/main
gcc_linux-64                   8.2.0      h218040c_2  pkgs/main
gcc_linux-64                   8.2.0      h218040c_3  pkgs/main
libgcc                         7.2.0      h69d50b8_2  pkgs/main
libgcc-ng                      5.4.0      hdf63c60_3  pkgs/main
libgcc-ng                      7.2.0      h7cc24e2_2  pkgs/main
libgcc-ng                      7.2.0      hcbc56d2_1  pkgs/main
libgcc-ng                      7.2.0      hdf63c60_3  pkgs/main
libgcc-ng                      7.3.0      hdf63c60_0  pkgs/main
libgcc-ng                      8.2.0      hdf63c60_0  pkgs/main
libgcc-ng                      8.2.0      hdf63c60_1  pkgs/main
libgcc-ng                      9.1.0      hdf63c60_0  pkgs/main
r-rgcca                        2.1.2   r36h6115d3f_0  pkgs/r
```

**Comment by mik3y64** [comment]
I only install conda for radian. Can I remove these from conda and radian would still run? Are these causing the issues?

`conda list | grep gcc`
_libgcc_mutex 0.1 main
libgcc-ng 9.1.0 hdf63c60_0

**Comment by randy3k** [comment]
Upgrading the compiling toolchain is usually a huge task as it will break things easily. I guess the easiest solution is to downgrade your system gcc to what it used to be.

**Comment by randy3k** [comment]
> I only install conda for radian. Can I remove these from conda and radian would still run? Are these causing the issues?
> 
> `conda list | grep gcc`
> _libgcc_mutex 0.1 main
> libgcc-ng 9.1.0 hdf63c60_0

Then I guess you could easier install python via pacman and install radian via pip.

**Comment by mik3y64** [comment]
> > I only install conda for radian.
> 
> Then I guess you could easily install python via pacman and install radian via pip (and keep the current version of gcc)

So you mean `rm -rf .../miniconda3` and use pip to install radian?

**Comment by randy3k** [comment]
Yap.

**Comment by randy3k** [comment]
Well, it is just a hacky way to upgrade the minconda c runtime. Not sure if there is a cleaner approach.

**Comment by 18kimn** [comment]
for future readers, if you would like to keep conda installed (I use it for a few projects), one solution is to just install radian with pip, outside of any conda environment:

```
# within a conda env
pip uninstall radian

# exit conda env
conda deactivate

pip install radian
library(tidyverse) # loads without error
```
