### ISSUE TITLE
Exit radian in Windows 10

### ISSUE THREAD

**Issue by conghuynhho** [randy3k/radian#279]
In the docs I see:  shell mode: hit ; to enter and <backspace> to leave
But I can't do this. Any help? 
Maybe this is a silly issue . Sorry about that

**Comment by randy3k** [comment]
Do you want to exit radian or the shell mode? Type quit() or ctrl-d to exit radian or type backspace to exit the shell mode.

**Comment by conghuynhho** [comment]
Yeah, it work when type quit(). Thank you so much
