### ISSUE TITLE
radian doesnt work with 4.1 arm version 

### ISSUE THREAD

**Issue by matthiaskaeding** [randy3k/radian#281]
Hi, 

thanks for the nice console!

When I use radian with the new arm 4.1 version of R I get:

`Exception: Cannot load shared library: dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 10): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Resources/lib/libR.dylib: mach-o, but wrong architecture
	/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libR.dylib: mach-o, but wrong architecture`

(tested on m1 macbook air m1, with macOS big sur 11.3.1)

I guess radian needs an update for that, just wanted to raise the issue.

Thanks

**Comment by randy3k** [comment]
You need to make sure that your python and R have the same arch, i.e. they are both intel based or both arm based.

**Comment by matthiaskaeding** [comment]
Thanks, I reinstalled python (which was not arm based before), that solved the issue.
