### ISSUE TITLE
Radian unable to load shared object but not RStudio

### ISSUE THREAD

**Issue by ShixiangWang** [randy3k/radian#285]
I tried to install the latest radian by `pip3 install -U radian` but see the same problem

```sh
▶ radian                
Using library: /Users/wsx/Library/R
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Platform: x86_64-apple-darwin17.0 (64-bit)

r$> devtools::document                                                                                                  
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/wsx/Library/R/ellipsis/libs/ellipsis.so':
  dlopen(/Users/wsx/Library/R/ellipsis/libs/ellipsis.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Referenced from: /Users/wsx/Library/R/ellipsis/libs/ellipsis.so
  Reason: image not found

```

This issue cannot be reproduced in RStudio

```R
Restarting R session...

Using library: /Users/wsx/Library/R
> devtools::document
function (pkg = ".", roclets = NULL, quiet = FALSE) 
{
    pkg <- as.package(pkg)
    if (!isTRUE(quiet)) {
        cli::cli_alert_info("Updating {.pkg {pkg$package}} documentation")
    }
    save_all()
    if (pkg$package == "roxygen2") {
        load_all(pkg$path, quiet = quiet)
    }
    if (quiet) {
        output <- file_temp()
        on.exit(file_delete(output))
        withr::local_output_sink(output)
    }
    withr::local_envvar(r_env_vars())
    roxygen2::roxygenise(pkg$path, roclets)
    pkgload::dev_topic_index_reset(pkg$package)
    invisible()
}
<bytecode: 0x7fede3a9bed0>
<environment: namespace:devtools>
```

**Comment by randy3k** [comment]
That’s strange. The shared objects in macOS usually have their rpath set correctly. What you saw is a common problem on Linux and there is already a workaround to fix it on Linux. 

There is a line: `Using library: /Users/wsx/Library/R`. Do you know what it is? It seems something is wrong with the library path.

**Comment by randy3k** [comment]
I figured it out. Your R is 4.1 while the library ellipsis is linked against 4.0. You cannot simply port your packages from 4.0 to 4.1. It will also cause issues in other places than radian.

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/120911956-dafc0480-c6bd-11eb-8ff7-c03601fa587c.png)

**Comment by ShixiangWang** [comment]
`Using library: /Users/wsx/Library/R` I set own library path for storing R packages.

**Comment by randy3k** [comment]
Porting packages across R versions is dangerous in the sense that the behaviour is undefined. I guess sooner of later you will have issues with some packages in plain R as well depends on how the packages were built.

**Comment by randy3k** [comment]
See this thread https://stackoverflow.com/questions/55929612/fail-to-load-libraries-after-upgrading-r-to-3-6-0-on-mac for some details.

**Comment by ShixiangWang** [comment]
Thanks for the reminder. I thought the packages should be compatible across R minor versions.
