### ISSUE TITLE
Not showing function definition and list component

### ISSUE THREAD

**Issue by EvoLandEco** [randy3k/radian#292]
In RStudio, `$` can be used to access list components:
![image](https://user-images.githubusercontent.com/57348932/124317588-b3427400-db77-11eb-9e68-491eb014b932.png)

And function definition is floating around:
![image](https://user-images.githubusercontent.com/57348932/124317670-d1a86f80-db77-11eb-9b03-c9d3b4c94392.png)

In VSCode + radian, they are not showing, is it a bug or just because radian currently doesn't have these features?

**Comment by randy3k** [comment]
I am quite sure that radian works in the first situation. The second one is outside of the scope of a terminal application.

**Comment by EvoLandEco** [comment]
I just tested again, in the first situation, list components didn't appear immediately after I typed `$` in, unless I continued to type in 2 more letters, and then there was only one matched auto-completion option, is this behavior normal? 
![image](https://user-images.githubusercontent.com/57348932/124319195-2baa3480-db7a-11eb-813c-d2759c59a101.png)

**Comment by randy3k** [comment]
You could hit the `tab` to trigger the items.

**Comment by EvoLandEco** [comment]
> You could hit the `tab` to trigger the items.

Good to know this linux-style trick. Thanks. Also, the second situation can also be achieved (mostly, without seeing the defaults) by hitting `tab`.
