### ISSUE TITLE
Exported functions not shown in completion

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#299]
Some base functions starting with `.` (e.g. `.mapply`) are not shown in the completion

![image](https://user-images.githubusercontent.com/4662568/127622972-81aaa32a-ddf3-46ca-a044-e27d7096e051.png)

**Comment by randy3k** [comment]
On mobile now. Could you check if base R does the same? We basically use the same mechanism as base R.

**Comment by renkun-ken** [comment]
Looks like the official R terminal has exactly the same behavior. Then it is probably a limitation of R's built-in completion functions.
