### ISSUE TITLE
Syntax Error when trying to install

### ISSUE THREAD

**Issue by jdawson554** [randy3k/radian#304]
```
c/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-eYe3tF/radian/
```
I'm getting the above error when I try to install using `pip install -U radian` on my Raspberry Pi 4b running the Raspberry Pi OS.

I'm very much a Linux and Raspberry Pi newbie, so any help would be greatly appreciated.

**Comment by randy3k** [comment]
What version of python is it?

**Comment by jdawson554** [comment]
I have both 2.7 and 3.7, but it looks like it's been using 2.7 - as a default maybe?

**Comment by jdawson554** [comment]
This is the complete output from the attempted install...

[radian-install.txt](https://github.com/randy3k/radian/files/6985010/radian-install.txt)

**Comment by randy3k** [comment]
Try a different version of setuptools-scm

```

pip install setuptools-scm==5.0.2

```

**Comment by jdawson554** [comment]
I finally got installed. After removing and re-installing various versions of Python, I eventually got it using `pip3 install -U radian`. Thanks for your help
