### ISSUE TITLE
Big Sur - M1 Mac - Radian not starting anymore

### ISSUE THREAD

**Issue by atze007** [randy3k/radian#305]
After installing 4.1.1 (2021-08-10, aarch64-apple-darwin20 (64-bit)) radian is not starting anymore... :-(

`radian`                                       
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/radian/__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/radian/radianapp.py", line 94, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 10): no suitable image found.  Did find:
        /Library/Frameworks/R.framework/Resources/lib/libR.dylib: mach-o, but wrong architecture
        /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libR.dylib: mach-o, but wrong architecture```

**Comment by psobolewskiPhD** [comment]
The error is an architecture mismatch, so either your R or your python or your Terminal is x86 and not arm64. How did you install python 3.9 and radian?
Your R appears arm64, butA are you able to launch the regular R console from the command line?

**Comment by atze007** [comment]
I installed python via brew. I think it should also be arm64. Is it possible to check this?

the normal R-Console ist starting without problems

**Comment by psobolewskiPhD** [comment]
Python from homebrew would be in /opt/homebrew...
what happens when you type:
`which python`
and `which python3`
You can use `lipo -info` on the returned path to get the architecture.

**Comment by atze007** [comment]
python
`Architectures in the fat file: /usr/bin/python are: x86_64 arm64e `
(so this could be the problem?)

python3
`Non-fat file: /opt/homebrew/bin/python3 is architecture: arm64`
(seems ok, right?)

i installed radian via `pip3 install -U radian`

**Comment by psobolewskiPhD** [comment]
Ok, your `python` is *fat* meaning both architectures. This should be fine—it's the Apple install I think.
Your homebrew `python3` is fine, although it doesn't appear to be used.
Which pip3 are you using? 
`which pip3` 
I guess system pip3 given that radian is in /Library/Frameworks... so it should be universal and also fine.
I just tested with a base conda env (don't want to mess up my system or other envs) and using conda pip3 (which is arm native) installed radian just fine with my native arm64 R.

Can you try running `lipo -info`
on /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libR.dylib

Maybe the R 4.1.1 isn't actually arm64, despite what it claims?
Can also look at the header when your run it from the terminal:
```
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: arm-apple-darwin20.5.0 (64-bit)
```
(yes, I'm super lazy and still on 4.0.3 that I installed in December).

**Comment by atze007** [comment]
Thanks already for the help ;-)

`which pip3` ->
```/opt/homebrew/bin/pip3```

`which radian` ->
```/opt/homebrew/bin/radian```

`lipo -info  /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libR.dylib` ->
```Non-fat file: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libR.dylib is architecture: arm64```

**Comment by psobolewskiPhD** [comment]
Hmm, all of that checks out.
I'm at a loss—and I thought I'd seen it all with this stuff! 
Your R is for sure arm64 and it's triggering the architecture issue, so it has to somehow be the python side?
Can you try:
`radian -v`
That will tell us what executables it's looking for...

**Comment by atze007** [comment]
```radian version: 0.5.11
r executable: /Library/Frameworks/R.framework/Resources/bin/R
r version: 4.1.1
python executable: /opt/homebrew/opt/python@3.9/bin/python3.9
python version: 3.9.6```

**Comment by psobolewskiPhD** [comment]
That's all correct...
The R executable is the one you checked to be arm64.
Strangely, the error in the OP doesn't refer to /opt/homebrew/...
but /Library/Frameworks/

Can you try to list this dir:
`ls -al  /opt/homebrew/lib/python3.9/site-packages`
This should be where homebrew pip3 installs stuff.
Presumably `radian` and `rchitect` should be there.

**Comment by atze007** [comment]
```
drwxr-xr-x  18 pelz  admin     576 16 Aug 14:23 radian
drwxr-xr-x  10 pelz  admin     320 16 Aug 14:23 radian-0.5.11.dist-info
drwxr-xr-x  18 pelz  admin     576 16 Aug 14:23 rchitect
drwxr-xr-x   8 pelz  admin     256 16 Aug 14:23 rchitect-0.3.32.dist-info
```

**Comment by psobolewskiPhD** [comment]
🤯 
Everything.is.correct.
Why.doesn't.it.work?

**Comment by psobolewskiPhD** [comment]
Is that listing all that you have in `site-packages`? I'd expect a bit more since radian has some dependencies.
Maybe try to reinstall radian? and force no binaries.
`pip uninstall radian`
`pip install --no-binary :all: radian`

**Comment by atze007** [comment]
There were a lot more listings in the `site-packages`.

But the `pip uninstall radian` and `pip install --no-binary :all: radian` worked! 

Radian is working again :)
Thanks again for the help :)
