### ISSUE TITLE
Lag time between an output and next input

### ISSUE THREAD

**Issue by Fred-Wu** [randy3k/radian#306]
When there is a large `list` in the VSCode-R's workspace, there is always a significant lag time between an output and for next input in the `radian` terminal. Once it happens, it also affects small objects too, things like to print `a=1`.   It takes about 1 second to show the next `r$>` after 1 gets printed. 

```
r$> a
[1] 1

r$>
```
Once the `list` is removed, everything gets back to normal. 

Here are some sample codes I borrowed from a `stackoverflow` question for other things, that you could use to reproduce the issue. 

```
product_ids <- as.vector(
    outer(LETTERS[seq(1, 26, 1)],
        outer(outer(LETTERS[seq(1, 26, 1)], LETTERS[seq(1, 26, 1)], paste, sep = ""),
            LETTERS[seq(1, 26, 1)], paste,
            sep = ""
        ), paste,
        sep = ""
    )
)

test_lookup_list <- lapply(product_ids, function(id) {
    return_list <- list(
        product_id = id,
        val_1 = rnorm(1),
        val_2 = rnorm(1),
        val_3 = rnorm(1),
        val_4 = rnorm(1),
        val_5 = rnorm(1),
        val_6 = rnorm(1),
        val_7 = rnorm(1),
        val_8 = rnorm(1)
    )
    return(return_list)
})
```

**Comment by renkun-ken** [comment]
This has nothing to do with radian but the vscode-R session watcher task callback (https://github.com/REditorSupport/vscode-R/issues/174). It has been resolved by https://github.com/REditorSupport/vscode-R/pull/778. You might want to try the [latest development build](https://github.com/REditorSupport/vscode-R/releases/tag/latest) and see if it works for you.

If you have further issues, please add your comments to https://github.com/REditorSupport/vscode-R/issues/174.

**Comment by Fred-Wu** [comment]
Thanks for the quick reply. I will close the issue here.
