### ISSUE TITLE
`radian` arm64 + R `x86_64`

### ISSUE THREAD

**Issue by pat-s** [randy3k/radian#327]
I am playing around in switching between `x86_64` and `arm64` R installations on a M1 machine and try to get them working with `radian`.

I have installed R `x86_64` and `arm64` side-by-side (yes, I know what I am doing :) ).
While both can be launched via `R` just fine and package installation works (🎉️), I can only get the R `arm64` to work with `radian`.

When trying to combine it with R `x86_64` I get

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/radian/__init__.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/opt/homebrew/lib/python3.9/site-packages/radian/radianapp.py", line 96, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/opt/homebrew/lib/python3.9/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 0x000A): tried: '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file)
```

To me this looks like that `radian` expects `libR.dylib` to be of `arm64e` arch but it finds the `x86_64` one (because R `x86_64` is active).
For R `x86_64` to run successfully, it is required that `libR.dylib` is of `x86_64` arch.

Is this something `radian` could account for? Or is the issue somewhere else and I can workaround this? Would it work if I would use `radian` installed with `x86_64`  arch?

**Comment by randy3k** [comment]
You would need to install the compatible arch of Python to run radian.

**Comment by pat-s** [comment]
Thanks for the quick reply! That's what I suspected a bit. 

Then I'll note this and go on with using `radian` only for `arm64` R :)
