### ISSUE TITLE
VS Code R radian integrated terminal displays "Window too small..."

### ISSUE THREAD

**Issue by marcelo-caetano** [randy3k/radian#329]
Hi Randy,
First of all, thanks for the radian R terminal project. I created a virtual environment for R with conda and I am working on it with VS Code. I installed the R extension by Yuki Ueda and all the recommended extensions and packages, including radian. Everything was working fine until yesterday, when this weird behavior appeared. I activated the conda environment, launched code inside the workspace, and created an R terminal (running radian inside the integrated terminal) as usual. However, I only see the message below and naturally radian is unusable
![radian_bug](https://user-images.githubusercontent.com/9254896/145329261-43ea9a39-f1a9-455f-a043-44d039187e26.png)
If I configure VC Code to use the regular R terminal, everything works fine. If I launch radian from bash outside of VS Code, it also works fine (as show below)
![radian_bash](https://user-images.githubusercontent.com/9254896/145329523-4d473be4-0c6c-46f8-aea4-98652f27afe6.png)
I cloned the radian repo and did a quick search for keywords in the cryptic error message in the codebase for radian, but the message seems to come from somewhere else. So now I need help. Any troubleshooting ideas? Any fixes?

**Comment by randy3k** [comment]
You'll need to resize your terminal to make it longer. The error is from [prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit).

**Comment by marcelo-caetano** [comment]
How embarrassing, resizing the terminal window did the trick. Interestingly, making the terminal wider had no effect. Making it taller did, as illustrated below. Thanks for the help, Randy
![radian_wide_err](https://user-images.githubusercontent.com/9254896/145441293-eed04f0d-053e-4d17-a5d2-65f1fb150ea9.png)
![radian_wide](https://user-images.githubusercontent.com/9254896/145441320-7de3e9fb-ee03-4a4d-9a0a-94f7fdef7515.png)
![radian_narrow](https://user-images.githubusercontent.com/9254896/145441343-08440ea7-c8fa-4cf6-b4a5-922e317a01a1.png)
