### ISSUE TITLE
Not working on macOS 12.0.1

### ISSUE THREAD

**Issue by stefanocoretta** [randy3k/radian#331]
Hi! I successfully installed radian on macOS 12.0.1, but when I run it I get this error:

```
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/bin/radian", line 33, in <module>
    sys.exit(load_entry_point('radian==0.6.0.dev0', 'console_scripts', 'radian')())
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/radian-0.6.0.dev0-py3.9.egg/radian/app.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/radian-0.6.0.dev0-py3.9.egg/radian/app.py", line 205, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/rchitect-0.3.34-py3.9-macosx-10.9-x86_64.egg/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib, 0x000A): tried: '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file)
```

It's weird because everything has been built for arm.

My specs:

- macOS 12.0.1 M1
- R version 4.1.2 (2021-11-01) aarch64-apple-darwin20.6.0 (64-bit), (homebrew)
- anaconda (homebrew)

**Comment by psobolewskiPhD** [comment]
Looks like your conda environment is x86 while your R is arm64. 
You can't mix architectures.
`anaconda` is still just x86, so it runs in emulation.

Your options are to use miniforge3 as your arm64 conda env:
https://github.com/conda-forge/miniforge
And then you can install arm64 radian, etc.

Or you can use homebrew to install native arm64 python/pip and then radian etc.

Alternately, you can install x86 R from CRAN and then it will work in emulation with your emulated anaconda python environment.

**Comment by stefanocoretta** [comment]
Hi, thanks! Funny enough I just noticed that anaconda is x86 only... which explains the issue, as per your answer. I uninstalled anaconda and installed miniforge and now radian runs fine.
