### ISSUE TITLE
Change font for radian?

### ISSUE THREAD

**Issue by kalaschnik** [randy3k/radian#344]
radian uses the font I set up in my Terminal: i.e., MesloLGS. This font plays nicely with zsh/ohmyzsh and theming:

<p align="center">
<img width="473" alt="image" src="https://user-images.githubusercontent.com/9831678/156439273-de934cc8-7ea3-4cb3-88d9-34d630a6dd96.png">
</p>

Yet, for coding I prefer Fira Code which provides nice font ligature making the code look more "natural", and since the native pipe has arrived in R, we have a nice ligature for that too:

<p align="center">
<img width="380" alt="image" src="https://user-images.githubusercontent.com/9831678/156441088-cc84d184-4052-4e91-8bee-d57809bea742.png">
</p>

It would be great if there would be an option to allow overriding the Terminal font (and font size). As I don’t want to give up MesloLGS for "normal" terminal work, but would love to have Fira Code as soon as radian starts in the terminal. Here is a screenshot that shows Fira Coda at the top and Meslo at the bottom terminal:

<p align="center">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/9831678/156441781-510ef845-1a4b-43f6-ac9a-fcef1fcc2ed8.png">
</p>

So, Fira Code in the Editor and radian would be great!

**Comment by a-hurst** [comment]
@kalaschnik I also have different preferences for regular terminal usage and R sessions, so what I've been doing for years is use iTerm 2 for R/radian and Apple's Terminal.app for everything else. Not sure how well that lines up with your specific workflow, but it's worth trying!

**Comment by randy3k** [comment]
radian does not control font or even font sizes. Please raise an issue to vscode-R in your case.
