### ISSUE TITLE
Error starting radian

### ISSUE THREAD

**Issue by yannikbuhl** [randy3k/radian#348]
Dear Randy,

after a couple of hours trying to solve this error I don't know what to do anymore, so that's why I unfortunately have to open up an issue, hoping you can help me fix this. After installing radian on Windows 11 using pip I encounter the following error:

`Traceback (most recent call last):`
`  File "d:\programme\python\lib\runpy.py", line 196, in _run_module_as_main`
`    return _run_code(code, main_globals, None,`
`  File "d:\programme\python\lib\runpy.py", line 86, in _run_code`
`    exec(code, run_globals)`
`  File "D:\Programme\Python\Scripts\radian.exe\__main__.py", line 7, in <module>`
`  File "d:\programme\python\lib\site-packages\radian\app.py", line 108, in main`
`    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)`
`  File "d:\programme\python\lib\site-packages\radian\app.py", line 215, in run`
`    self.session = create_radian_prompt_session(options, settings)`
`  File "d:\programme\python\lib\site-packages\radian\prompt_session.py", line 152, in create_radian_prompt_session`
`    session = RadianPromptSession(`
`  File "d:\programme\python\lib\site-packages\radian\lineedit\prompt.py", line 72, in __init__`
`    super().__init__(*args, **kwargs)`
`  File "d:\programme\python\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 463, in __init__`
`    self.default_buffer = self._create_default_buffer()`
`  File "d:\programme\python\lib\site-packages\radian\lineedit\prompt.py", line 163, in _create_default_buffer`
`    return ModalBuffer(`
`  File "d:\programme\python\lib\site-packages\radian\lineedit\buffer.py", line 185, in __init__`
`    super().__init__(*args, **kwargs)`
`  File "d:\programme\python\lib\site-packages\radian\lineedit\buffer.py", line 22, in __init__`
`    super().__init__(*args, **kwargs)`
`  File "d:\programme\python\lib\site-packages\prompt_toolkit\buffer.py", line 316, in __init__`
`    self.history.load(new_history_item)`
`TypeError: ModelHistory.load() takes 1 positional argument but 2 were given`

For your information, this is what `radian --version` gives me:

`radian version: 0.6.0`
`r executable: D:\Programme\R\R-4.1.3\bin\R`
`r version: 4.1.3`
`python executable: d:\programme\python\python.exe`
`python version: 3.10.4`

Thank you so much in advance!

**Comment by randy3k** [comment]
See https://github.com/randy3k/radian/issues/345

It seems that your `prompt-toolkit` was not updated.

**Comment by yannikbuhl** [comment]
Is there a way to forcibly update it correctly? I have removed and reinstalled Python and radian multiple times already to try and fix the issue.

**Comment by yannikbuhl** [comment]
That actually solved my issue right away.

**Comment by randy3k** [comment]
Looks like we need at least prompt-toolkit 3.0.15. The dependency requirement has been updated and a new version of radian is being tagged.
