### ISSUE TITLE
Is file editing mode emacs or vim?

### ISSUE THREAD

**Issue by Fred-Wu** [randy3k/radian#351]
I never used emacs or vim previously, so this question might be naive. 

With RStudio, I usually edit files with `file.edit`, which opens a text file editor.  So I tried to use this function with Radian as well. 

From the description, the default editing mode is supposed to be emacs. However, the keybindings working for emacs do not seem to work in the emac editing mode. I also get the following message, which suggests Vim

```
Type  :qa!  and press <Enter> to abandon all changes and exit Vim
```
Therefore, does file editing mode with emacs or vi also correspond to their usual keybindings?

**Comment by randy3k** [comment]
radian editing mode is not related to the editor that you use while running `edit`. You could change your default editor by changing the `EDITOR` option in R.
