### ISSUE TITLE
getOption("askpass") in radian returns a Python object instead of NULL

### ISSUE THREAD

**Issue by duccioa** [randy3k/radian#359]
In the R console:

```
getOption("askpass")
> NULL
```

In radian:

```
askpass = getOption("askpass")
askpass("pwd: ")
# type 123 
> pwd: *** 
> <pointer: 0x7f6d2fd8d540>
> attr(,"class")
> [1] "PyObject"
> attr(,"convert")
> [1] FALSE

```

So the function in the option "askpass" returns a pointer to a Python object instead of the character with the input string. 
This, for example, makes {keyring} fail because it uses {askpass} which calls `getOption("askpass", askpass_default_function)`, expecting NULL or a function that returns a character.

**Comment by randy3k** [comment]
It's fixed in the master branch.
