### ISSUE TITLE
Cannot type the "±" symbol in Radian on Windows platforms.

### ISSUE THREAD

**Issue by yanpd01** [randy3k/radian#360]
## operating environment 
```
radian version: 0.6.2
r executable: C:\R\R-4.2.0\bin\R
r version: 4.2.0
python executable: C:\Users\cuilab\AppData\Local\Programs\Python\Python310\python.exe
python version: 3.10.4
windows 10 21H2: 19044.1645
system language: Chinese (People's Republic of China)
```
## problem description
Whether running radian in CMD or Powershell, or directly opening radian.exe, I cannot type "±". Even the URLdecode("%C2%B1") function doesn't print "±" correctly, but everything looks fine in Linux. 

## screenshots
![001](https://user-images.githubusercontent.com/69427931/167887966-202f7304-c28e-4cc5-a6ae-a47ce1976486.png)

**Comment by randy3k** [comment]
what does `Sys.getenv("LANG")` return?

**Comment by yanpd01** [comment]
> what does `Sys.getenv("LANG")` return?

Enter Sys.getenv("LANG"), it will be displayed as "en_US.UTF-8" in radian and "" in the R console. When I set Sys.setenv(LANG="") in radial, I still can't type and print ±. But everything works fine in the R console.

**Comment by randy3k** [comment]
The workaround of setting `LANG` was inspired by https://github.com/randy3k/radian/issues/269#issuecomment-1118113471

@SpecterShell
Could you reproduce the same bug here?

**Comment by SpecterShell** [comment]
The same here, but may not relate to that change. 🧐

Default GB2312 (936) in console, GB2312 (936) in radian
![image](https://user-images.githubusercontent.com/56779163/167978850-e3b820d8-3295-4799-94e6-c0cb329accca.png)

Set UTF8 (65001) in console, GB2312 (936) in radian
![image](https://user-images.githubusercontent.com/56779163/167978962-e0a17e7a-a3ba-40db-a20f-f1fd0181a377.png)

Default GB2312 encoding (936) in console, UTF-8 (65001) in R
![image](https://user-images.githubusercontent.com/56779163/167979273-ffc48dc3-98ea-4e96-8280-b603fc833bfd.png)

**Comment by yanpd01** [comment]
When I run `Sys.setlocale(locale ="Chinese (Simplified)_China.UTF-8")`, I can type and print "±" normally. But running this code throws a warning, will this affect other operations?


![002](https://user-images.githubusercontent.com/69427931/167982536-7416585e-d082-42ff-8298-c6cb4fd2ea3d.jpg)

**Comment by randy3k** [comment]
Indeed, it is a locale related stuff. Python on Windows doesn't support UTF-8 as default codepage, so it inherits the system locale, which is simplified chinese in your case.

I think it should be safe to ignore the warning in this case as R 4.2 indeed does support UTF-8 codepage.

**Comment by yanpd01** [comment]
I am going to write `Sys.setlocale(locale ="Chinese (Simplified)_China.UTF-8")`  into the .Rprofile file, in order to use the radian better.
Thanks for your answer.
