### ISSUE TITLE
64-bit R and python on M1- won't load

### ISSUE THREAD

**Issue by spacefurll** [randy3k/radian#369]
I need to use x86 R on a M1 machine because a specific R package isn't developed for arm-64. I installed x86 R and python with x86 conda. Both work well on this machine. However, starting radian results in the error:

```
Traceback (most recent call last):
  File "/Users/rk2643/miniconda3/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/Users/rk2643/miniconda3/lib/python3.9/site-packages/radian/app.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "/Users/rk2643/miniconda3/lib/python3.9/site-packages/radian/app.py", line 205, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/Users/rk2643/miniconda3/lib/python3.9/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 0x000A): tried: '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
(base) 
```

radian --version gives me:

```
$ radian --version
radian version: 0.6.3
r executable: /Library/Frameworks/R.framework/Resources/bin/R
r version: 4.2.0
python executable: /Users/rk2643/miniconda3/bin/python
python version: 3.9.12
(base) 
```

The architecture of R and python match, but radian seems to really want the ARM architecture.

**Comment by psobolewskiPhD** [comment]
Do you have another radian installed somewhere? Is it possible a cached version was used?
Alternately you can force x86 using: `arch -x86_64 pip install .....`

**Comment by spacefurll** [comment]
I don't have any other instances of radian installed, no cached version. 

It actually looks like I'm having a bigger issue than radian because uninstalling and using: `arch -x86_64 pip install .....` 
results in an M1/rosetta specific error: `arch: posix_spawnp: pip: Bad CPU type in executable` even though Rosetta is installed and updated.

**Comment by psobolewskiPhD** [comment]
Sounds like your conda env or pip isn't x86?
Maybe try `conda info` in your env?

**Comment by spacefurll** [comment]
You are right! The conda is an x86 install but pip (installed by conda) isn't. The arch test worked great though! I'll try reinstalling and see.

**Comment by psobolewskiPhD** [comment]
Wow, pretty interesting env you have there then 🤣 
Not sure how an x86 conda env has arm64 pip...

**Comment by spacefurll** [comment]
I don't know how this happened either! All fresh installs and everything...

The answer was to create an x86 specific conda environment :

`CONDA_SUBDIR=osx-64 conda create -n myenv_x86 python=3.9'

And then installing radian, which now works perfectly. :) Thanks for your help! I checked x86 for everything except pip lol

**Comment by psobolewskiPhD** [comment]
AH, my B then, I thought you had that based on the OP.
