### ISSUE TITLE
not able to start radian

### ISSUE THREAD

**Issue by ettislink** [randy3k/radian#380]
Hello

following situation:
OS: Windows 10
Python: version 3.10.6 (64-bit)
Successfully installed radian-0.6.3

When I try to start radian by just entering the word radian in Windows PowerShell I get:

Traceback (most recent call last):
  File "D:\Python\Python310\Scripts\radian-script.py", line 33, in <module>
    sys.exit(load_entry_point('radian==0.6.3', 'console_scripts', 'radian')())
  File "D:\Python\Python310\lib\site-packages\radian\app.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "D:\Python\Python310\lib\site-packages\radian\app.py", line 205, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "D:\Python\Python310\lib\site-packages\rchitect\setup.py", line 51, in init
    raise Exception(load_symbol_error())
Exception: Cannot load symbol CDDDR: Die angegebene Prozedur wurde nicht gefunden.

Last phrase in english reads "The indicated procedure has not been found."
Any idea what is wrong with the installation? Thanks in advance for any hint ...

Stefan

**Comment by randy3k** [comment]
What version of R is it? It is strange that the symbol `CDDDR` is not found.

**Comment by ettislink** [comment]
Thanks a lot for your comment! I have several R-Versions parallely installed: 3.1.0, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.6.0, 3.6.3, 4.0.0, 4.1.0
Could this be the reason? I mean this diversity of installed R-version such that radian is overcharged in some sense ?

**Comment by randy3k** [comment]
radian only works with R >= 3.4.0.

**Comment by ettislink** [comment]
Yes; this is it ... I uninstalled R 3.1.0, R 3.2.0 and R 3.3.0 and afterwards radiant started with R 3.4.0
Thanks a lot for pointing to that condition.
