### ISSUE TITLE
How  to run an R script from the shell using radian?

### ISSUE THREAD

**Issue by GBuchanon** [randy3k/radian#386]
I can not find a way to run an R script from the shell but using the radian console.  Basically I am looking for the radian equivalent of ```Rscript ./myscript.R``` or ```Rscript -e 'source(".myscript.R", echo=TRUE)'```.  Does such a thing exist?

**Comment by randy3k** [comment]
Radian is for interactive usage.  
Please use Rscript for running R scripts.

**Comment by GBuchanon** [comment]
Okay. I would have found the coloured output that radian provides useful.
