### ISSUE TITLE
Error loading packages that use shared .so files

### ISSUE THREAD

**Issue by tarensanders** [randy3k/radian#395]
### Setup
I'm running radian on Ubuntu (via WSL from Windows). I'm setting up a new install, and it has been working fine until now. I'm using R version 4.2.2, and my `radian --version` looks like:

```
radian version: 0.6.4
r executable: /usr/lib/R/bin/R
r version: 4.2.2
python executable: /home/taren/miniconda3/bin/python
python version: 3.9.15
```

### Problem
When I try to load `{vroom}`, I get the following error:

```
Error: package or namespace load failed for ‘vroom’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/taren/R/x86_64-pc-linux-gnu-library/4.2/vroom/libs/vroom.so':
  /home/taren/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/taren/R/x86_64-pc-linux-gnu-library/4.2/vroom/libs/vroom.so)
```

I assume this would be a similar problem for any package that uses a shared .so file.

If I use a regular R terminal, I don't have this issue.

### Troubleshooting

I've tried:

* A clean reinstall of miniconda, and downgrading from Python 3.10 to 3.9.
* Checking that "GLIBCXX_3.4.30" exists. 
    * I've tried reinstalling (`sudo apt-get install libstdc++6`)
    * I've checked that it's on the system (`strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX`)
* A total uninstall and reinstall of R

Any suggestions? I've not tried install R from conda (because I would really like to avoid that).

**Comment by randy3k** [comment]
Sorry for the late reply. Generally, it is recommanded to use R and python from the same ecosysytem. If you are using conda, it is better for you to install R from conda, it ensures that they have the same C runtime.

**Comment by tarensanders** [comment]
Thanks, Randy. Can confirm that reinstalling radian using the version of python that comes with Ubuntu solves this problem.
