### ISSUE TITLE
Cannot load shared library issue

### ISSUE THREAD

**Issue by chenhuiapp** [randy3k/radian#418]
I am trying to use Radian on a remove Hoffman machine. 

After I installed Radian, I encountered the following error.

Traceback (most recent call last):
  File "\~/.local/bin/radian", line 8, in <module>
    sys.exit(main())
  File "\~/.local/lib/python3.10/site-packages/radian/app.py", line 109, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "\~/.local/lib/python3.10/site-packages/radian/app.py", line 206, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "\~/.local/lib/python3.10/site-packages/rchitect/setup.py", line 50, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: /u/local/apps/R/4.2.2/gcc-4.8.5/intel-2020.4/lib/libR.so: cannot open shared object file: No such file or directory

I have contacted my hoffman cluster technical team, and they told me that the shared library is located at another location which is

/u/local/apps/R/4.2.2/gcc-4.8.5/intel-2020.4/**lib64/R**/lib/libR.so

instead of

/u/local/apps/R/4.2.2/gcc-4.8.5/intel-2020.4/lib/libR.so

Is there a way that I can update this directory?

**Comment by danielduyvo** [comment]
Running `export R_HOME=/u/local/apps/R/4.2.2/gcc-4.8.5/intel-2020.4/lib64/R` should point radian to the right folder to look for the shared library.
