### ISSUE TITLE
How to enter new line in a multiline script?

### ISSUE THREAD

**Issue by rrodrigueznt** [randy3k/radian#422]
Hi! I'm using radian in Ubuntu 22.04.2 running under Termux, Android 13. R 4.2.0. jedi 0.18.2.

Is it expected that I can enter new lines when editing scripts in the console? I can only enter new lines if I hit enter between {}. If I hit Enter, Shift+Enter or Ctrl+Shift+Enter in any other position of the code, submit the code bunch.

Thanks!

**Comment by randy3k** [comment]
Esc + enter. Or alt enter if you have mapped alt to escape.
