### ISSUE TITLE
problem of colorscheme

### ISSUE THREAD

**Issue by kaji331** [randy3k/radian#45]
From 0.0.41, the colorscheme was changed. When I used gnome-terminal and light solarized colorscheme, the color of editing text was too light to be read. I have to use dark colorscheme or version 0.0.40.

**Comment by randy3k** [comment]
Did you try v0.1.2? It is not the change of the color scheme, but the way prompt-toolkit handles colors.

Please try v0.1.2 to see if it performs better. However, you always have to choice to switch to a different scheme.

**Comment by kaji331** [comment]
Sorry, I find where the problem is. When I test my code, I like to use r --vanilla. It won't load .Rprofile, so the colorscheme option is useless. The default colorscheme is not suitable for my terminal colorscheme.

**Comment by kaji331** [comment]
In 0.0.40, native colorscheme could be used in solarized light colorscheme in terminal. After that, native colorscheme only can be used in a dark terminal colorscheme, even in the latest version of rtichoke.

**Comment by kaji331** [comment]
I don't understand your code. It seems that you change the method to handle default pygments style. Maybe that's why default colorscheme can't be suitable for light background.

**Comment by kaji331** [comment]
from 0.0.41

**Comment by matteodefelice** [comment]
I have just installed radian (0.4.0) but with a terminal with light colors is impossible to read anything. I have tried typing: `options(radian.color_scheme = 'native')` but nothing changes.

**Comment by randy3k** [comment]
@matteodefelice 
You will need to specify it in the `.Rprofile`.

**Comment by kaji331** [comment]
@randy3k @matteodefelice We have to set the color scheme in .Rprofile. If sometimes I wanna use radian with --vanilla parameter, I have to accept the very light colors of default scheme, especially in a light background terminal. Sad!

**Comment by randy3k** [comment]
ok, I see that could be an issue. What do you think about an radian specific settings file?

**Comment by kaji331** [comment]
> ok, I see that could be an issue. What do you think about an radian specific settings file?

I think it's a great choice, e.g. .radian_profile. When the radian starts, it will load .radian_profile first and then check .Rprofile. If the .Rprofile have the same option for radian, it will cover the option in .radian_profile.

**Comment by randy3k** [comment]
added support of .radian_profile 65c51c61ae545595cf3b7eafefa9e5878f12d86c

I will make a release very soon.

**Comment by randy3k** [comment]
However, the order of execution is different. .Rprofile is first loaded and then the `.radian_profile`.
