### ISSUE TITLE
Cannot handle `\b` correctly in version 0.6.10

### ISSUE THREAD

**Issue by psychelzh** [randy3k/radian#463]
For example `targets::tar_make()` will show waiting status as a rotating stick, but it prints many lines! 

![image](https://github.com/randy3k/radian/assets/13306020/6c339d41-2c38-45fb-8613-aee9faa0e288)

**Comment by psychelzh** [comment]
Currently tried 0.6.9, works perfectly:

![image](https://github.com/randy3k/radian/assets/13306020/92054609-69e7-4e38-8fb5-46748a5f03b9)

**Comment by randy3k** [comment]
Sorry for the issue. It should be fixed by [3a75a1e](https://github.com/randy3k/radian/commit/3a75a1e4c047fc86342fdcee5765e23cf5a5fdd6).

**Comment by randy3k** [comment]
0.6.11 is tagged, will be published to pypi.
