### ISSUE TITLE
Feature request: optionally create and use local history file if it does not exist

### ISSUE THREAD

**Issue by uhkeller** [randy3k/radian#465]
Currently, radian uses a local (folder-specific) history file only if it already exists. I *always* want a local history file as it rarely makes sense to share the history across projects. So I always have to remember to create an empty history file before starting work on a new project. It would be much more convenient if there was an option `radian.history_always_use_local` or something similar, which, when set to `TRUE` would create the local history file in case it does not yet exist.

**Comment by randy3k** [comment]
I am on mobile now. There is an option to force using local history, try `radian --help`.

**Comment by uhkeller** [comment]
Oh sorry, I didn't look for an option. Thanks!
