### ISSUE TITLE
Colored text output not working

### ISSUE THREAD

**Issue by khvorov45** [randy3k/radian#468]
![Screenshot from 2024-02-06 14-26-03](https://github.com/randy3k/radian/assets/44919476/23dcd843-c5f9-4ea1-ab27-6fb8ac4ef4f7)

Left - radian console, right - normal R console.
Test code is

```r
cat('\033[0;32m hello world  \033[0m \n')
```

It's green in the R console but white in the radian console.

```
radian version: 0.6.11
r executable: /usr/lib/R/bin/R
r version: 4.3.2
python executable: /usr/bin/python3
python version: 3.10.12
```

**Comment by randy3k** [comment]
Oh, it is due to a recent commit, please fix soon.
