### ISSUE TITLE
feature request: keybinding for %>%

### ISSUE THREAD

**Issue by foonwong** [randy3k/radian#71]
Is it possible to add key binding for the pipe operator? It makes a big
difference when writing tidyverse style code. In Rstudio it's Ctrl-Shift-m.

Thanks!

**Comment by randy3k** [comment]
This issue actually is related to a more general issue of supporting user custom keybindings. I don't know how useful it will be in a terminal because a tty doesn't recognize `ctrl + shift + <anykey>`. It may be just easier for users to configure their terminal program for such a purpose.

**Comment by randy3k** [comment]
radian v0.4 will have a setting `radian.escape_key_map` to allow user-defined escape keys.
