### ISSUE TITLE
radian cannot find macros/system.Rd

### ISSUE THREAD

**Issue by pat-s** [randy3k/radian#74]
When calling functions I get the following warnings:

```
Warning messages:
1: In file(con, "r") :
  cannot open file '/usr/lib64/R/share/Rd/macros/system.Rd': No such file or directory
```

I do not get them when running the same functions with "plain R" from the command line (either --vanilla or normal). 

I'm on Arch and `R_HOME` is `/usr/lib64/R`.

Session Info after normal startup:

```r
sessioninfo::session_info()                                                                        
─ Session info ──────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Antergos Linux              
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2019-01-03                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source                            
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.2)                    
 cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.2)                    
 colorout    * 1.2-0   2018-12-28 [1] Github (jalvesaq/colorout@cc5fbfa)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)                    
 fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.2)                    
 git2r         0.23.0  2018-07-17 [1] CRAN (R 3.5.2)                    
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.2)                    
 Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.2)                    
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)                    
 usethis     * 1.4.0   2018-08-14 [1] CRAN (R 3.5.2)                    
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)                    

[1] /home/pjs/R/x86_64-pc-linux-gnu-library/3.5
[2] /usr/lib/R/library
```

**Comment by randy3k** [comment]
I got no issue on my machine. It seems to me your installation of R is missing some files.

<img width="530" alt="screen shot 2019-01-09 at 9 35 41 pm" src="https://user-images.githubusercontent.com/1690993/50942404-96b99b00-1456-11e9-8130-bf86e95e064f.png">

**Comment by pat-s** [comment]
It's the standard "R" package on Arch. I only get these warnings in `radian`, that's why I posted. Do you have an idea what could be different here? I also cannot see which function triggers the error. 

Haven't yet faced this problem in other projects when running `radian`. That's strange. 

However, it's not only the warning in the end but apparently something is not working correctly in the background as I get the exclamation mark in this example and a different outcome.

Tedious problem. Thanks for checking so quickly!

**Comment by randy3k** [comment]
By the way, does the file `/usr/lib64/R/share/Rd/macros/system.Rd` exist?

**Comment by adomingues** [comment]
Hi @randy3k. I am not the OP but I am having similar issues. I am detailing bellow the issues.

> By the way, does the file `/usr/lib64/R/share/Rd/macros/system.Rd` exist?

No.

> Would there be a chance that you have two versions of R located at `/usr/lib/R` and `/usr/lib64/R`?

No, only the first.

I am on Ubuntu 18.04.


Cheers and thanks lot for this package.

**Comment by pat-s** [comment]
Ah sorry, forgot to follow-up. Thanks @adomingues.

**Comment by randy3k** [comment]
For some reasons, if your system is missing the file `macros/system.Rd`, it could be an issue. Though I am not sure why the ordinal R doesn't issue a warning.

**Comment by adomingues** [comment]
I dug some more and the system has `/usr/share/R/share/Rd/macros/system.Rd` and `/usr/lib/R/`, so it looks like radian is looking for things in `*/lib64/*` folders but these are in `*/lib/*` folders. Could this be the case?

**Comment by randy3k** [comment]
Could you report the following from both original R and radian?
```
Sys.getenv(“R_SHARE_DIR”)                                                                   
```

**Comment by adomingues** [comment]
Here it is:

- radian, `"/usr/lib/R/share"`
- R, `"/usr/lib/R/share"`

A few notes that might be useful for debugging:

- with a fresh computer restart and a new radian session the issue went away.
- the issue occurs in the context of building an R package inside radian with devtools::load_all(). Once that command is issued searching for help, for example `?paste`, throws the error

> Error in file(con, "r") : cannot open the connection
> In addition: Warning message:
> In file(con, "r") :
>   cannot open file '/usr/lib/R/share/Rd/macros/system.Rd': No such file or directory

- following the same steps in `R` works fine. 
- R version 3.5.2

I hope this helps.

**Comment by randy3k** [comment]
Hm, in your case, I believe `R.home("share")` is also `"/usr/lib/R/share"` in both R and radian. I am trying to identify the differences between the two programs.

Could you check again if `/usr/lib/R/share/Rd/macros/system.Rd` exist? I don't think the error is related to `lib` and `lib64` since your error is 
```
cannot open file '/usr/lib/R/share/Rd/macros/system.Rd': No such file or directory
```

**Comment by randy3k** [comment]
It could be great if there is a docker image which this can be reproudced.

**Comment by adomingues** [comment]
> Hm, in your case, I believe `R.home("share")` is also `"/usr/lib/R/share"` in both R and radian. I am trying to identify the differences between the two programs.

I think you are on to something. `R.home("share")` in:

- `radian` is `"/usr/lib/R/share"`
- `R` is `"/usr/share/R/share"`

> Could you check again if `/usr/lib/R/share/Rd/macros/system.Rd` exist?

Checked again, it doesn't. Sorry about the `lib64` confusion.

Sadly I don't have the time at moment create a docker image to sort this out. I would have to learn how to create the image in the first place since my knowledge of docker is very limited. 

If you can't solve the issue without it I still appreciate your help and time on trying to solve this.

**Comment by randy3k** [comment]
In R, `Sys.getenv("R_SHARE_DIR")` and `R.home("share")` give you different result? It's odd.

Anyway, I think I know what's happening now. `radian` assume that `R.home("share")` is always `file.path(R.home(), "share")`. But it is not always the case.

**Comment by adibender** [comment]
btw, this older issues from me seems related: https://github.com/randy3k/radian/issues/68
Part of the problem was chromium vs. chrome so I closed it. But issue still persists in combination with devtools

**Comment by adomingues** [comment]
Ok, this is weird. After re-start I know get the same result for `Sys.getenv("R_SHARE_DIR")` and `R.home("share")` in `R`: `"/usr/share/R/share"`. The output in `radian is still `"/usr/lib/R/share"` for both commands.

**Comment by randy3k** [comment]
f4b604171d6e4b7f8c978927d96f6c6347517ef4 should fix it.

**Comment by jrosell** [comment]
Setting R_SHARE_DIR=/usr/share/R/share/ at my ~/.Renviron solve it.
