### ISSUE TITLE
prompt updates through addTaskCallback => no color, no completion 

### ISSUE THREAD

**Issue by WillForan** [randy3k/radian#75]
I find it useful to have the time (of last finished process) in the prompt. Updating the prompt with a task callback by setting `options(prompt=...)` looses color and completion. Using `options(radian.prompt=....)` has no effect.

My `~/.Rprofile` looks like
```
 updatePrompt <- function(...) {
   options(prompt=format(Sys.time(), "%X\n> ")
   return(T)
}
.First <- function(...) {
  addTaskCallback(updatePrompt)
  updatePrompt()
}
```

```
 cat /etc/debian_version && radian --version 
9.3
radian version: 0.3.1
r executable: /usr/lib/R/bin/R
r version: 3.4.3
python executable: /usr/bin/python3
python version: 3.5.3
```

**Comment by randy3k** [comment]
It is expected to lose the color, you may add it back by using the escape color sequences. I am not totally understanding why it’s breaking completions though.

**Comment by WillForan** [comment]
Sorry was ambiguous! Syntax highlighting is the color that is lost.

**Comment by randy3k** [comment]
I got no issue.

```r
updatePrompt <- function(...) {
   options(prompt=format(Sys.time(), "\033[0;34m%X\n>\033[0m "))
   return(T)
}
.First <- function(...) {
  addTaskCallback(updatePrompt)
  updatePrompt()
}
```
<img width="397" alt="screen shot 2019-01-08 at 1 19 25 am" src="https://user-images.githubusercontent.com/1690993/50813157-7fa66c00-12e3-11e9-9fa9-0b943195bfa6.png">

**Comment by WillForan** [comment]
I tried on another computer, no problem!

Any update to the prompt on the original computer breaks radian goodness (pop up suggestions, syntax highlighting). Maybe it's a python library issue? 

The working prompt is on debian testing, the busted prompt environment is on debian stable.

I think it's fine to close this as specific to something weird on a specific environment. Sorry for the noise! 

![radian2](https://user-images.githubusercontent.com/680742/50844646-29fcae80-1339-11e9-989c-4c703ee4b86e.png)
![radian](https://user-images.githubusercontent.com/680742/50844662-2ec16280-1339-11e9-94ab-ae8b0c460db5.png)
