### ISSUE TITLE
README: suggest using pip3?

### ISSUE THREAD

**Issue by briatte** [randy3k/radian#76]
On my machine (macOS 10.13), installing radian failed when I tried running the `pip` install command provided in the README, because `six` would not uninstall ("protected by `distutils`).

However, installation succeeded when I tried with `pip3`. Perhaps it might help to suggest that workaround in the README?

**Comment by randy3k** [comment]
I believe that your `pip` is for the system python 2 and the `six` package was install by `distutils`. You could simply upgrade it using `pip install -I six`.

**Comment by briatte** [comment]
I have tried that, but:

```
$ pip install -I six
Collecting six
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/six.pyc'
Consider using the `--user` option or check the permissions.
```

**Comment by briatte** [comment]
Will do, thanks.
