### ISSUE TITLE
Crashing on invoking reticulate::repl_python()

### ISSUE THREAD

**Issue by docbiz** [randy3k/radian#77]
I am currently running Ubuntu 18.04, R 3.5.2, and Python 3.7.1. The reticulate package works in a regular R session, but not in a radian session; it crashes back out to the shell.

Radian:
```
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Platform: x86_64-pc-linux-gnu (64-bit)

r$> reticulate::repl_python()
free(): invalid pointer
[1]    17278 abort (core dumped)  radian
```

Regular R session:
```
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> reticulate::repl_python()
Python 3.7.1 (/usr/bin/python3.7)
Reticulate 1.10 REPL -- A Python interpreter in R.
>>>
```

Let me know if there's any information you need to try and figure this one out!

**Comment by randy3k** [comment]
Meanwhile, try my patches version of reticulate 

```
devtools::install_github(“rstudio/reticulate#279”)
```

**Comment by docbiz** [comment]
Thanks (both for this and the general work on radian)! The patched version works, but I've noticed something small: it's not respecting this line in my .zshrc file:
```
export RETICULATE_PYTHON="/usr/bin/python3.7"
```
Note that `reticulate::pyconfig()` returns `/usr/bin/python3.7` when I open a regular R session (and it says that it was forced by the shell variable), but it defaults to `/usr/bin/python3` in radian.

**Comment by randy3k** [comment]
It is expected because radian is a python package. We have to force reticulate to use the same build of python.

You will need to install radian to the corresponding python library if you want to use a different version of python.

**Comment by docbiz** [comment]
I see! It all works now—thanks for your help and, again, for all your work on radian.

**Comment by randy3k** [comment]
let's keep this open.
