### ISSUE TITLE
Python Indentation

### ISSUE THREAD

**Issue by MikeJohnPage** [randy3k/radian#78]
Apologies if I have missed something obvious, but how does one set radian to automatically indent python code when entering reticulate mode (using ~)?

For example, creating a simple for loop like below, the code does not automatically indent before the print statement:

```
nums = [1, 2, 3]

for num in nums:
print(num)
```
When of course it should be:

```
nums = [1, 2, 3]

for num in nums:
    print(num)
```

While the indents can be added manually, I presume there must be a more elegant solution? I have messed around with the indent rules in the .Rprofile settings:

```
  # auto indentation for new line and curly braces
    radian.auto_indentation = TRUE,
    radian.tab_size = 4,
```
but this did not solve the issue. Any help would be appreciated.

**Comment by randy3k** [comment]
`radian.auto_indentation` doesn't currently honor any indentation need of python code. I would keep this in mind when I touch the codebase.

Perhaps the easier implementation is to apply indentation when the last line is ended with a colon?
