### ISSUE TITLE
Radian crashes upon loading reticulate

### ISSUE THREAD

**Issue by paulklemm** [randy3k/radian#79]
When loading `reticulate`, I encounter the following error with the latest version of `radian`:

```R
r$> library(reticulate)
The host python environment is /usr/bin/python3
and `radian` is forcing `reticulate` to use this version of python.
Any python packages needed, e.g., `tensorflow` and `keras`,
have to be available to the current python environment.

File an issue at https://github.com/randy3k/radian if you encounter any
difficulties in loading `reticulate`.
free(): invalid pointer
[1]    8741 abort (core dumped)  singularity exec  radian
```

I'm using radian in an HPC environment in a docker image. The image can be found here: [https://hub.docker.com/r/paulklemm/mytidyverse](https://hub.docker.com/r/paulklemm/mytidyverse).

You can reproduce this by running: `docker run -ti --rm paulklemm/mytidyverse:base-3.5.2-1 radian` and load `reticulate`. The dockerfile for the `base-3.5.2-1` image is located here: [https://github.com/paulklemm/mytidyverse/blob/master/Dockerfile](https://github.com/paulklemm/mytidyverse/blob/master/Dockerfile)

Loading `reticulate` using the standard `R` shell on the same container works (docker run -ti --rm paulklemm/mytidyverse:base-3.5.2-1 R).

**Comment by randy3k** [comment]
It is a known issue.

Basically, it is an issue of reticulate failing to initialize. I have submitted an PR to reticulate a while ago https://github.com/rstudio/reticulate/pull/279 but that is still not merged.

For now, we could try my patched version of `reticulate`.
```
devtools::install_github(“rstudio/reticulate#279”)
```

related issue: https://github.com/randy3k/radian/issues/77

**Comment by paulklemm** [comment]
Wait, you fixed this already on May 17th of last year and they still did bother merging it? That's not cool.

Thanks, the patched version works. Feel free to close the issue.

**Comment by randy3k** [comment]
We are now patching reticulate directly in radian. No more waiting for the merge.
