### ISSUE TITLE
R history in radian

### ISSUE THREAD

**Issue by mschubert** [randy3k/radian#81]
R provides an option to record and load previously executed commands to/from a history file. It is common to have e.g. the following options set in a user's *~/.Rprofile*:

```r
if (interactive()) {
    .Last = function() try(utils::savehistory("~/.Rhistory"))
    utils::loadhistory("~/.Rhistory")
}
```

However, trying to load the history file from *radian* I get the following error:

```r
r$> utils::loadhistory("~/.Rhistory")
Error in .External2(C_loadhistory, file) : no history mechanism available
```

As this is a valid R command that *radian* errors on, should this maybe be handled by *radian* somehow?

Also note: this breaks running `pytest` for me (related to #80).

**Comment by randy3k** [comment]
radian manages its own history file `~/.radian_history` and we definitely don't want to affect the history file of R. My recommendation is to detect the use of `radian`, perhaps something like

```r
if (interactive() & Sys.getenv("RADIAN_VERSION") == "") {

}
```

**Comment by randy3k** [comment]
BTW, why this is necessary? R already saves and loads history in default.

**Comment by mschubert** [comment]
> My recommendation is to detect the use of `radian`

Yes, that works too. Thanks!

> BTW, why this is necessary? R already saves and loads history in default.

It does not save the command history between sessions unless specified like the above
