### ISSUE TITLE
Loading packages only for radian interactive session

### ISSUE THREAD

**Issue by devillemereuil** [randy3k/radian#90]
Is there currently a way to load packages only when starting R from radian? I can't check whether the radian options are set up from .Rprofile, as radian seems to load the content of .Rprofile before settings its own options (which makes sense).

EDIT : Made the wording clearer.

**Comment by randy3k** [comment]
Try this
```r
if (Sys.getenv("RADIAN_VERSION") == "") {
    library(tidyverse)
}
```

**Comment by devillemereuil** [comment]
It does work, thanks! Maybe worth adding to the README? Seems to me like a common occurrence, but I'm obviously biased! ;)

And thanks a lot for this super useful piece of software!
