### ISSUE TITLE
The version limitation 'rchitect>=0.2.3,<0.3.0' conflicts with the latest rchitect-0.3.2

### ISSUE THREAD

**Issue by yurivict** [randy3k/radian#95]
Could you please make a release and post it on PyPI?

Thank you.

**Comment by randy3k** [comment]
There is a prelease, try

```
pip install --pre -U radian
```

**Comment by randy3k** [comment]
I am working towards a new release of radian, but it stills need more work.

**Comment by yurivict** [comment]
```pip install --pre -U radian``` can't be used in packages. They can only take released versions.
Both radian and rchitect packages are from your account, and they are incompatible.
Now all systems will begin to delete ```radian``` ports as broken.

**Comment by randy3k** [comment]
v0.4.0 is out.

**Comment by yurivict** [comment]
Thanks!
