### ISSUE TITLE
Reticulate Mode Crashes

### ISSUE THREAD

**Issue by gfleetwood** [randy3k/radian#96]
Hi,

I'm trying radian's reticulate mode and had an error pop up which closed the python REPL on two different systems once I entered `~` and pressed `Enter`.

1. Windows 10  | R 3.6.0 | Python 3.6.2

Error in mapply(function(from, to) paste(lines[from:to], collapse = "\n"), :
zero-length inputs cannot be mixed with those of non-zero length

2. Ubuntu 18.04 | R 3.4.4 | Python 3.6.5

Error in initialize_python(required_module, use_environment) :
Python shared library '' not found, Python bindings not loaded.

Would you happen to know what's wrong? 

Also, do you know if it would be possible to use [rpy2](https://rpy2.readthedocs.io/en/version_2.8.x/) within the python REPL? I'm trying to build a full conduit between Python and R but had trouble with rpy2 since it seems that the two different R processes (the original and the one opened from python with rpy2) clashed. Theoretically I would want to link use rpy2 to link to the original  R process instead of starting another one.

**Comment by randy3k** [comment]
What versions of radian are they? Try the latest v0.4.0, there are some improvements for handling reticulate.

**Comment by gfleetwood** [comment]
I'm using radian v0.4.0. Just started using it this week.

**Comment by randy3k** [comment]
could you show `radian --version` for both machines?

**Comment by randy3k** [comment]
Speaking of `rpy2`, I have written another package for calling R from python: https://github.com/randy3k/rchitect/

**Comment by gfleetwood** [comment]
Great! I'll check it out.

My bad, the Ubuntu machine has 0.4.0 but for some reason pip is only installing 0.3.4 on the Windows machine. I did `pip install -U radian` on the Windows machine but now radian just hangs and doesn't load. It's stuck on this screen: https://drive.google.com/file/d/1-auiPo0C6RhA-rFndwIvDwmbWPWiJYPV/view?usp=sharing

**Comment by randy3k** [comment]
>Great! I'll check it out. ...

@gfleetwood 

For the rchitect issue, it seems that you just had a wrong call `rchitect.eval` instead of `rchitect.revel`

**Comment by randy3k** [comment]
>Great! I'll check it out. ...

@gfleetwood 

Anconda python should work out of the box. Is radian running fine on your Ubuntu? And I really had no clue why radia in your Windows failed.

**Comment by gfleetwood** [comment]
Right. So rchitect works in the python shell but not in the notebook.

Radian is running well on Ubuntu except for the error I get with reticulate mode.

**Comment by randy3k** [comment]
You need to do `library(reticulate)` to load the `py` object explicitly.

**Comment by randy3k** [comment]
I am still confused, what’s working and what’s not. It would be great for you to summarize the R/python/platform information/error message information for the non working cases.

**Comment by gfleetwood** [comment]
Right. So there are three machines that I tried to run radian's reticulate mode in.

**Windows 10 VM**: Running R 3.6.0 and Python 3.6.2. That gives me this error when I try to activate reticulate mode:

`Error in mapply(function(from, to) paste(lines[from:to], collapse = "\n"), :
zero-length inputs cannot be mixed with those of non-zero length`

**Ubuntu 18.04**:  RuningR 3.4.4  and Python 3.6.5. Gives me this error when I try to activate reticulate mode:

`Error in initialize_python(required_module, use_environment) :
Python shared library '' not found, Python bindings not loaded.`

**Windows 10**:  Running R 3.4.3 and Python 3.6.5. This works fine with reticulate mode.

**Comment by gfleetwood** [comment]
@randy3k Have you looked into using radian as the backend for an IDE?

**Comment by randy3k** [comment]
For example?

**Comment by randy3k** [comment]
> Right. So there are three machines that I tried to run radian's reticulate mode in with radian 0.4.0
> 
> **Windows 10 VM**: Running R 3.6.0 and Python 3.6.2. With radian 0.3.4 I got this error when I try to activate reticulate mode:
> 
> `Error in mapply(function(from, to) paste(lines[from:to], collapse = "\n"), : zero-length inputs cannot be mixed with those of non-zero length`
> 

It is kinda expected for radian 0.3.4.


> When I upgraded to radian 0.4.0 radian would just hang on the command line and not open.
> 

Not sure why. Cannot help without more details.

> **Ubuntu 18.04**: RuningR 3.4.4 and Python 3.6.5. Gives me this error when I try to activate reticulate mode:
> 
> `Error in initialize_python(required_module, use_environment) : Python shared library '' not found, Python bindings not loaded.`
> 

What is the result of `reticulate::py_discover_config()`?

> **Windows 10**: Running R 3.4.3 and Python 3.6.5. This works fine with reticulate mode.

Great!

**Comment by gfleetwood** [comment]
Well, sort of like how IPython is the backend for the Jupyter notebook, having radian as the backend for a notebook-like interface. 

If I run reticulate::py_discover_config() in radian I get:

```
python:         /home/gordon/anaconda3/bin/python
libpython:      [NOT FOUND]
pythonhome:     /home/gordon/anaconda3:/home/gordon/anaconda3
version:        3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)  [GCC 7.2.0]
numpy:          /home/gordon/anaconda3/lib/python3.6/site-packages/numpy
numpy_version:  1.16.3

NOTE: Python version was forced by RETICULATE_PYTHON
```

**Comment by randy3k** [comment]
Let's track the jupyter notehook issue in rchitect.

Also, I believe the error of the ubuntu build is now fixed with the latest reticulate. The relevant fix is: https://github.com/rstudio/reticulate/commit/8df7bf367f195a76f8693cde12ee214e916dcf11#diff-951791f1fb37d9e5b0f0cf852ce38d83

**Comment by randy3k** [comment]
> Well, sort of like how IPython is the backend for the Jupyter notebook,

The two projects have been split. The so-called "IPython" notebook is now "Jupyter" notebook. The IPython is now only a command line program for python, and radian has a very similar role for R.

For jupyter notebook, there is [`IRkernel`](https://github.com/IRkernel/IRkernel) for R kernel by the way.

**Comment by gfleetwood** [comment]
Thanks! I updated reticulate and radian is now working on Ubuntu. 

It's not the R kernel that's important, it's the interoperability. I don't know if you're familiar with the [Beaker Notebook](https://github.com/twosigma/beaker-notebook-archive), but it supported the use of multiple languages within the same notebook and the ability to pass/access data between the different processes. 

But yeah, thanks again. Feel free to close this.
